<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <OutputType>Exe</OutputType>
    <AssemblyName>Chaos.TestFramework.Runtime</AssemblyName>
    <RootNamespace>Chaos.TestFramework.Runtime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Chaos.TestFramework.Sdk/Chaos.TestFramework.Sdk.csproj" />
  </ItemGroup>
</Project>
