
public class Program
{
    static int Main()
    {
        int failures = 0;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method0(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 0;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method1(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 1;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method2(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 2;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method3(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 3;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method4(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 4;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method5(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 5;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method6(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 6;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method7(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 7;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method8(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 8;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method9(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 9;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method10(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 10;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method11(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 11;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method12(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 12;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method13(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 13;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method14(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 14;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method15(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 15;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method16(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 16;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method17(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 17;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method18(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 18;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method19(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 19;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method20(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 20;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method21(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 21;
        InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode = 0; InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry.Method22(); failures += InterfaceDispatchPinvokeDllimportPrimitiveNumericConversionsCorePatchEntry._exitCode << 22;
        return failures;
    }
}
