<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ErrorInfoBasicSubjects</AssemblyName>
    <RootNamespace>ErrorInfoBasicSubjects</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ErrorInfoBasicSubjects.cs" />
    <Compile Include="ErrorInfoBasicNativeEntry.cs" />
  </ItemGroup>
</Project>
