// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Xml.Xsl;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System;

namespace AutoGenerated.System_Private_CoreLib
{
    public unsafe partial class System_MemoryExtensionsTests
    {

        [Fact]
        [HotUpdate]
        public long AsMemory_0_string_0()
        {
            var result_0_0 = global::System.MemoryExtensions.AsMemory(default(string)!);
            return (object)(result_0_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_0_string_0()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_0_string_1()
        {
            var result_0_1 = global::System.MemoryExtensions.AsMemory("");
            return (object)(result_0_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_0_string_1()
        {
            _ = global::System.MemoryExtensions.AsMemory("");
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_1_string_int_0()
        {
            var result_1_0 = global::System.MemoryExtensions.AsMemory(default(string)!, default(int));
            return (object)(result_1_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_1_string_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_1_string_int_1()
        {
            var result_1_1 = global::System.MemoryExtensions.AsMemory("", default(int));
            return (object)(result_1_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_1_string_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory("", default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_1_string_int_2()
        {
            var result_1_2 = global::System.MemoryExtensions.AsMemory(default(string)!, (int)0);
            return (object)(result_1_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_1_string_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_2_string_System_Index_0()
        {
            var result_2_0 = global::System.MemoryExtensions.AsMemory(default(string)!, default(System.Index)!);
            return (object)(result_2_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_2_string_System_Index_0()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, default(System.Index)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_2_string_System_Index_1()
        {
            var result_2_1 = global::System.MemoryExtensions.AsMemory("", default(System.Index)!);
            return (object)(result_2_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_2_string_System_Index_1()
        {
            _ = global::System.MemoryExtensions.AsMemory("", default(System.Index)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_2_string_System_Index_2()
        {
            var result_2_2 = global::System.MemoryExtensions.AsMemory(default(string)!, System.Index.Start);
            return (object)(result_2_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_2_string_System_Index_2()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, System.Index.Start);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_3_string_int_int_0()
        {
            var result_3_0 = global::System.MemoryExtensions.AsMemory(default(string)!, default(int), default(int));
            return (object)(result_3_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_3_string_int_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_3_string_int_int_1()
        {
            var result_3_1 = global::System.MemoryExtensions.AsMemory("", default(int), default(int));
            return (object)(result_3_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_3_string_int_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory("", default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_3_string_int_int_2()
        {
            var result_3_2 = global::System.MemoryExtensions.AsMemory(default(string)!, (int)0, default(int));
            return (object)(result_3_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_3_string_int_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_3_string_int_int_3()
        {
            var result_3_3 = global::System.MemoryExtensions.AsMemory(default(string)!, default(int), (int)0);
            return (object)(result_3_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_3_string_int_int_3()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_4_string_System_Range_0()
        {
            var result_4_0 = global::System.MemoryExtensions.AsMemory(default(string)!, default(System.Range)!);
            return (object)(result_4_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_4_string_System_Range_0()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, default(System.Range)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_4_string_System_Range_1()
        {
            var result_4_1 = global::System.MemoryExtensions.AsMemory("", default(System.Range)!);
            return (object)(result_4_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_4_string_System_Range_1()
        {
            _ = global::System.MemoryExtensions.AsMemory("", default(System.Range)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_4_string_System_Range_2()
        {
            var result_4_2 = global::System.MemoryExtensions.AsMemory(default(string)!, System.Range.All);
            return (object)(result_4_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_4_string_System_Range_2()
        {
            _ = global::System.MemoryExtensions.AsMemory(default(string)!, System.Range.All);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_5_System_Int32_0()
        {
            var result_5_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!);
            return (object)(result_5_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_5_System_Int32_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_5_System_Int32_1()
        {
            var result_5_1 = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>());
            return (object)(result_5_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_5_System_Int32_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>());
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_5_System_Int32_2()
        {
            var result_5_2 = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! });
            return (object)(result_5_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_5_System_Int32_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! });
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_6_System_Int32_int_0()
        {
            var result_6_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int));
            return (object)(result_6_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_6_System_Int32_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_6_System_Int32_int_1()
        {
            var result_6_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, (int)0);
            return (object)(result_6_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_6_System_Int32_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_6_System_Int32_int_2()
        {
            var result_6_2 = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(int));
            return (object)(result_6_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_6_System_Int32_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_6_System_Int32_int_3()
        {
            var result_6_3 = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(int));
            return (object)(result_6_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_6_System_Int32_int_3()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_7_System_Int32_System_Index_0()
        {
            var result_7_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(System.Index)!);
            return (object)(result_7_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_7_System_Int32_System_Index_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(System.Index)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_7_System_Int32_System_Index_1()
        {
            var result_7_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, System.Index.Start);
            return (object)(result_7_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_7_System_Int32_System_Index_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, System.Index.Start);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_7_System_Int32_System_Index_2()
        {
            var result_7_2 = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(System.Index)!);
            return (object)(result_7_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_7_System_Int32_System_Index_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(System.Index)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_7_System_Int32_System_Index_3()
        {
            var result_7_3 = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(System.Index)!);
            return (object)(result_7_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_7_System_Int32_System_Index_3()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(System.Index)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_8_System_Int32_int_int_0()
        {
            var result_8_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int), default(int));
            return (object)(result_8_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_8_System_Int32_int_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_8_System_Int32_int_int_1()
        {
            var result_8_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, (int)0, default(int));
            return (object)(result_8_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_8_System_Int32_int_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_8_System_Int32_int_int_2()
        {
            var result_8_2 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int), (int)0);
            return (object)(result_8_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_8_System_Int32_int_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_8_System_Int32_int_int_3()
        {
            var result_8_3 = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(int), default(int));
            return (object)(result_8_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_8_System_Int32_int_int_3()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_8_System_Int32_int_int_4()
        {
            var result_8_4 = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(int), default(int));
            return (object)(result_8_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_8_System_Int32_int_int_4()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_9_System_Int32_System_Range_0()
        {
            var result_9_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(System.Range)!);
            return (object)(result_9_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_9_System_Int32_System_Range_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, default(System.Range)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_9_System_Int32_System_Range_1()
        {
            var result_9_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, System.Range.All);
            return (object)(result_9_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_9_System_Int32_System_Range_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.Int32[])!, System.Range.All);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_9_System_Int32_System_Range_2()
        {
            var result_9_2 = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(System.Range)!);
            return (object)(result_9_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_9_System_Int32_System_Range_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(System.Array.Empty<int>(), default(System.Range)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_9_System_Int32_System_Range_3()
        {
            var result_9_3 = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(System.Range)!);
            return (object)(result_9_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_9_System_Int32_System_Range_3()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new int[2] { default(int)!, default(int)! }, default(System.Range)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_10_System_ArraySegmentint_0()
        {
            var result_10_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!);
            return (object)(result_10_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_10_System_ArraySegmentint_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_10_System_ArraySegmentint_1()
        {
            var result_10_1 = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }));
            return (object)(result_10_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_10_System_ArraySegmentint_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_11_System_ArraySegmentint_int_0()
        {
            var result_11_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int));
            return (object)(result_11_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_11_System_ArraySegmentint_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_11_System_ArraySegmentint_int_1()
        {
            var result_11_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, (int)0);
            return (object)(result_11_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_11_System_ArraySegmentint_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_11_System_ArraySegmentint_int_2()
        {
            var result_11_2 = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_11_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_11_System_ArraySegmentint_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_12_System_ArraySegmentint_int_int_0()
        {
            var result_12_0 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int), default(int));
            return (object)(result_12_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_12_System_ArraySegmentint_int_int_0()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_12_System_ArraySegmentint_int_int_1()
        {
            var result_12_1 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, (int)0, default(int));
            return (object)(result_12_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_12_System_ArraySegmentint_int_int_1()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_12_System_ArraySegmentint_int_int_2()
        {
            var result_12_2 = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int), (int)0);
            return (object)(result_12_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_12_System_ArraySegmentint_int_int_2()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(default(System.ArraySegment<System.Int32>)!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long AsMemory_12_System_ArraySegmentint_int_int_3()
        {
            var result_12_3 = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }), default(int), default(int));
            return (object)(result_12_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_AsMemory_12_System_ArraySegmentint_int_int_3()
        {
            _ = global::System.MemoryExtensions.AsMemory<int>(new System.ArraySegment<System.Int32>(new int[] { 0, 1 }), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long Trim_13_System_Memoryint_int_0()
        {
            var result_13_0 = global::System.MemoryExtensions.Trim<int>(default(System.Memory<System.Int32>)!, default(int));
            return (object)(result_13_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_13_System_Memoryint_int_0()
        {
            _ = global::System.MemoryExtensions.Trim<int>(default(System.Memory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long Trim_13_System_Memoryint_int_1()
        {
            var result_13_1 = global::System.MemoryExtensions.Trim<int>(default(System.Memory<System.Int32>)!, (int)0);
            return (object)(result_13_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_13_System_Memoryint_int_1()
        {
            _ = global::System.MemoryExtensions.Trim<int>(default(System.Memory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long Trim_13_System_Memoryint_int_2()
        {
            var result_13_2 = global::System.MemoryExtensions.Trim<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_13_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_13_System_Memoryint_int_2()
        {
            _ = global::System.MemoryExtensions.Trim<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_14_System_Memoryint_int_0()
        {
            var result_14_0 = global::System.MemoryExtensions.TrimStart<int>(default(System.Memory<System.Int32>)!, default(int));
            return (object)(result_14_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_14_System_Memoryint_int_0()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(default(System.Memory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_14_System_Memoryint_int_1()
        {
            var result_14_1 = global::System.MemoryExtensions.TrimStart<int>(default(System.Memory<System.Int32>)!, (int)0);
            return (object)(result_14_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_14_System_Memoryint_int_1()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(default(System.Memory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_14_System_Memoryint_int_2()
        {
            var result_14_2 = global::System.MemoryExtensions.TrimStart<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_14_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_14_System_Memoryint_int_2()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_15_System_Memoryint_int_0()
        {
            var result_15_0 = global::System.MemoryExtensions.TrimEnd<int>(default(System.Memory<System.Int32>)!, default(int));
            return (object)(result_15_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_15_System_Memoryint_int_0()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(default(System.Memory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_15_System_Memoryint_int_1()
        {
            var result_15_1 = global::System.MemoryExtensions.TrimEnd<int>(default(System.Memory<System.Int32>)!, (int)0);
            return (object)(result_15_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_15_System_Memoryint_int_1()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(default(System.Memory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_15_System_Memoryint_int_2()
        {
            var result_15_2 = global::System.MemoryExtensions.TrimEnd<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_15_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_15_System_Memoryint_int_2()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(new System.Memory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long Trim_16_System_ReadOnlyMemoryint_int_0()
        {
            var result_16_0 = global::System.MemoryExtensions.Trim<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
            return (object)(result_16_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_16_System_ReadOnlyMemoryint_int_0()
        {
            _ = global::System.MemoryExtensions.Trim<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long Trim_16_System_ReadOnlyMemoryint_int_1()
        {
            var result_16_1 = global::System.MemoryExtensions.Trim<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
            return (object)(result_16_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_16_System_ReadOnlyMemoryint_int_1()
        {
            _ = global::System.MemoryExtensions.Trim<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long Trim_16_System_ReadOnlyMemoryint_int_2()
        {
            var result_16_2 = global::System.MemoryExtensions.Trim<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_16_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_16_System_ReadOnlyMemoryint_int_2()
        {
            _ = global::System.MemoryExtensions.Trim<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_17_System_ReadOnlyMemoryint_int_0()
        {
            var result_17_0 = global::System.MemoryExtensions.TrimStart<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
            return (object)(result_17_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_17_System_ReadOnlyMemoryint_int_0()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_17_System_ReadOnlyMemoryint_int_1()
        {
            var result_17_1 = global::System.MemoryExtensions.TrimStart<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
            return (object)(result_17_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_17_System_ReadOnlyMemoryint_int_1()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_17_System_ReadOnlyMemoryint_int_2()
        {
            var result_17_2 = global::System.MemoryExtensions.TrimStart<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_17_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_17_System_ReadOnlyMemoryint_int_2()
        {
            _ = global::System.MemoryExtensions.TrimStart<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_18_System_ReadOnlyMemoryint_int_0()
        {
            var result_18_0 = global::System.MemoryExtensions.TrimEnd<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
            return (object)(result_18_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_18_System_ReadOnlyMemoryint_int_0()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(default(System.ReadOnlyMemory<System.Int32>)!, default(int));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_18_System_ReadOnlyMemoryint_int_1()
        {
            var result_18_1 = global::System.MemoryExtensions.TrimEnd<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
            return (object)(result_18_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_18_System_ReadOnlyMemoryint_int_1()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(default(System.ReadOnlyMemory<System.Int32>)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_18_System_ReadOnlyMemoryint_int_2()
        {
            var result_18_2 = global::System.MemoryExtensions.TrimEnd<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
            return (object)(result_18_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_18_System_ReadOnlyMemoryint_int_2()
        {
            _ = global::System.MemoryExtensions.TrimEnd<int>(new System.ReadOnlyMemory<System.Int32>(new int[] { 0, 1 }), default(int));
        }

        [Fact]
        [HotUpdate]
        public long Trim_19_System_Memorychar_0()
        {
            var result_19_0 = global::System.MemoryExtensions.Trim(default(System.Memory<System.Char>)!);
            return (object)(result_19_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_19_System_Memorychar_0()
        {
            _ = global::System.MemoryExtensions.Trim(default(System.Memory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long Trim_19_System_Memorychar_1()
        {
            var result_19_1 = global::System.MemoryExtensions.Trim(new System.Memory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_19_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_19_System_Memorychar_1()
        {
            _ = global::System.MemoryExtensions.Trim(new System.Memory<System.Char>(new char[] { '{', '}' }));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_20_System_Memorychar_0()
        {
            var result_20_0 = global::System.MemoryExtensions.TrimStart(default(System.Memory<System.Char>)!);
            return (object)(result_20_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_20_System_Memorychar_0()
        {
            _ = global::System.MemoryExtensions.TrimStart(default(System.Memory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_20_System_Memorychar_1()
        {
            var result_20_1 = global::System.MemoryExtensions.TrimStart(new System.Memory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_20_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_20_System_Memorychar_1()
        {
            _ = global::System.MemoryExtensions.TrimStart(new System.Memory<System.Char>(new char[] { '{', '}' }));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_21_System_Memorychar_0()
        {
            var result_21_0 = global::System.MemoryExtensions.TrimEnd(default(System.Memory<System.Char>)!);
            return (object)(result_21_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_21_System_Memorychar_0()
        {
            _ = global::System.MemoryExtensions.TrimEnd(default(System.Memory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_21_System_Memorychar_1()
        {
            var result_21_1 = global::System.MemoryExtensions.TrimEnd(new System.Memory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_21_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_21_System_Memorychar_1()
        {
            _ = global::System.MemoryExtensions.TrimEnd(new System.Memory<System.Char>(new char[] { '{', '}' }));
        }

        [Fact]
        [HotUpdate]
        public long Trim_22_System_ReadOnlyMemorychar_0()
        {
            var result_22_0 = global::System.MemoryExtensions.Trim(default(System.ReadOnlyMemory<System.Char>)!);
            return (object)(result_22_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_22_System_ReadOnlyMemorychar_0()
        {
            _ = global::System.MemoryExtensions.Trim(default(System.ReadOnlyMemory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long Trim_22_System_ReadOnlyMemorychar_1()
        {
            var result_22_1 = global::System.MemoryExtensions.Trim(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_22_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Trim_22_System_ReadOnlyMemorychar_1()
        {
            _ = global::System.MemoryExtensions.Trim(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_23_System_ReadOnlyMemorychar_0()
        {
            var result_23_0 = global::System.MemoryExtensions.TrimStart(default(System.ReadOnlyMemory<System.Char>)!);
            return (object)(result_23_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_23_System_ReadOnlyMemorychar_0()
        {
            _ = global::System.MemoryExtensions.TrimStart(default(System.ReadOnlyMemory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long TrimStart_23_System_ReadOnlyMemorychar_1()
        {
            var result_23_1 = global::System.MemoryExtensions.TrimStart(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_23_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimStart_23_System_ReadOnlyMemorychar_1()
        {
            _ = global::System.MemoryExtensions.TrimStart(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_24_System_ReadOnlyMemorychar_0()
        {
            var result_24_0 = global::System.MemoryExtensions.TrimEnd(default(System.ReadOnlyMemory<System.Char>)!);
            return (object)(result_24_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_24_System_ReadOnlyMemorychar_0()
        {
            _ = global::System.MemoryExtensions.TrimEnd(default(System.ReadOnlyMemory<System.Char>)!);
        }

        [Fact]
        [HotUpdate]
        public long TrimEnd_24_System_ReadOnlyMemorychar_1()
        {
            var result_24_1 = global::System.MemoryExtensions.TrimEnd(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
            return (object)(result_24_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_TrimEnd_24_System_ReadOnlyMemorychar_1()
        {
            _ = global::System.MemoryExtensions.TrimEnd(new System.ReadOnlyMemory<System.Char>(new char[] { '{', '}' }));
        }
    }
}
