#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Benchmark_TryParse_1_string_AuthenticationHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Benchmark_TryParse_1_string_AuthenticationHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_TryParse_1_string_AuthenticationHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_AuthenticationHeaderValueTests_TryParse_1_string_AuthenticationHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Benchmark_TryParse_1_string_CacheControlHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Benchmark_TryParse_1_string_CacheControlHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_TryParse_1_string_CacheControlHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_CacheControlHeaderValueTests_TryParse_1_string_CacheControlHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Benchmark_TryParse_1_string_ContentDispositionHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Benchmark_TryParse_1_string_ContentDispositionHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_TryParse_1_string_ContentDispositionHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentDispositionHeaderValueTests_TryParse_1_string_ContentDispositionHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Benchmark_TryParse_1_string_ContentRangeHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Benchmark_TryParse_1_string_ContentRangeHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_TryParse_1_string_ContentRangeHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ContentRangeHeaderValueTests_TryParse_1_string_ContentRangeHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Benchmark_TryParse_1_string_EntityTagHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Benchmark_TryParse_1_string_EntityTagHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_TryParse_1_string_EntityTagHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_EntityTagHeaderValueTests_TryParse_1_string_EntityTagHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Benchmark_Contains_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Benchmark_Contains_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Benchmark_TryGetValues_1_string_HeaderStringValues_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Benchmark_TryGetValues_1_string_HeaderStringValues_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Contains_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_Contains_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_TryGetValues_1_string_HeaderStringValues_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersNonValidatedTests_TryGetValues_1_string_HeaderStringValues_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_0_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_0_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_0_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_1_string_IEnumerablestring_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_1_string_IEnumerablestring_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Add_1_string_IEnumerablestring_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_0_string_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_0_string_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_0_string_string_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_1_string_IEnumerablestring_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_1_string_IEnumerablestring_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Add_1_string_IEnumerablestring_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Clear_9__9(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Contains_6_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Contains_6_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_GetEnumerator_7__7(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_GetValues_4_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_GetValues_4_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Remove_8_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_Remove_8_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_2_string_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_2_string_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_2_string_string_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_3_string_IEnumerablestring_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_3_string_IEnumerablestring_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryAddWithoutValidation_3_string_IEnumerablestring_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryGetValues_5_string_IEnumerablestring_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryGetValues_5_string_IEnumerablestring_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Benchmark_TryGetValues_5_string_IEnumerablestring_2(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Clear_9__9(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Contains_6_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Contains_6_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_GetEnumerator_7__7(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_GetValues_4_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_GetValues_4_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Remove_8_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_Remove_8_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_2_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_2_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_2_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_3_string_IEnumerablestring_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_3_string_IEnumerablestring_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryAddWithoutValidation_3_string_IEnumerablestring_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryGetValues_5_string_IEnumerablestring_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryGetValues_5_string_IEnumerablestring_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeadersTests_TryGetValues_5_string_IEnumerablestring_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Add_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Add_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Add_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Add_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Clear_3__3(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Contains_4_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Contains_4_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_GetEnumerator_6__6(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_ParseAdd_1_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_ParseAdd_1_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Remove_5_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_Remove_5_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_TryParseAdd_2_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Benchmark_TryParseAdd_2_string_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Clear_3__3(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Contains_4_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Contains_4_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_GetEnumerator_6__6(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_ParseAdd_1_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_ParseAdd_1_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Remove_5_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_Remove_5_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_TryParseAdd_2_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_HttpHeaderValueCollectionSystem_StringTests_TryParseAdd_2_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Benchmark_TryParse_1_string_MediaTypeHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Benchmark_TryParse_1_string_MediaTypeHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_TryParse_1_string_MediaTypeHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeHeaderValueTests_TryParse_1_string_MediaTypeHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Benchmark_TryParse_1_string_MediaTypeWithQualityHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Benchmark_TryParse_1_string_MediaTypeWithQualityHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_TryParse_1_string_MediaTypeWithQualityHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_MediaTypeWithQualityHeaderValueTests_TryParse_1_string_MediaTypeWithQualityHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Benchmark_TryParse_1_string_NameValueHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Benchmark_TryParse_1_string_NameValueHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_TryParse_1_string_NameValueHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueHeaderValueTests_TryParse_1_string_NameValueHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Benchmark_TryParse_1_string_NameValueWithParametersHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Benchmark_TryParse_1_string_NameValueWithParametersHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_TryParse_1_string_NameValueWithParametersHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_NameValueWithParametersHeaderValueTests_TryParse_1_string_NameValueWithParametersHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Benchmark_TryParse_1_string_ProductHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Benchmark_TryParse_1_string_ProductHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_TryParse_1_string_ProductHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductHeaderValueTests_TryParse_1_string_ProductHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Benchmark_TryParse_1_string_ProductInfoHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Benchmark_TryParse_1_string_ProductInfoHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_TryParse_1_string_ProductInfoHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ProductInfoHeaderValueTests_TryParse_1_string_ProductInfoHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Benchmark_TryParse_1_string_RangeConditionHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Benchmark_TryParse_1_string_RangeConditionHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_TryParse_1_string_RangeConditionHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeConditionHeaderValueTests_TryParse_1_string_RangeConditionHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Benchmark_TryParse_1_string_RangeHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Benchmark_TryParse_1_string_RangeHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_TryParse_1_string_RangeHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RangeHeaderValueTests_TryParse_1_string_RangeHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Benchmark_TryParse_1_string_RetryConditionHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Benchmark_TryParse_1_string_RetryConditionHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_TryParse_1_string_RetryConditionHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_RetryConditionHeaderValueTests_TryParse_1_string_RetryConditionHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Benchmark_TryParse_1_string_StringWithQualityHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Benchmark_TryParse_1_string_StringWithQualityHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_TryParse_1_string_StringWithQualityHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_StringWithQualityHeaderValueTests_TryParse_1_string_StringWithQualityHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_TryParse_1_string_TransferCodingHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_TryParse_1_string_TransferCodingHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_TryParse_1_string_TransferCodingWithQualityHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_TryParse_1_string_TransferCodingWithQualityHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_TryParse_1_string_ViaHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_TryParse_1_string_ViaHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_TryParse_1_string_ViaHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_TryParse_1_string_ViaHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_Parse_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_Parse_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_TryParse_1_string_WarningHeaderValue_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_TryParse_1_string_WarningHeaderValue_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_TryParse_1_string_WarningHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_TryParse_1_string_WarningHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCustomTag_0_string_object_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCustomTag_0_string_object_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1_b__3_0_System_Net_Http_Metrics_HttpMetricsEnrichmentContext(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);





// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::Benchmark_TryParse_1_string_TransferCodingHeaderValue_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingHeaderValue_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[77])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::Benchmark_TryParse_1_string_TransferCodingHeaderValue_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingHeaderValue_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[77])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::Parse_0_string_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::Parse_0_string_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::TryParse_1_string_TransferCodingHeaderValue_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_TryParse_1_string_TransferCodingHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[77])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingHeaderValueTests::TryParse_1_string_TransferCodingHeaderValue_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingHeaderValueTests_TryParse_1_string_TransferCodingHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[77])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Benchmark_Parse_0_string_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_Parse_0_string_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = 0;
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[78])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Benchmark_Parse_0_string_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_Parse_0_string_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[78])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[79])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Benchmark_TryParse_1_string_TransferCodingWithQualityHeaderValue_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[79])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Parse_0_string_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::Parse_0_string_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::TryParse_1_string_TransferCodingWithQualityHeaderValue_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_TryParse_1_string_TransferCodingWithQualityHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[79])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests::TryParse_1_string_TransferCodingWithQualityHeaderValue_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_TransferCodingWithQualityHeaderValueTests_TryParse_1_string_TransferCodingWithQualityHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[79])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Benchmark_Parse_0_string_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_Parse_0_string_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = 0;
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[80])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Benchmark_Parse_0_string_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_Parse_0_string_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[80])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Benchmark_TryParse_1_string_ViaHeaderValue_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_TryParse_1_string_ViaHeaderValue_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Benchmark_TryParse_1_string_ViaHeaderValue_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Benchmark_TryParse_1_string_ViaHeaderValue_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Parse_0_string_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::Parse_0_string_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::TryParse_1_string_ViaHeaderValue_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_TryParse_1_string_ViaHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_ViaHeaderValueTests::TryParse_1_string_ViaHeaderValue_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_ViaHeaderValueTests_TryParse_1_string_ViaHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Benchmark_Parse_0_string_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_Parse_0_string_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = 0;
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[82])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Benchmark_Parse_0_string_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_Parse_0_string_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[82])(chaos_arg_0);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Benchmark_TryParse_1_string_WarningHeaderValue_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_TryParse_1_string_WarningHeaderValue_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[83])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Benchmark_TryParse_1_string_WarningHeaderValue_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Benchmark_TryParse_1_string_WarningHeaderValue_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[83])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Parse_0_string_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Parse_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::Parse_0_string_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_Parse_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
	_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
	chaos_locals[0] = ChaosStoreInt64(_i0);
	_i0 = ChaosLoadInt64(chaos_locals[0]);
	return _i0;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::TryParse_1_string_WarningHeaderValue_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_TryParse_1_string_WarningHeaderValue_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[83])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Headers_WarningHeaderValueTests::TryParse_1_string_WarningHeaderValue_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Headers_WarningHeaderValueTests_TryParse_1_string_WarningHeaderValue_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 3) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = 0;
	chaos_locals[0] = _s0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(&chaos_locals[0]);
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[83])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[2] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[2]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests::Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[84])(chaos_arg_0, chaos_arg_1);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests::Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	_s0 = 0;
	_s1 = chaos_static_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c____9__3_0;
	_s2 = _s1;
	{
		if (_s2 == 0)
		{
			_s1 = chaos_static_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 291)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1) -> void {
					auto& _d_entry = s_hotpatch_entries[291];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[16];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_1));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0, chaos_fn_arg_1);
				};
			_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s2;
				const auto chaos_target = _s1;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action_System_Net_Http_Metrics_HttpMetricsEnrichmentContext_, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action_System_Net_Http_Metrics_HttpMetricsEnrichmentContext_.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s2 = _s1;
			{
				auto chaos_value = _s2;
				chaos_static_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c____9__3_0 = chaos_value;
			}
		}
		{
			const auto chaos_arg_1 = _s1;
			const auto chaos_arg_0 = _s0;
			reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[84])(chaos_arg_0, chaos_arg_1);
		}
		return;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests::Benchmark_AddCustomTag_0_string_object_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCustomTag_0_string_object_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	{
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[88])(chaos_arg_0, chaos_arg_1);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests::Benchmark_AddCustomTag_0_string_object_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests_Benchmark_AddCustomTag_0_string_object_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s2 = 0;
	{
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[88])(chaos_arg_0, chaos_arg_1);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Net_Http.System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests+<>c::<Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1>b__3_0(System.Net.Http.Metrics.HttpMetricsEnrichmentContext)
extern "C" void CombinedSubjects_AutoGenerated_System_Net_Http_System_Net_Http_Metrics_HttpMetricsEnrichmentContextTests___c_Benchmark_AddCallback_1_HttpRequestMessage_System_ActionHttpMetricsEnrichmentContext_1_b__3_0_System_Net_Http_Metrics_HttpMetricsEnrichmentContext(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 2) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	chaos_args[1] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_1);
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)

// extern "C" definition for link-time visibility from runtime-entry.cpp
extern "C" const int kAotMethodCount = 293;

extern "C" void ChaosJitRegisterAll() {}