// Auto-generated patch subjects for hotupdate verification
// Each method matches baseline [HotUpdate] subject signature,
// but returns a transformed value for semantic change detection.
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Chaos.TestFramework;

namespace AutoGenerated.Patch
{
    public sealed unsafe class System_Threading_Tasks_ParallelPatchSubjects
    {

        public long Subject_0_For_0_int_int_System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_1_For_0_int_int_System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((int)0, default(int), default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_2_For_0_int_int_System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), (int)0, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_3_For_0_int_int_System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_4_For_1_long_long_System_Action_long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_5_For_1_long_long_System_Action_long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((long)0, default(long), default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_6_For_1_long_long_System_Action_long__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), (long)0, default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_7_For_1_long_long_System_Action_long__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), (long arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_8_For_2_int_int_ParallelOptions_System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_9_For_2_int_int_ParallelOptions_System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((int)0, default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_10_For_2_int_int_ParallelOptions_System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), (int)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_11_For_2_int_int_ParallelOptions_System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_12_For_3_long_long_ParallelOptions_System_Action_long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_13_For_3_long_long_ParallelOptions_System_Action_long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((long)0, default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_14_For_3_long_long_ParallelOptions_System_Action_long__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), (long)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_15_For_3_long_long_ParallelOptions_System_Action_long__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, (long arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_16_For_4_int_int_System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_17_For_4_int_int_System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((int)0, default(int), default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_18_For_4_int_int_System_Action_int__ParallelLoopState__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), (int)0, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_19_For_4_int_int_System_Action_int__ParallelLoopState__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_20_For_5_long_long_System_Action_long__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_21_For_5_long_long_System_Action_long__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((long)0, default(long), default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_22_For_5_long_long_System_Action_long__ParallelLoopState__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), (long)0, default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_23_For_5_long_long_System_Action_long__ParallelLoopState__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), (long arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_24_For_6_int_int_ParallelOptions_System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_25_For_6_int_int_ParallelOptions_System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((int)0, default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_26_For_6_int_int_ParallelOptions_System_Action_int__ParallelLoopState__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), (int)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_27_For_6_int_int_ParallelOptions_System_Action_int__ParallelLoopState__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_28_For_7_long_long_ParallelOptions_System_Action_long__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_29_For_7_long_long_ParallelOptions_System_Action_long__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For((long)0, default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_30_For_7_long_long_ParallelOptions_System_Action_long__ParallelLoopState__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), (long)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int64,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_31_For_7_long_long_ParallelOptions_System_Action_long__ParallelLoopState__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, (long arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_32_For_8_int_int_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), default(int), default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_33_For_8_int_int_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>((int)0, default(int), default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_34_For_8_int_int_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), (int)0, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_35_For_8_int_int_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), default(int), () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_36_For_9_long_long_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), default(long), default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_37_For_9_long_long_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>((long)0, default(long), default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_38_For_9_long_long_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), (long)0, default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_39_For_9_long_long_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), default(long), () => default(int)!, (long arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_40_For_10_int_int_ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_41_For_10_int_int_ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>((int)0, default(int), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_42_For_10_int_int_ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), (int)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_43_For_10_int_int_ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(int), default(int), default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_44_For_11_long_long_ParallelOptions_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_45_For_11_long_long_ParallelOptions_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>((long)0, default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_46_For_11_long_long_ParallelOptions_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__2()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), (long)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int64,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_47_For_11_long_long_ParallelOptions_System_Func_int__System_Func_long__ParallelLoopState__int__int__System_Action_int__3()
        {
            var result = global::System.Threading.Tasks.Parallel.For<int>(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (long arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_48_ForEach_12_IEnumerable_int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_49_ForEach_12_IEnumerable_int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_50_ForEach_13_IEnumerable_int__ParallelOptions_System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_51_ForEach_13_IEnumerable_int__ParallelOptions_System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_52_ForEach_14_IEnumerable_int__System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_53_ForEach_14_IEnumerable_int__System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_54_ForEach_15_IEnumerable_int__ParallelOptions_System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_55_ForEach_15_IEnumerable_int__ParallelOptions_System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_56_ForEach_16_IEnumerable_int__System_Action_int__ParallelLoopState__long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_57_ForEach_16_IEnumerable_int__System_Action_int__ParallelLoopState__long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), (int arg0, ParallelLoopState arg1, long arg2) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_58_ForEach_17_IEnumerable_int__ParallelOptions_System_Action_int__ParallelLoopState__long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_59_ForEach_17_IEnumerable_int__ParallelOptions_System_Action_int__ParallelLoopState__long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, (int arg0, ParallelLoopState arg1, long arg2) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_60_ForEach_18_IEnumerable_int__System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_61_ForEach_18_IEnumerable_int__System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(System.Linq.Enumerable.Empty<int>(), () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_62_ForEach_19_IEnumerable_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_63_ForEach_19_IEnumerable_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_64_ForEach_20_IEnumerable_int__System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_65_ForEach_20_IEnumerable_int__System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(System.Linq.Enumerable.Empty<int>(), () => default(int)!, (int arg0, ParallelLoopState arg1, long arg2, int arg3) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_66_ForEach_21_IEnumerable_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_67_ForEach_21_IEnumerable_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (int arg0, ParallelLoopState arg1, long arg2, int arg3) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_68_ForEach_22_Partitioner_int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_69_ForEach_22_Partitioner_int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_70_ForEach_23_Partitioner_int__System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_71_ForEach_23_Partitioner_int__System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_72_ForEach_24_OrderablePartitioner_int__System_Action_int__ParallelLoopState__long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_73_ForEach_24_OrderablePartitioner_int__System_Action_int__ParallelLoopState__long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, (int arg0, ParallelLoopState arg1, long arg2) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_74_ForEach_25_Partitioner_int__System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_75_ForEach_25_Partitioner_int__System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_76_ForEach_26_OrderablePartitioner_int__System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_77_ForEach_26_OrderablePartitioner_int__System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, () => default(int)!, (int arg0, ParallelLoopState arg1, long arg2, int arg3) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_78_ForEach_27_Partitioner_int__ParallelOptions_System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_79_ForEach_27_Partitioner_int__ParallelOptions_System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_80_ForEach_28_Partitioner_int__ParallelOptions_System_Action_int__ParallelLoopState__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_81_ForEach_28_Partitioner_int__ParallelOptions_System_Action_int__ParallelLoopState__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, (int arg0, ParallelLoopState arg1) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_82_ForEach_29_OrderablePartitioner_int__ParallelOptions_System_Action_int__ParallelLoopState__long__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Action<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_83_ForEach_29_OrderablePartitioner_int__ParallelOptions_System_Action_int__ParallelLoopState__long__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, (int arg0, ParallelLoopState arg1, long arg2) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_84_ForEach_30_Partitioner_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_85_ForEach_30_Partitioner_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.Partitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (int arg0, ParallelLoopState arg1, int arg2) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_86_ForEach_31_OrderablePartitioner_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__0()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32>)!, default(System.Func<System.Int32,System.Threading.Tasks.ParallelLoopState,System.Int64,System.Int32,System.Int32>)!, default(System.Action<System.Int32>)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_87_ForEach_31_OrderablePartitioner_int__ParallelOptions_System_Func_int__System_Func_int__ParallelLoopState__long__int__int__System_Action_int__1()
        {
            var result = global::System.Threading.Tasks.Parallel.ForEach<int, int>(default(System.Collections.Concurrent.OrderablePartitioner<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, () => default(int)!, (int arg0, ParallelLoopState arg1, long arg2, int arg3) => default(int)!, (int arg0) => { });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_88_ForAsync_32_long_long_System_Func_long__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_89_ForAsync_32_long_long_System_Func_long__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>((long)0, default(long), default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_90_ForAsync_32_long_long_System_Func_long__CancellationToken__ValueTask__2()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), (long)0, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_91_ForAsync_32_long_long_System_Func_long__CancellationToken__ValueTask__3()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), (long arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_92_ForAsync_33_long_long_CancellationToken_System_Func_long__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), default(System.Threading.CancellationToken)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_93_ForAsync_33_long_long_CancellationToken_System_Func_long__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>((long)0, default(long), default(System.Threading.CancellationToken)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_94_ForAsync_33_long_long_CancellationToken_System_Func_long__CancellationToken__ValueTask__2()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), (long)0, default(System.Threading.CancellationToken)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_95_ForAsync_33_long_long_CancellationToken_System_Func_long__CancellationToken__ValueTask__3()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), default(System.Threading.CancellationToken)!, (long arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_96_ForAsync_34_long_long_ParallelOptions_System_Func_long__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_97_ForAsync_34_long_long_ParallelOptions_System_Func_long__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>((long)0, default(long), default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_98_ForAsync_34_long_long_ParallelOptions_System_Func_long__CancellationToken__ValueTask__2()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), (long)0, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int64,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_99_ForAsync_34_long_long_ParallelOptions_System_Func_long__CancellationToken__ValueTask__3()
        {
            global::System.Threading.Tasks.Parallel.ForAsync<long>(default(long), default(long), default(System.Threading.Tasks.ParallelOptions)!, (long arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_100_ForEachAsync_35_IEnumerable_int__System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_101_ForEachAsync_35_IEnumerable_int__System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(System.Linq.Enumerable.Empty<int>(), (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_102_ForEachAsync_36_IEnumerable_int__CancellationToken_System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.CancellationToken)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_103_ForEachAsync_36_IEnumerable_int__CancellationToken_System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.CancellationToken)!, (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_104_ForEachAsync_37_IEnumerable_int__ParallelOptions_System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_105_ForEachAsync_37_IEnumerable_int__ParallelOptions_System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(System.Linq.Enumerable.Empty<int>(), default(System.Threading.Tasks.ParallelOptions)!, (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_106_ForEachAsync_38_IAsyncEnumerable_int__System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<System.Int32>)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_107_ForEachAsync_38_IAsyncEnumerable_int__System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<int>)!, (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_108_ForEachAsync_39_IAsyncEnumerable_int__CancellationToken_System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<System.Int32>)!, default(System.Threading.CancellationToken)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_109_ForEachAsync_39_IAsyncEnumerable_int__CancellationToken_System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<int>)!, default(System.Threading.CancellationToken)!, (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_110_ForEachAsync_40_IAsyncEnumerable_int__ParallelOptions_System_Func_int__CancellationToken__ValueTask__0()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<System.Int32>)!, default(System.Threading.Tasks.ParallelOptions)!, default(System.Func<System.Int32,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask>)!).GetAwaiter().GetResult();
            return 142L;
        }

        public long Subject_111_ForEachAsync_40_IAsyncEnumerable_int__ParallelOptions_System_Func_int__CancellationToken__ValueTask__1()
        {
            global::System.Threading.Tasks.Parallel.ForEachAsync<int>(default(System.Collections.Generic.IAsyncEnumerable<int>)!, default(System.Threading.Tasks.ParallelOptions)!, (int arg0, CancellationToken arg1) => default(ValueTask)!).GetAwaiter().GetResult();
            return 142L;
        }
    }
}
