#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "exception_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_ArgumentNullException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_ArgumentNullException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NullReferenceException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NullReferenceException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_ContainsKey_2_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_ContainsKey_2_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_CopyTo_0_KeyValuePairintint_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_CopyTo_0_KeyValuePairintint_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_CopyTo_0_KeyValuePairintint_int_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_CopyTo_0_KeyValuePairintint_int_3(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_GetValueRefOrNullRef_1_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_GetValueRefOrNullRef_1_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_TryGetValue_3_int_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_TryGetValue_3_int_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_Benchmark_TryGetValue_3_int_int_2(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_ContainsKey_2_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_ContainsKey_2_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_GetValueRefOrNullRef_1_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_GetValueRefOrNullRef_1_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_TryGetValue_3_int_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_TryGetValue_3_int_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests_TryGetValue_3_int_int_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass12_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass12_0_TryGetValue_3_int_int_0_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass14_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass14_0_TryGetValue_3_int_int_1_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass16_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__DisplayClass16_0_TryGetValue_3_int_int_2_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c_ContainsKey_2_int_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c_ContainsKey_2_int_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c_GetValueRefOrNullRef_1_int_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionarySystem_Int32System_Int32Tests___c_GetValueRefOrNullRef_1_int_1_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_0_IEnumerableKeyValuePairintint_IEqualityComparerint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_0_IEnumerableKeyValuePairintint_IEqualityComparerint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_Benchmark_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_0_IEnumerableKeyValuePairintint_IEqualityComparerint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_0_IEnumerableKeyValuePairintint_IEqualityComparerint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_Benchmark_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_1_b__7_0_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_Benchmark_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1_b__11_0_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_Benchmark_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1_b__11_1_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_0_IEnumerableKeyValuePairintint_IEqualityComparerint_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_1_IEnumerableint_System_Funcintint_IEqualityComparerint_1_b__6_0_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1_b__10_0_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenDictionaryTests___c_ToFrozenDictionary_2_IEnumerableint_System_Funcintint_System_Funcintint_IEqualityComparerint_1_b__10_1_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_Contains_0_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_Contains_0_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsProperSubsetOf_2_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsProperSubsetOf_2_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsProperSupersetOf_3_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsProperSupersetOf_3_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsSubsetOf_4_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsSubsetOf_4_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsSupersetOf_5_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_IsSupersetOf_5_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_Overlaps_6_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_Overlaps_6_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_SetEquals_7_IEnumerableint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_SetEquals_7_IEnumerableint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_TryGetValue_1_int_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_TryGetValue_1_int_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Benchmark_TryGetValue_1_int_int_2(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Contains_0_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Contains_0_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsProperSubsetOf_2_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsProperSubsetOf_2_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsProperSupersetOf_3_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsProperSupersetOf_3_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsSubsetOf_4_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsSubsetOf_4_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsSupersetOf_5_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_IsSupersetOf_5_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Overlaps_6_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_Overlaps_6_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_SetEquals_7_IEnumerableint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_SetEquals_7_IEnumerableint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_TryGetValue_1_int_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_TryGetValue_1_int_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests_TryGetValue_1_int_int_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass4_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass4_0_TryGetValue_1_int_int_0_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass6_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass6_0_TryGetValue_1_int_int_1_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass8_0__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__DisplayClass8_0_TryGetValue_1_int_int_2_b__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_Contains_0_int_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_Contains_0_int_1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsProperSubsetOf_2_IEnumerableint_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsProperSubsetOf_2_IEnumerableint_1_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsProperSupersetOf_3_IEnumerableint_0_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsProperSupersetOf_3_IEnumerableint_1_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsSubsetOf_4_IEnumerableint_0_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsSubsetOf_4_IEnumerableint_1_b__20_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsSupersetOf_5_IEnumerableint_0_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_IsSupersetOf_5_IEnumerableint_1_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_Overlaps_6_IEnumerableint_0_b__26_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_Overlaps_6_IEnumerableint_1_b__28_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_SetEquals_7_IEnumerableint_0_b__30_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetSystem_Int32Tests___c_SetEquals_7_IEnumerableint_1_b__32_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests_Benchmark_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests_Benchmark_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);





// Managed method: CombinedSubjects/AutoGenerated.System_Collections_Immutable.System_Collections_Frozen_FrozenSetTests::ToFrozenSet_0_IEnumerableint_IEqualityComparerint_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 2) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INT64 _i0;
	{
		if (42 < 0 || 42 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL(); // external runtime table index 42 out of range
		}
		if (kChaosExternalRuntimeFnTable[42] == nullptr) {
			CHAOS_IL2CPP_FAIL(); // external runtime table entry 42 is null
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(void)>(kChaosExternalRuntimeFnTable[42])();
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		if (40 < 0 || 40 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL(); // external runtime table index 40 out of range
		}
		if (kChaosExternalRuntimeFnTable[40] == nullptr) {
			CHAOS_IL2CPP_FAIL(); // external runtime table entry 40 is null
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(void)>(kChaosExternalRuntimeFnTable[40])();
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		if (81 < 0 || 81 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL(); // external runtime table index 81 out of range
		}
		if (kChaosExternalRuntimeFnTable[81] == nullptr) {
			CHAOS_IL2CPP_FAIL(); // external runtime table entry 81 is null
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	chaos_locals[0] = _s0;
	_s0 = 0;
	_s1 = chaos_locals[0];
	_s2 = 0;
	{
		[&]() -> void { if ((_s0) != (_s1)) { throw chaos_managed_exception{}; } }();
	}
	_s0 = chaos_locals[0];
	{
		if (_s0 != 0)
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(1);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		}
		else
		{
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
			_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(ChaosLoadInt64(_s0)));
		}
		chaos_locals[1] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[1]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Collections_Immutable.System_Collections_Frozen_FrozenSetTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Collections_Immutable.System_Collections_Frozen_FrozenSetTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Collections_Immutable.System_Collections_Frozen_FrozenSetTests+<>c::<ToFrozenSet_0_IEnumerableint_IEqualityComparerint_0>b__0_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Collections_Immutable_System_Collections_Frozen_FrozenSetTests___c_ToFrozenSet_0_IEnumerableint_IEqualityComparerint_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_1 = _s1;
		const auto chaos_arg_0 = _s0;
		if (81 < 0 || 81 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL(); // external runtime table index 81 out of range
		}
		if (kChaosExternalRuntimeFnTable[81] == nullptr) {
			CHAOS_IL2CPP_FAIL(); // external runtime table entry 81 is null
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[81])(chaos_arg_0, chaos_arg_1);
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)

// extern "C" definition for link-time visibility from runtime-entry.cpp
extern "C" const int kAotMethodCount = 155;
// Codegen stub count — pipeline checks this
extern "C" const int kCodegenFailureCount = 1;

extern "C" void ChaosJitRegisterAll() {}