// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.Text.Json.Schema;

namespace AutoGenerated.System_Text_Json
{
    public unsafe partial class System_Text_Json_Schema_JsonSchemaExporterTests
    {

        [Fact]
        [HotUpdate]
        public long GetJsonSchemaAsNode_0_JsonSerializerOptions_System_Type_JsonSchemaExporterOptions_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(default(System.Text.Json.JsonSerializerOptions)!, default(System.Type)!, default(System.Text.Json.Schema.JsonSchemaExporterOptions)!));
            return 42L;
        }
    }
}
