// Auto-generated by chaos-il2cpp convert-to-cpp
// Generated Module Source — A1 Typed Dispatch Table wiring
//
// Wires the extern "C" codegen symbols into the typed kFunctions table,
// and implements ChaosGeneratedModuleActivate() for the A2 proxy wrappers.

#include "chaos_runtime_host.h"
#include "chaos_generated_module.h"
#include <gc/gc_layout.h>

// extern "C" symbols from native-aot.generated.cpp
extern "C" const CodeRegistrationV0 chaos_codegen_code_registration;
extern "C" const MetadataRegistrationV0 chaos_codegen_metadata_registration;
extern "C" const CodegenRegistrationOptionsV0 chaos_codegen_options;
extern "C" CHAOS_IL2CPP_INT32 kAotMethodCount;


// extern "C" function declarations for all AOT-compiled methods
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_3_System_SequencePosition_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_4_System_SequencePosition_System_SequencePosition_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CancelPendingRead_6__6(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CompleteAsync_8_System_Exception_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_Complete_7_System_Exception_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_10_PipeWriter_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAsync_1_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_TryRead_0_ReadResult_0(
        void
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CompleteAsync_8_System_Exception_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_10_PipeWriter_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAsync_1_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_TryRead_0_ReadResult_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_cctor(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1_b__19_0_System_Exception_System_Object(
            CHAOS_IL2CPP_INTPTR, 
            CHAOS_IL2CPP_INTPTR, 
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_cctor(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_Benchmark_Schedule_0_System_Actionobject_object_1_b__1_0_System_Object(
            CHAOS_IL2CPP_INTPTR, 
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CancelPendingFlush_2__2(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CompleteAsync_1_System_Exception_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Complete_0_System_Exception_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_FlushAsync_4_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0(
        void
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_CompleteAsync_1_System_Exception_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_FlushAsync_4_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_cctor(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_0_b__14_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_1_b__16_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1_b__5_0_System_Exception_System_Object(
            CHAOS_IL2CPP_INTPTR, 
            CHAOS_IL2CPP_INTPTR, 
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_CompleteAsync_1_System_Exception_0_b__1_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_FlushAsync_4_CancellationToken_0_b__6_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_0_b__10_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_1_b__12_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0_b__18_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1(
        void
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_cctor(
        void
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c__ctor(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0_b__0_0(
            CHAOS_IL2CPP_INTPTR
);
extern "C" void CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1_b__2_0(
            CHAOS_IL2CPP_INTPTR
);

// ═══════════════════════════════════════════════════════════════════════════
// Typed Dispatch Table — wires extern "C" native symbols into typed pointers
// ═══════════════════════════════════════════════════════════════════════════

static const Functions s_functions = {
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_3_System_SequencePosition_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_4_System_SequencePosition_System_SequencePosition_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CancelPendingRead_6__6,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CompleteAsync_8_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_Complete_7_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_10_PipeWriter_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAsync_1_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_TryRead_0_ReadResult_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CompleteAsync_8_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_10_PipeWriter_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAsync_1_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_TryRead_0_ReadResult_0,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_cctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1_b__19_0_System_Exception_System_Object,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_1,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_cctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_Benchmark_Schedule_0_System_Actionobject_object_1_b__1_0_System_Object,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CancelPendingFlush_2__2,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CompleteAsync_1_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Complete_0_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_FlushAsync_4_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_CompleteAsync_1_System_Exception_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_FlushAsync_4_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_cctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_0_b__14_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_1_b__16_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1_b__5_0_System_Exception_System_Object,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_CompleteAsync_1_System_Exception_0_b__1_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_FlushAsync_4_CancellationToken_0_b__6_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_0_b__10_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_1_b__12_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0_b__18_0,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1,
    },
    {
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_cctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c__ctor,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0_b__0_0,
        &CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1_b__2_0,
    },
    76,
};

const Functions kFunctions = s_functions;

// Flat function pointer array for indexed dispatch (benchmarking).
// Avoids fragile reinterpret_cast<void* const*>(&kFunctions) which depends on
// struct layout uniformity across sub-struct members.
extern "C" void* kFunctionsFlat[76];
void* kFunctionsFlat[76] = {
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_AsStream_5_bool_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_3_System_SequencePosition_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AdvanceTo_4_System_SequencePosition_System_SequencePosition_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_AsStream_5_bool_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CancelPendingRead_6__6),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CompleteAsync_8_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_Complete_7_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_10_PipeWriter_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_CopyToAsync_11_Stream_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAsync_1_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_ReadAtLeastAsync_2_int_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_Benchmark_TryRead_0_ReadResult_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CompleteAsync_8_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_10_PipeWriter_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_CopyToAsync_11_Stream_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAsync_1_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_ReadAtLeastAsync_2_int_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests_TryRead_0_ReadResult_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_cctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeReaderTests___c_Benchmark_OnWriterCompleted_9_System_ActionSystem_Exceptionobject_object_1_b__19_0_System_Exception_System_Object),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests_Benchmark_Schedule_0_System_Actionobject_object_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_cctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeSchedulerTests___c_Benchmark_Schedule_0_System_Actionobject_object_1_b__1_0_System_Object),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_AsStream_7_bool_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Advance_5_int_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_AsStream_7_bool_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CancelPendingFlush_2__2),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_CompleteAsync_1_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_Complete_0_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_FlushAsync_4_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_GetMemory_6_int_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_Benchmark_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_CompleteAsync_1_System_Exception_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_FlushAsync_4_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_GetMemory_6_int_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_cctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_0_b__14_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_AsStream_7_bool_1_b__16_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_Benchmark_OnReaderCompleted_3_System_ActionSystem_Exceptionobject_object_1_b__5_0_System_Exception_System_Object),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_CompleteAsync_1_System_Exception_0_b__1_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_FlushAsync_4_CancellationToken_0_b__6_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_0_b__10_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_GetMemory_6_int_1_b__12_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_PipeWriterTests___c_WriteAsync_8_System_ReadOnlyMemorybyte_CancellationToken_0_b__18_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_Benchmark_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_cctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c__ctor),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_0_b__0_0),
    reinterpret_cast<void*>(&CombinedSubjects_AutoGenerated_System_IO_Pipelines_System_IO_Pipelines_StreamPipeExtensionsTests___c_CopyToAsync_0_Stream_PipeWriter_CancellationToken_1_b__2_0),
};


bool ChaosGeneratedModuleActivate(ChaosRuntimeHost* host) {
    if (!host) return false;
    if (!host->IsInitialized()) return false;

    bool ok = host->RegisterModule(
        &chaos_codegen_code_registration,
        &chaos_codegen_metadata_registration,
        &chaos_codegen_options
    );
    if (ok) {
        ChaosRegisterGcLayouts();
    }
    return ok;
}