#!/usr/bin/env python3
"""Stage verification reports into the GitHub Pages artifact tree.

Why
---
`docs/verification/**` is the committed snapshot of the reports.  Deploying that
tree directly means Pages serves whatever was last committed — a nightly that
just regenerated a dashboard would still publish the old one.  This script
copies the *freshly generated* report trees over the committed ones, so the
published site reflects the run that produced it, while falling back to the
committed copy for anything the current run did not regenerate.

Usage
-----
    python .github/scripts/stage_pages_reports.py \
        --site-root docs/native-api/build/html \
        [--report-dir <path> ...] [--dry-run]

Each --report-dir is expected to contain a `verification/` subtree mirroring
docs/verification/.  Missing sources are skipped with a notice, never an error:
a report that a given profile doesn't produce must not fail the deploy.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# Committed snapshot: the fallback and the set of destinations that must exist.
COMMITTED_REPORTS = Path("docs/verification")
SITE_SUBDIR = Path("verification")

# Only these are published.  `artifact/` and `_dll/` hold intermediates that are
# large and not part of the reviewer-facing contract.
PUBLISH_SUFFIXES = {".html", ".css", ".json", ".md", ".svg", ".js"}


def _copy_tree(src: Path, dst: Path, dry_run: bool) -> int:
    """Copy publishable files from src into dst, returning the file count."""
    count = 0
    for f in src.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in PUBLISH_SUFFIXES:
            continue
        rel = f.relative_to(src)
        target = dst / rel
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, target)
        count += 1
    return count


def stage(site_root: Path, report_dirs: list[Path], dry_run: bool = False) -> int:
    target = site_root / SITE_SUBDIR

    if not COMMITTED_REPORTS.is_dir():
        print(f"ERROR: committed reports not found at {COMMITTED_REPORTS}",
              file=sys.stderr)
        return 2

    # 1. Always lay down the committed snapshot — it defines the published
    #    surface, so a report the run didn't touch still appears on the site.
    base = _copy_tree(COMMITTED_REPORTS, target, dry_run)
    print(f"committed snapshot -> {target} ({base} files)")

    # 2. Overlay fresh reports from this run.  Later dirs win, so callers list
    #    lowest-priority first.
    total_fresh = 0
    for d in report_dirs:
        src = d / SITE_SUBDIR if (d / SITE_SUBDIR).is_dir() else d
        if not src.is_dir():
            print(f"  [skip] {d} — no verification/ subtree")
            continue
        n = _copy_tree(src, target, dry_run)
        total_fresh += n
        print(f"  fresh <- {src} ({n} files)")

    print(f"staged {base} committed + {total_fresh} fresh file(s)"
          f"{' [dry-run]' if dry_run else ''}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--site-root", required=True,
                    help="Pages artifact root (e.g. docs/native-api/build/html)")
    ap.add_argument("--report-dir", action="append", default=[],
                    help="Directory containing a verification/ subtree "
                         "regenerated by this run (repeatable)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Report what would be copied without writing")
    args = ap.parse_args(argv)

    return stage(Path(args.site_root),
                 [Path(d) for d in args.report_dir],
                 dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
