#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "exception_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_JsonException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__JsonException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_ArgumentNullException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_ArgumentNullException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NotSupportedException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NotSupportedException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NullReferenceException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NullReferenceException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Security_SecurityException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_Security_SecurityException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Add_0_IdentityReference_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Clear_2__2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Contains_3_IdentityReference_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_GetEnumerator_4__4(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Remove_1_IdentityReference_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Translate_5_System_Type_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Translate_6_System_Type_bool_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Benchmark_Translate_6_System_Type_bool_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Contains_3_IdentityReference_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_GetEnumerator_4__4(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Remove_1_IdentityReference_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Translate_5_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Translate_6_System_Type_bool_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests_Translate_6_System_Type_bool_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_Contains_3_IdentityReference_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_GetEnumerator_4__4_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_Remove_1_IdentityReference_0_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_Translate_5_System_Type_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_Translate_6_System_Type_bool_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceCollectionTests___c_Translate_6_System_Type_bool_1_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests_Benchmark_IsValidTargetType_0_System_Type_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests_Benchmark_Translate_1_System_Type_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests_IsValidTargetType_0_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests_Translate_1_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests___c_IsValidTargetType_0_System_Type_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_IdentityReferenceTests___c_Translate_1_System_Type_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests_Benchmark_IsValidTargetType_0_System_Type_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests_Benchmark_Translate_1_System_Type_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests_IsValidTargetType_0_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests_Translate_1_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests___c_IsValidTargetType_0_System_Type_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_NTAccountTests___c_Translate_1_System_Type_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_CompareTo_3_SecurityIdentifier_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_GetBinaryForm_5_System_Byte_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_GetBinaryForm_5_System_Byte_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_GetBinaryForm_5_System_Byte_int_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_GetBinaryForm_5_System_Byte_int_3(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_IsAccountSid_1__1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_IsEqualDomainSid_6_SecurityIdentifier_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_IsValidTargetType_0_System_Type_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_IsWellKnown_4_WellKnownSidType_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Benchmark_Translate_2_System_Type_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_CompareTo_3_SecurityIdentifier_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_IsAccountSid_1__1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_IsEqualDomainSid_6_SecurityIdentifier_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_IsValidTargetType_0_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_IsWellKnown_4_WellKnownSidType_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests_Translate_2_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_CompareTo_3_SecurityIdentifier_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_IsAccountSid_1__1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_IsEqualDomainSid_6_SecurityIdentifier_0_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_IsValidTargetType_0_System_Type_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_IsWellKnown_4_WellKnownSidType_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_SecurityIdentifierTests___c_Translate_2_System_Type_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_Clone_9__9(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_Dispose_8__8(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_GetAnonymous_3__3(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_GetCurrent_0__0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_GetCurrent_1_bool_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_GetCurrent_1_bool_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_GetCurrent_2_TokenAccessLevels_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonated_4_SafeAccessTokenHandle_System_Action_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Benchmark_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_Clone_9__9(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_GetAnonymous_3__3(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_GetCurrent_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_GetCurrent_1_bool_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_GetCurrent_1_bool_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_GetCurrent_2_TokenAccessLevels_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_Benchmark_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_1_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_Benchmark_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_1_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_Benchmark_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_1_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_Clone_9__9_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_GetAnonymous_3__3_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_GetCurrent_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_GetCurrent_1_bool_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_GetCurrent_1_bool_1_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_GetCurrent_2_TokenAccessLevels_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_0_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_1_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonated_5_SafeAccessTokenHandle_System_Funcint_1_b__13_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_0_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_1_b__17_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_6_SafeAccessTokenHandle_System_FuncTask_1_b__17_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_0_b__19_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_1_b__21_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsIdentityTests___c_RunImpersonatedAsync_7_SafeAccessTokenHandle_System_FuncTaskint_1_b__21_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_0_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_1_WindowsBuiltInRole_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_2_int_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_2_int_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_Benchmark_IsInRole_3_SecurityIdentifier_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_1_WindowsBuiltInRole_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_2_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_2_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_3_SecurityIdentifier_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_0_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_0_string_1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_1_WindowsBuiltInRole_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_2_int_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_2_int_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_3_SecurityIdentifier_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);





// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests::IsInRole_1_WindowsBuiltInRole_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_1_WindowsBuiltInRole_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__4_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 167)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[167];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__4_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests::IsInRole_2_int_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_2_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__6_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 168)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[168];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__6_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests::IsInRole_2_int_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_2_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__8_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 169)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[169];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__8_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests::IsInRole_3_SecurityIdentifier_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests_IsInRole_3_SecurityIdentifier_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__10_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 170)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[170];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9__10_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		chaos_external_runtime_System_Private_CoreLib_System_Object___ctor_System_Void__(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_0_string_0>b__0_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_0_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[97])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_0_string_1>b__2_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_0_string_1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[97])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_1_WindowsBuiltInRole_0>b__4_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_1_WindowsBuiltInRole_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[98])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_2_int_0>b__6_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_2_int_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[99])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_2_int_1>b__8_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_2_int_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(0);
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[99])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Principal_Windows.System_Security_Principal_WindowsPrincipalTests+<>c::<IsInRole_3_SecurityIdentifier_0>b__10_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Principal_Windows_System_Security_Principal_WindowsPrincipalTests___c_IsInRole_3_SecurityIdentifier_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[100])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)

// extern "C" definition for link-time visibility from runtime-entry.cpp
extern "C" const int kAotMethodCount = 172;

extern "C" void ChaosJitRegisterAll() {}