// Auto-generated native-AOT entry point
// Family: family/System.Linq/numeric/aggregation
// Assembly: System.Linq
// Variant: subjects

using System;
using System.Collections.Generic;
using System.Linq;

public static partial class NumericAggregationSubjects
{
    // Inlined exit code — avoids SDK method call resolution in codegen
    public static int _exitCode;

    // [0] System.Linq/System.Linq.Enumerable::Average:System.Double(System.Collections.Generic.IEnumerable{System.Int32})
    // [1] System.Linq/System.Linq.Enumerable::Average:System.Double(System.Collections.Generic.IEnumerable{System.Int64})
    // [2] System.Linq/System.Linq.Enumerable::Average:System.Single(System.Collections.Generic.IEnumerable{System.Single})
    // [3] System.Linq/System.Linq.Enumerable::Average:System.Double(System.Collections.Generic.IEnumerable{System.Double})
    // [4] System.Linq/System.Linq.Enumerable::Average:System.Decimal(System.Collections.Generic.IEnumerable{System.Decimal})
    // [5] System.Linq/System.Linq.Enumerable::Average:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int32}})
    // [6] System.Linq/System.Linq.Enumerable::Average:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int64}})
    // [7] System.Linq/System.Linq.Enumerable::Average:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{System.Nullable{System.Single}})
    // [8] System.Linq/System.Linq.Enumerable::Average:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Double}})
    // [9] System.Linq/System.Linq.Enumerable::Average:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{System.Nullable{System.Decimal}})
    // [10] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int32})
    // [11] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int64})
    // [12] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Single(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Single})
    // [13] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Double})
    // [14] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Decimal(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Decimal})
    // [15] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int32}})
    // [16] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int64}})
    // [17] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Single}})
    // [18] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Double}})
    // [19] System.Linq/System.Linq.Enumerable::Average{TSource}:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Decimal}})
    // [20] System.Linq/System.Linq.Enumerable::Max:System.Int32(System.Collections.Generic.IEnumerable{System.Int32})
    // [21] System.Linq/System.Linq.Enumerable::Max:System.Int64(System.Collections.Generic.IEnumerable{System.Int64})
    // [22] System.Linq/System.Linq.Enumerable::Max:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int32}})
    // [23] System.Linq/System.Linq.Enumerable::Max:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int64}})
    // [24] System.Linq/System.Linq.Enumerable::Max:System.Double(System.Collections.Generic.IEnumerable{System.Double})
    // [25] System.Linq/System.Linq.Enumerable::Max:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Double}})
    // [26] System.Linq/System.Linq.Enumerable::Max:System.Single(System.Collections.Generic.IEnumerable{System.Single})
    // [27] System.Linq/System.Linq.Enumerable::Max:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{System.Nullable{System.Single}})
    // [28] System.Linq/System.Linq.Enumerable::Max:System.Decimal(System.Collections.Generic.IEnumerable{System.Decimal})
    // [29] System.Linq/System.Linq.Enumerable::Max:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{System.Nullable{System.Decimal}})
    // [30] System.Linq/System.Linq.Enumerable::Max{TSource}:TSource(System.Collections.Generic.IEnumerable{TSource})
    // [31] System.Linq/System.Linq.Enumerable::Max{TSource}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Collections.Generic.IComparer{TSource})
    // [32] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Int32(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int32})
    // [33] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int32}})
    // [34] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Int64(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int64})
    // [35] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int64}})
    // [36] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Single(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Single})
    // [37] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Single}})
    // [38] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Double})
    // [39] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Double}})
    // [40] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Decimal(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Decimal})
    // [41] System.Linq/System.Linq.Enumerable::Max{TSource}:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Decimal}})
    // [42] System.Linq/System.Linq.Enumerable::Max{TSource,TResult}:TResult(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TResult})
    // [43] System.Linq/System.Linq.Enumerable::MaxBy{TSource,TKey}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TKey})
    // [44] System.Linq/System.Linq.Enumerable::MaxBy{TSource,TKey}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TKey},System.Collections.Generic.IComparer{TKey})
    // [45] System.Linq/System.Linq.Enumerable::Min:System.Int32(System.Collections.Generic.IEnumerable{System.Int32})
    // [46] System.Linq/System.Linq.Enumerable::Min:System.Int64(System.Collections.Generic.IEnumerable{System.Int64})
    // [47] System.Linq/System.Linq.Enumerable::Min:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int32}})
    // [48] System.Linq/System.Linq.Enumerable::Min:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int64}})
    // [49] System.Linq/System.Linq.Enumerable::Min:System.Single(System.Collections.Generic.IEnumerable{System.Single})
    // [50] System.Linq/System.Linq.Enumerable::Min:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{System.Nullable{System.Single}})
    // [51] System.Linq/System.Linq.Enumerable::Min:System.Double(System.Collections.Generic.IEnumerable{System.Double})
    // [52] System.Linq/System.Linq.Enumerable::Min:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Double}})
    // [53] System.Linq/System.Linq.Enumerable::Min:System.Decimal(System.Collections.Generic.IEnumerable{System.Decimal})
    // [54] System.Linq/System.Linq.Enumerable::Min:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{System.Nullable{System.Decimal}})
    // [55] System.Linq/System.Linq.Enumerable::Min{TSource}:TSource(System.Collections.Generic.IEnumerable{TSource})
    // [56] System.Linq/System.Linq.Enumerable::Min{TSource}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Collections.Generic.IComparer{TSource})
    // [57] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Int32(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int32})
    // [58] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int32}})
    // [59] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Int64(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int64})
    // [60] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int64}})
    // [61] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Single(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Single})
    // [62] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Single}})
    // [63] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Double})
    // [64] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Double}})
    // [65] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Decimal(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Decimal})
    // [66] System.Linq/System.Linq.Enumerable::Min{TSource}:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Decimal}})
    // [67] System.Linq/System.Linq.Enumerable::Min{TSource,TResult}:TResult(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TResult})
    // [68] System.Linq/System.Linq.Enumerable::MinBy{TSource,TKey}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TKey})
    // [69] System.Linq/System.Linq.Enumerable::MinBy{TSource,TKey}:TSource(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,TKey},System.Collections.Generic.IComparer{TKey})
    // [70] System.Linq/System.Linq.Enumerable::Sum:System.Int32(System.Collections.Generic.IEnumerable{System.Int32})
    // [71] System.Linq/System.Linq.Enumerable::Sum:System.Int64(System.Collections.Generic.IEnumerable{System.Int64})
    // [72] System.Linq/System.Linq.Enumerable::Sum:System.Single(System.Collections.Generic.IEnumerable{System.Single})
    // [73] System.Linq/System.Linq.Enumerable::Sum:System.Double(System.Collections.Generic.IEnumerable{System.Double})
    // [74] System.Linq/System.Linq.Enumerable::Sum:System.Decimal(System.Collections.Generic.IEnumerable{System.Decimal})
    // [75] System.Linq/System.Linq.Enumerable::Sum:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int32}})
    // [76] System.Linq/System.Linq.Enumerable::Sum:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{System.Nullable{System.Int64}})
    // [77] System.Linq/System.Linq.Enumerable::Sum:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{System.Nullable{System.Single}})
    // [78] System.Linq/System.Linq.Enumerable::Sum:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{System.Nullable{System.Double}})
    // [79] System.Linq/System.Linq.Enumerable::Sum:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{System.Nullable{System.Decimal}})
    // [80] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Int32(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int32})
    // [81] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Int64(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Int64})
    // [82] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Single(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Single})
    // [83] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Double(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Double})
    // [84] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Decimal(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Decimal})
    // [85] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Nullable{System.Int32}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int32}})
    // [86] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Nullable{System.Int64}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Int64}})
    // [87] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Nullable{System.Single}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Single}})
    // [88] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Nullable{System.Double}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Double}})
    // [89] System.Linq/System.Linq.Enumerable::Sum{TSource}:System.Nullable{System.Decimal}(System.Collections.Generic.IEnumerable{TSource},System.Func{TSource,System.Nullable{System.Decimal}})
}