// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Xml.Xsl;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.Xml.Schema;

namespace AutoGenerated.System_Private_Xml
{
    public unsafe partial class System_Xml_Schema_XmlSchemaSetTests
    {

        [Fact]
        [HotUpdate]
        public long Add_0_string_string_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add(default(string)!, default(string)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_0_string_string_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add("", default(string)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_0_string_string_2()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add(default(string)!, "") (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_1_string_XmlReader_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add(default(string)!, default(System.Xml.XmlReader)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_1_string_XmlReader_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add("", default(System.Xml.XmlReader)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_2_XmlSchemaSet_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add(default(System.Xml.Schema.XmlSchemaSet)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Add_3_XmlSchema_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Add(default(System.Xml.Schema.XmlSchema)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Remove_4_XmlSchema_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Remove(default(System.Xml.Schema.XmlSchema)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long RemoveRecursive_5_XmlSchema_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.RemoveRecursive(default(System.Xml.Schema.XmlSchema)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Contains_6_string_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Contains(default(string)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Contains_6_string_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Contains("") (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Contains_7_XmlSchema_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Contains(default(System.Xml.Schema.XmlSchema)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Compile_8__8()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Compile() (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Reprocess_9_XmlSchema_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Reprocess(default(System.Xml.Schema.XmlSchema)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Schemas_10__10()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Schemas() (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Schemas_11_string_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Schemas(default(string)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long Schemas_11_string_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.Xml.Schema.XmlSchemaSet)!.Schemas("") (external assembly stub — skipping Throws)
            return 42L;
        }
    }
}
