// Auto-generated by chaos-il2cpp convert-to-cpp
// Generated Module Header — A1 Typed Dispatch Table + A2 Proxy Wrappers
//
// Provides:
//   1. `kFunctions` — typed function pointer table grouped by declaring C# type
//   2. Proxy wrapper classes — static inline methods calling through kFunctions
//
// Usage:
//   #include "chaos_generated_module.h"
//   #include "chaos_runtime_host.h"
//
//   ChaosRuntimeHost host;
//   host.Initialize();
//   ChaosGeneratedModuleActivate(&host);  // register codegen + fill kFunctions
//
//   // Call via proxy wrapper (A2):
//   int result = SnapshotProverSubjects::ValueTypeHelper::RunValueType();
//
//   // Or call via raw function table (A1):
//   int r2 = kFunctions.ValueTypeHelper.RunValueType();
#pragma once

#include <cstdint>
#include "codegen_bridge.h"

// Forward declaration of ChaosRuntimeHost (defined in chaos_runtime_host.h).
class ChaosRuntimeHost;


// ═══════════════════════════════════════════════════════════════════════════
// A1: Typed Dispatch Table
// ═══════════════════════════════════════════════════════════════════════════

// NOTE: Uses raw function pointers matching the extern "C" symbols emitted by
// codegen.  Each group's section is a constexpr aggregate so the compiler can
// inline through the table when the address is known at compile time (LTO).
struct Functions {
    struct PrimitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry_t {
        CHAOS_IL2CPP_INT32 (*TestByteToInt)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestDoubleToFloat)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestDoubleToInt)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestFloatToDouble)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestIntToByte)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestIntToDouble)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestIntToLong)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestIntToShort)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestLongToInt)(
                void
        );
        CHAOS_IL2CPP_INT32 (*TestUintToLong)(
                void
        );
    } primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry;
    struct PrimitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects_t {
        void (*Subject_0)(
                void
        );
        void (*Subject_1)(
                void
        );
        void (*Subject_2)(
                void
        );
        void (*Subject_3)(
                void
        );
        void (*Subject_4)(
                void
        );
        void (*Subject_5)(
                void
        );
        void (*Subject_6)(
                void
        );
        void (*Subject_7)(
                void
        );
        void (*Subject_8)(
                void
        );
        void (*Subject_9)(
                void
        );
    } primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects;
    int32_t method_count;
};

extern const Functions kFunctions;

// Flat function pointer array for indexed dispatch (benchmarking).
// Index by slot index to call any AOT method without struct-layout dependencies.
extern "C" void* kFunctionsFlat[];

// ═══════════════════════════════════════════════════════════════════════════
// A2: Proxy Wrappers
// ═══════════════════════════════════════════════════════════════════════════
//
// Static inline methods that call through the kFunctions typed dispatch table.
// These provide type-safe invocation without exposing the raw function table.
// Compiler inlines through the table when LTO is enabled.
// ═══════════════════════════════════════════════════════════════════════════

struct PrimitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry {
    static inline CHAOS_IL2CPP_INT32 TestByteToInt(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestByteToInt(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestDoubleToFloat(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestDoubleToFloat(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestDoubleToInt(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestDoubleToInt(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestFloatToDouble(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestFloatToDouble(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestIntToByte(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestIntToByte(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestIntToDouble(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestIntToDouble(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestIntToLong(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestIntToLong(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestIntToShort(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestIntToShort(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestLongToInt(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestLongToInt(
        );
    }
    static inline CHAOS_IL2CPP_INT32 TestUintToLong(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreNativeEntry.TestUintToLong(
        );
    }
    /// Total number of AOT-compiled methods in this type.
    static constexpr int32_t MethodCount = 10;
};

struct PrimitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects {
    static inline void Subject_0(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_0(
        );
    }
    static inline void Subject_1(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_1(
        );
    }
    static inline void Subject_2(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_2(
        );
    }
    static inline void Subject_3(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_3(
        );
    }
    static inline void Subject_4(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_4(
        );
    }
    static inline void Subject_5(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_5(
        );
    }
    static inline void Subject_6(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_6(
        );
    }
    static inline void Subject_7(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_7(
        );
    }
    static inline void Subject_8(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_8(
        );
    }
    static inline void Subject_9(
    ) {
        return kFunctions.primitiveNumericConversionsCoreSubjects_PrimitiveNumericConversionsCoreSubjects.Subject_9(
        );
    }
    /// Total number of AOT-compiled methods in this type.
    static constexpr int32_t MethodCount = 10;
};



/// Activate this generated module by registering its codegen data with the
/// runtime host.  Must be called once after ChaosRuntimeHost::Initialize().
/// @param host  Pointer to an initialized ChaosRuntimeHost instance.
/// @return true on success.
bool ChaosGeneratedModuleActivate(ChaosRuntimeHost* host);