#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "exception_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NullReferenceException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NullReferenceException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_AddClaim_1_Claim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_AddClaims_2_IEnumerableClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_AddClaims_2_IEnumerableClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_Clone_0__0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindAll_5_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindAll_5_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindAll_6_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindAll_6_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindFirst_7_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindFirst_7_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindFirst_8_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_FindFirst_8_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_HasClaim_10_string_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_HasClaim_10_string_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_HasClaim_10_string_string_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_HasClaim_9_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_HasClaim_9_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_RemoveClaim_4_Claim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_TryRemoveClaim_3_Claim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Benchmark_WriteTo_11_BinaryWriter_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_Clone_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindAll_5_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindAll_5_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindAll_6_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindAll_6_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindFirst_7_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindFirst_7_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindFirst_8_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_FindFirst_8_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_HasClaim_10_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_HasClaim_10_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_HasClaim_10_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_HasClaim_9_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_HasClaim_9_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests_TryRemoveClaim_3_Claim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_Benchmark_FindAll_5_System_PredicateClaim_1_b__11_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_Benchmark_FindFirst_7_System_PredicateClaim_1_b__19_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_Benchmark_HasClaim_9_System_PredicateClaim_1_b__27_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindAll_5_System_PredicateClaim_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindAll_5_System_PredicateClaim_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindAll_5_System_PredicateClaim_1_b__10_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindAll_6_string_0_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindAll_6_string_1_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindFirst_7_System_PredicateClaim_0_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindFirst_7_System_PredicateClaim_1_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindFirst_7_System_PredicateClaim_1_b__18_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindFirst_8_string_0_b__20_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_FindFirst_8_string_1_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_10_string_string_0_b__28_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_10_string_string_1_b__30_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_10_string_string_2_b__32_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_9_System_PredicateClaim_0_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_9_System_PredicateClaim_1_b__26_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_HasClaim_9_System_PredicateClaim_1_b__26_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsIdentityTests___c_TryRemoveClaim_3_Claim_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_AddIdentities_1_IEnumerableClaimsIdentity_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_AddIdentities_1_IEnumerableClaimsIdentity_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_AddIdentity_0_ClaimsIdentity_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_Clone_2__2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindAll_3_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindAll_3_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindAll_4_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindAll_4_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindFirst_5_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindFirst_5_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindFirst_6_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_FindFirst_6_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_HasClaim_7_System_PredicateClaim_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_HasClaim_7_System_PredicateClaim_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_HasClaim_8_string_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_HasClaim_8_string_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_HasClaim_8_string_string_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_IsInRole_9_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_IsInRole_9_string_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Benchmark_WriteTo_10_BinaryWriter_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_Clone_2__2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindAll_3_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindAll_3_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindAll_4_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindAll_4_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindFirst_5_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindFirst_5_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindFirst_6_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_FindFirst_6_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_HasClaim_7_System_PredicateClaim_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_HasClaim_7_System_PredicateClaim_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_HasClaim_8_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_HasClaim_8_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_HasClaim_8_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_IsInRole_9_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests_IsInRole_9_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_Benchmark_FindAll_3_System_PredicateClaim_1_b__8_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_Benchmark_FindFirst_5_System_PredicateClaim_1_b__16_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_Benchmark_HasClaim_7_System_PredicateClaim_1_b__24_0_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_Clone_2__2_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindAll_3_System_PredicateClaim_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindAll_3_System_PredicateClaim_1_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindAll_3_System_PredicateClaim_1_b__7_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindAll_4_string_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindAll_4_string_1_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindFirst_5_System_PredicateClaim_0_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindFirst_5_System_PredicateClaim_1_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindFirst_5_System_PredicateClaim_1_b__15_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindFirst_6_string_0_b__17_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_FindFirst_6_string_1_b__19_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_7_System_PredicateClaim_0_b__21_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_7_System_PredicateClaim_1_b__23_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_7_System_PredicateClaim_1_b__23_1_Claim(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_8_string_string_0_b__25_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_8_string_string_1_b__27_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_HasClaim_8_string_string_2_b__29_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_IsInRole_9_string_0_b__31_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimsPrincipalTests___c_IsInRole_9_string_1_b__33_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Benchmark_Clone_0__0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Benchmark_Clone_1_ClaimsIdentity_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Benchmark_WriteTo_2_BinaryWriter_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Clone_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Clone_1_ClaimsIdentity_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_Clone_1_ClaimsIdentity_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests_Benchmark_Clone_0__0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests_Clone_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_Benchmark_IsInRole_0_string_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_Benchmark_IsInRole_0_string_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_IsInRole_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_IsInRole_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_IsInRole_0_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_IsInRole_0_string_1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);





// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Claims_ClaimTests::Clone_1_ClaimsIdentity_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests_Clone_1_ClaimsIdentity_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c____9__2_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 162)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[162];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) CHAOS_IL2CPP_UINT8 _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c____9__2_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Claims_ClaimTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Claims_ClaimTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Claims_ClaimTests+<>c::<Clone_0__0>b__0_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		if (96 < 0 || 96 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 96 out of range");
		}
		if (kChaosExternalRuntimeFnTable[96] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 96 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(void)>(kChaosExternalRuntimeFnTable[96])();
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Claims_ClaimTests+<>c::<Clone_1_ClaimsIdentity_0>b__2_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Claims_ClaimTests___c_Clone_1_ClaimsIdentity_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (97 < 0 || 97 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 97 out of range");
		}
		if (kChaosExternalRuntimeFnTable[97] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 97 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[97])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests::Benchmark_Clone_0__0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests_Benchmark_Clone_0__0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		if (27 < 0 || 27 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 27 out of range");
		}
		if (kChaosExternalRuntimeFnTable[27] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 27 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(void)>(kChaosExternalRuntimeFnTable[27])();
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests::Clone_0__0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests_Clone_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c____9__0_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 168)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[168];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) CHAOS_IL2CPP_UINT8 _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c____9__0_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericIdentityTests+<>c::<Clone_0__0>b__0_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericIdentityTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		if (27 < 0 || 27 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 27 out of range");
		}
		if (kChaosExternalRuntimeFnTable[27] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 27 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(void)>(kChaosExternalRuntimeFnTable[27])();
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests::Benchmark_IsInRole_0_string_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_Benchmark_IsInRole_0_string_0(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (75 < 0 || 75 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 75 out of range");
		}
		if (kChaosExternalRuntimeFnTable[75] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 75 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[75])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests::Benchmark_IsInRole_0_string_1()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_Benchmark_IsInRole_0_string_1(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s1;
		if (75 < 0 || 75 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 75 out of range");
		}
		if (kChaosExternalRuntimeFnTable[75] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 75 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[75])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests::IsInRole_0_string_0()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_IsInRole_0_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9__0_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 176)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[176];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) CHAOS_IL2CPP_UINT8 _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9__0_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests::IsInRole_0_string_1()
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests_IsInRole_0_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INT64 _i0;
	_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9__2_0;
	_s1 = _s0;
	{
		if (_s1 == 0)
		{
			_s0 = chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 177)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) -> void {
					auto& _d_entry = s_hotpatch_entries[177];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) CHAOS_IL2CPP_UINT8 _d_ab[8];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0);
				};
			_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s1;
				const auto chaos_target = _s0;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s1 = _s0;
			{
				auto chaos_value = _s1;
				chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9__2_0 = chaos_value;
			}
		}
		{
			// Assert.Throws: target method not found via IL lookahead
			// (verification skipped — use direct Assert.Throws in SDK for full coverage)
		}
		_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(42);
		_i0 = ChaosStoreInt64(static_cast<CHAOS_IL2CPP_INT64>(_s0));
		chaos_locals[0] = ChaosStoreInt64(_i0);
		_i0 = ChaosLoadInt64(chaos_locals[0]);
		return _i0;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests+<>c::.cctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_cctor(void)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};

	CHAOS_IL2CPP_INTPTR _s0;
	{
		auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c, {});
		chaos_object->header.type_info = chaos_mt_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c.AsTypeInfoHot();
		CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c__ctor(reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object));
		_s0 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
	}
	{
		auto chaos_value = _s0;
		chaos_static_CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c____9 = chaos_value;
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests+<>c::.ctor()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	_s0 = chaos_args[0];
	{
		const auto chaos_arg_0 = _s0;
		ChaosObjectCtor(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests+<>c::<IsInRole_0_string_0>b__0_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_IsInRole_0_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (75 < 0 || 75 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 75 out of range");
		}
		if (kChaosExternalRuntimeFnTable[75] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 75 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[75])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Security_Claims.System_Security_Principal_GenericPrincipalTests+<>c::<IsInRole_0_string_1>b__2_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Security_Claims_System_Security_Principal_GenericPrincipalTests___c_IsInRole_0_string_1_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s1;
		if (75 < 0 || 75 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 75 out of range");
		}
		if (kChaosExternalRuntimeFnTable[75] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 75 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[75])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)