#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "exception_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_ArgumentNullException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_ArgumentNullException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NullReferenceException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NullReferenceException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Xml_XmlException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_Xml_XmlException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_3_System_Uri_System_Byte_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_3_System_Uri_System_Byte_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_3_System_Uri_System_Byte_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_4_System_Uri_System_Byte_int_int_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_4_System_Uri_System_Byte_int_int_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_4_System_Uri_System_Byte_int_int_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_4_System_Uri_System_Byte_int_int_3(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_5_System_Uri_Stream_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_5_System_Uri_Stream_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_6_System_Uri_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Add_6_System_Uri_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_GetEntity_1_System_Uri_string_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_GetEntity_1_System_Uri_string_System_Type_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_GetEntityAsync_8_System_Uri_string_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_GetEntityAsync_8_System_Uri_string_System_Type_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_Remove_7_System_Uri_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_ResolveUri_0_System_Uri_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_ResolveUri_0_System_Uri_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests_SupportsType_2_System_Uri_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_3_System_Uri_System_Byte_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_3_System_Uri_System_Byte_1_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_3_System_Uri_System_Byte_2_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_4_System_Uri_System_Byte_int_int_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_4_System_Uri_System_Byte_int_int_1_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_4_System_Uri_System_Byte_int_int_2_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_4_System_Uri_System_Byte_int_int_3_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_5_System_Uri_Stream_0_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_5_System_Uri_Stream_1_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_6_System_Uri_string_0_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Add_6_System_Uri_string_1_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_GetEntity_1_System_Uri_string_System_Type_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_GetEntity_1_System_Uri_string_System_Type_1_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_GetEntityAsync_8_System_Uri_string_System_Type_0_b__17_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_GetEntityAsync_8_System_Uri_string_System_Type_1_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_Remove_7_System_Uri_0_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_ResolveUri_0_System_Uri_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_ResolveUri_0_System_Uri_string_1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Resolvers_XmlPreloadedResolverTests___c_SupportsType_2_System_Uri_System_Type_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests_Clone_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests_ValueAs_1_System_Type_IXmlNamespaceResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests___c_Clone_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlAtomicValueTests___c_ValueAs_1_System_Type_IXmlNamespaceResolver_0_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_0_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_0_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_0_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_1_string_XmlReader_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_1_string_XmlReader_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_2_string_XmlReader_XmlResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_2_string_XmlReader_XmlResolver_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_3_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_4_XmlSchema_XmlResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Add_5_XmlSchemaCollection_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Contains_6_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Contains_7_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_Contains_7_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests_GetEnumerator_8__8(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_0_string_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_0_string_string_1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_0_string_string_2_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_1_string_XmlReader_0_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_1_string_XmlReader_1_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_2_string_XmlReader_XmlResolver_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_2_string_XmlReader_XmlResolver_1_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_3_XmlSchema_0_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_4_XmlSchema_XmlResolver_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Add_5_XmlSchemaCollection_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Contains_6_XmlSchema_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Contains_7_string_0_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_Contains_7_string_1_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaCollectionTests___c_GetEnumerator_8__8_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests_ChangeType_1_object_System_Type_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests_ChangeType_2_object_System_Type_IXmlNamespaceResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests_IsDerivedFrom_3_XmlSchemaDatatype_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests_ParseValue_0_string_XmlNameTable_IXmlNamespaceResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests_ParseValue_0_string_XmlNameTable_IXmlNamespaceResolver_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_ChangeType_1_object_System_Type_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_ChangeType_2_object_System_Type_IXmlNamespaceResolver_0_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_IsDerivedFrom_3_XmlSchemaDatatype_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_ParseValue_0_string_XmlNameTable_IXmlNamespaceResolver_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaDatatypeTests___c_ParseValue_0_string_XmlNameTable_IXmlNamespaceResolver_1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests_InferSchema_0_XmlReader_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests_InferSchema_1_XmlReader_XmlSchemaSet_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests___c_InferSchema_0_XmlReader_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaInferenceTests___c_InferSchema_1_XmlReader_XmlSchemaSet_0_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_Add_1_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_Contains_4_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_GetEnumerator_0__0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_IndexOf_3_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_Insert_2_int_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_Insert_2_int_XmlSchemaObject_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests_Remove_5_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_Add_1_XmlSchemaObject_0_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_Contains_4_XmlSchemaObject_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_GetEnumerator_0__0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_IndexOf_3_XmlSchemaObject_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_Insert_2_int_XmlSchemaObject_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_Insert_2_int_XmlSchemaObject_1_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectCollectionTests___c_Remove_5_XmlSchemaObject_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests_Contains_0_XmlQualifiedName_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests_GetEnumerator_1__1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests___c_Contains_0_XmlQualifiedName_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaObjectTableTests___c_GetEnumerator_1__1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_0_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_0_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_0_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_1_string_XmlReader_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_1_string_XmlReader_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_2_XmlSchemaSet_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Add_3_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Compile_8__8(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Contains_6_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Contains_6_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Contains_7_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Remove_4_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_RemoveRecursive_5_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Reprocess_9_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Schemas_10__10(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Schemas_11_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests_Schemas_11_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_0_string_string_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_0_string_string_1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_0_string_string_2_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_1_string_XmlReader_0_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_1_string_XmlReader_1_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_2_XmlSchemaSet_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Add_3_XmlSchema_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Compile_8__8_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Contains_6_string_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Contains_6_string_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Contains_7_XmlSchema_0_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Remove_4_XmlSchema_0_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_RemoveRecursive_5_XmlSchema_0_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Reprocess_9_XmlSchema_0_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Schemas_10__10_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Schemas_11_string_0_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaSetTests___c_Schemas_11_string_1_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Compile_10_ValidationEventHandler_XmlResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Compile_9_ValidationEventHandler_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Read_0_TextReader_ValidationEventHandler_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Read_0_TextReader_ValidationEventHandler_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Read_1_Stream_ValidationEventHandler_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Read_1_Stream_ValidationEventHandler_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Read_2_XmlReader_ValidationEventHandler_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_3_Stream_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_3_Stream_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_4_Stream_XmlNamespaceManager_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_4_Stream_XmlNamespaceManager_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_5_TextWriter_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_5_TextWriter_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_6_TextWriter_XmlNamespaceManager_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_6_TextWriter_XmlNamespaceManager_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_7_XmlWriter_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests_Write_8_XmlWriter_XmlNamespaceManager_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Compile_10_ValidationEventHandler_XmlResolver_0_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Compile_9_ValidationEventHandler_0_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Read_0_TextReader_ValidationEventHandler_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Read_0_TextReader_ValidationEventHandler_1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Read_1_Stream_ValidationEventHandler_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Read_1_Stream_ValidationEventHandler_1_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Read_2_XmlReader_ValidationEventHandler_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_3_Stream_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_3_Stream_1_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_4_Stream_XmlNamespaceManager_0_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_4_Stream_XmlNamespaceManager_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_5_TextWriter_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_5_TextWriter_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_6_TextWriter_XmlNamespaceManager_0_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_6_TextWriter_XmlNamespaceManager_1_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_7_XmlWriter_0_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTests___c_Write_8_XmlWriter_XmlNamespaceManager_0_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_Benchmark_GetBuiltInComplexType_2_XmlTypeCode_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_Benchmark_GetBuiltInSimpleType_1_XmlTypeCode_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_Benchmark_IsDerivedFrom_4_XmlSchemaType_XmlSchemaType_XmlSchemaDerivationMethod_0(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_GetBuiltInComplexType_2_XmlTypeCode_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_GetBuiltInComplexType_3_XmlQualifiedName_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_GetBuiltInSimpleType_0_XmlQualifiedName_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_GetBuiltInSimpleType_1_XmlTypeCode_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests_IsDerivedFrom_4_XmlSchemaType_XmlSchemaType_XmlSchemaDerivationMethod_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests___c_GetBuiltInComplexType_3_XmlQualifiedName_0_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaTypeTests___c_GetBuiltInSimpleType_0_XmlQualifiedName_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_AddSchema_0_XmlSchema_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_EndValidation_16__16(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_GetExpectedAttributes_18__18(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_GetExpectedParticles_17__17(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_GetUnspecifiedDefaultAttributes_7_ArrayList_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_Initialize_1__1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_Initialize_2_XmlSchemaObject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_SkipToEndElement_15_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_5_string_string_string_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_5_string_string_string_XmlSchemaInfo_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_5_string_string_string_XmlSchemaInfo_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_5_string_string_string_XmlSchemaInfo_3(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_3_string_string_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_3_string_string_XmlSchemaInfo_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_3_string_string_XmlSchemaInfo_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateEndElement_13_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateEndElement_14_XmlSchemaInfo_object_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateEndOfAttributes_8_XmlSchemaInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateText_10_XmlValueGetter_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateText_9_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateText_9_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateWhitespace_11_string_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateWhitespace_11_string_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests_ValidateWhitespace_12_XmlValueGetter_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_AddSchema_0_XmlSchema_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_EndValidation_16__16_b__27_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_GetExpectedAttributes_18__18_b__29_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_GetExpectedParticles_17__17_b__28_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_GetUnspecifiedDefaultAttributes_7_ArrayList_0_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_Initialize_1__1_b__1_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_Initialize_2_XmlSchemaObject_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_SkipToEndElement_15_XmlSchemaInfo_0_b__26_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_2_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_3_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_0_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_1_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_2_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_0_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_1_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_2_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_1_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_2_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndElement_13_XmlSchemaInfo_0_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndElement_14_XmlSchemaInfo_object_0_b__25_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndOfAttributes_8_XmlSchemaInfo_0_b__17_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_10_XmlValueGetter_0_b__20_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_9_string_0_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_9_string_1_b__19_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_11_string_0_b__21_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_11_string_1_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_12_XmlValueGetter_0_b__23_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);





// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<Initialize_2_XmlSchemaObject_0>b__2_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_Initialize_2_XmlSchemaObject_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (230 < 0 || 230 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 230 out of range");
		}
		if (kChaosExternalRuntimeFnTable[230] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 230 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[230])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<SkipToEndElement_15_XmlSchemaInfo_0>b__26_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_SkipToEndElement_15_XmlSchemaInfo_0_b__26_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (231 < 0 || 231 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 231 out of range");
		}
		if (kChaosExternalRuntimeFnTable[231] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 231 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[231])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_5_string_string_string_XmlSchemaInfo_0>b__9_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_0_b__9_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (232 < 0 || 232 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 232 out of range");
		}
		if (kChaosExternalRuntimeFnTable[232] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 232 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[232])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_5_string_string_string_XmlSchemaInfo_1>b__10_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_1_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (232 < 0 || 232 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 232 out of range");
		}
		if (kChaosExternalRuntimeFnTable[232] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 232 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[232])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_5_string_string_string_XmlSchemaInfo_2>b__11_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_2_b__11_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	_s1 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (232 < 0 || 232 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 232 out of range");
		}
		if (kChaosExternalRuntimeFnTable[232] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 232 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[232])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_5_string_string_string_XmlSchemaInfo_3>b__12_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_5_string_string_string_XmlSchemaInfo_3_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s3 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (232 < 0 || 232 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 232 out of range");
		}
		if (kChaosExternalRuntimeFnTable[232] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 232 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[232])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_0>b__13_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_0_b__13_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (233 < 0 || 233 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 233 out of range");
		}
		if (kChaosExternalRuntimeFnTable[233] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 233 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[233])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_1>b__14_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_1_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (233 < 0 || 233 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 233 out of range");
		}
		if (kChaosExternalRuntimeFnTable[233] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 233 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[233])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_2>b__15_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateAttribute_6_string_string_XmlValueGetter_XmlSchemaInfo_2_b__15_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	_s0 = 0;
	_s1 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s3 = 0;
	_s4 = 0;
	{
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (233 < 0 || 233 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 233 out of range");
		}
		if (kChaosExternalRuntimeFnTable[233] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 233 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[233])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_3_string_string_XmlSchemaInfo_0>b__3_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_0_b__3_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	_s3 = 0;
	{
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (234 < 0 || 234 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 234 out of range");
		}
		if (kChaosExternalRuntimeFnTable[234] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 234 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[234])(chaos_arg_0, chaos_arg_1, chaos_arg_2);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_3_string_string_XmlSchemaInfo_1>b__4_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_1_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s2 = 0;
	_s3 = 0;
	{
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (234 < 0 || 234 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 234 out of range");
		}
		if (kChaosExternalRuntimeFnTable[234] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 234 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[234])(chaos_arg_0, chaos_arg_1, chaos_arg_2);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_3_string_string_XmlSchemaInfo_2>b__5_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_3_string_string_XmlSchemaInfo_2_b__5_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	_s0 = 0;
	_s1 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s3 = 0;
	{
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (234 < 0 || 234 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 234 out of range");
		}
		if (kChaosExternalRuntimeFnTable[234] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 234 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[234])(chaos_arg_0, chaos_arg_1, chaos_arg_2);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_0>b__6_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	CHAOS_IL2CPP_INTPTR _s5;
	CHAOS_IL2CPP_INTPTR _s6;
	CHAOS_IL2CPP_INTPTR _s7;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	_s5 = 0;
	_s6 = 0;
	_s7 = 0;
	{
		const auto chaos_arg_6 = _s7;
		const auto chaos_arg_5 = _s6;
		const auto chaos_arg_4 = _s5;
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (235 < 0 || 235 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 235 out of range");
		}
		if (kChaosExternalRuntimeFnTable[235] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 235 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[235])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3, chaos_arg_4, chaos_arg_5, chaos_arg_6);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_1>b__7_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_1_b__7_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	CHAOS_IL2CPP_INTPTR _s5;
	CHAOS_IL2CPP_INTPTR _s6;
	CHAOS_IL2CPP_INTPTR _s7;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s2 = 0;
	_s3 = 0;
	_s4 = 0;
	_s5 = 0;
	_s6 = 0;
	_s7 = 0;
	{
		const auto chaos_arg_6 = _s7;
		const auto chaos_arg_5 = _s6;
		const auto chaos_arg_4 = _s5;
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (235 < 0 || 235 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 235 out of range");
		}
		if (kChaosExternalRuntimeFnTable[235] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 235 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[235])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3, chaos_arg_4, chaos_arg_5, chaos_arg_6);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_2>b__8_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateElement_4_string_string_XmlSchemaInfo_string_string_string_string_2_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	CHAOS_IL2CPP_INTPTR _s3;
	CHAOS_IL2CPP_INTPTR _s4;
	CHAOS_IL2CPP_INTPTR _s5;
	CHAOS_IL2CPP_INTPTR _s6;
	CHAOS_IL2CPP_INTPTR _s7;
	_s0 = 0;
	_s1 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	_s3 = 0;
	_s4 = 0;
	_s5 = 0;
	_s6 = 0;
	_s7 = 0;
	{
		const auto chaos_arg_6 = _s7;
		const auto chaos_arg_5 = _s6;
		const auto chaos_arg_4 = _s5;
		const auto chaos_arg_3 = _s4;
		const auto chaos_arg_2 = _s3;
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (235 < 0 || 235 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 235 out of range");
		}
		if (kChaosExternalRuntimeFnTable[235] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 235 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[235])(chaos_arg_0, chaos_arg_1, chaos_arg_2, chaos_arg_3, chaos_arg_4, chaos_arg_5, chaos_arg_6);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateEndElement_13_XmlSchemaInfo_0>b__24_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndElement_13_XmlSchemaInfo_0_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (236 < 0 || 236 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 236 out of range");
		}
		if (kChaosExternalRuntimeFnTable[236] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 236 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[236])(chaos_arg_0);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateEndElement_14_XmlSchemaInfo_object_0>b__25_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndElement_14_XmlSchemaInfo_object_0_b__25_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	_s0 = 0;
	_s1 = 0;
	_s2 = 0;
	{
		const auto chaos_arg_1 = _s2;
		const auto chaos_arg_0 = _s1;
		if (237 < 0 || 237 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 237 out of range");
		}
		if (kChaosExternalRuntimeFnTable[237] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 237 is null");
		}
		const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[237])(chaos_arg_0, chaos_arg_1);
		_s1 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateEndOfAttributes_8_XmlSchemaInfo_0>b__17_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateEndOfAttributes_8_XmlSchemaInfo_0_b__17_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (238 < 0 || 238 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 238 out of range");
		}
		if (kChaosExternalRuntimeFnTable[238] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 238 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[238])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateText_10_XmlValueGetter_0>b__20_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_10_XmlValueGetter_0_b__20_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (239 < 0 || 239 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 239 out of range");
		}
		if (kChaosExternalRuntimeFnTable[239] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 239 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[239])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateText_9_string_0>b__18_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_9_string_0_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (240 < 0 || 240 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 240 out of range");
		}
		if (kChaosExternalRuntimeFnTable[240] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 240 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[240])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateText_9_string_1>b__19_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateText_9_string_1_b__19_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s1;
		if (240 < 0 || 240 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 240 out of range");
		}
		if (kChaosExternalRuntimeFnTable[240] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 240 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[240])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateWhitespace_11_string_0>b__21_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_11_string_0_b__21_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (241 < 0 || 241 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 241 out of range");
		}
		if (kChaosExternalRuntimeFnTable[241] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 241 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[241])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateWhitespace_11_string_1>b__22_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_11_string_1_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	{
		auto* chaos_string = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_String);
		chaos_string->header.type_info = chaos_mt_System_Private_CoreLib_System_String.AsTypeInfoHot();
		chaos_string->length = static_cast<CHAOS_IL2CPP_INTPTR>(0);
		chaos_string->utf8_data = "";
		_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_string);
	}
	{
		const auto chaos_arg_0 = _s1;
		if (241 < 0 || 241 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 241 out of range");
		}
		if (kChaosExternalRuntimeFnTable[241] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 241 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[241])(chaos_arg_0);
	}
	return;
}

// Managed method: CombinedSubjects/AutoGenerated.System_Private_Xml.System_Xml_Schema_XmlSchemaValidatorTests+<>c::<ValidateWhitespace_12_XmlValueGetter_0>b__23_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Private_Xml_System_Xml_Schema_XmlSchemaValidatorTests___c_ValidateWhitespace_12_XmlValueGetter_0_b__23_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	_s0 = 0;
	_s1 = 0;
	{
		const auto chaos_arg_0 = _s1;
		if (242 < 0 || 242 >= kChaosExternalRuntimeCount) {
			CHAOS_IL2CPP_FAIL("external runtime table index 242 out of range");
		}
		if (kChaosExternalRuntimeFnTable[242] == nullptr) {
			CHAOS_IL2CPP_FAIL("external runtime table entry 242 is null");
		}
		reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[242])(chaos_arg_0);
	}
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)

// extern "C" definition for link-time visibility from runtime-entry.cpp
extern "C" const int kAotMethodCount = 309;

extern "C" void ChaosJitRegisterAll() {}