// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.ComponentModel.Design;

namespace AutoGenerated.System_ComponentModel_TypeConverter
{
    public unsafe partial class System_ComponentModel_Design_DesignerOptionService_DesignerOptionCollectionTests
    {

        [Benchmark]
        public static void Benchmark_CopyTo_0_System_Array_int_0()
        {
            default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.CopyTo(default(System.Array)!, default(int));
        }

        [Benchmark]
        public static void Benchmark_CopyTo_0_System_Array_int_1()
        {
            default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.CopyTo(default(System.Array)!, (int)0);
        }

        [Fact]
        [HotUpdate]
        public long GetEnumerator_1__1()
        {
            var result_1_1 = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.GetEnumerator();
            return (object)(result_1_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetEnumerator_1__1()
        {
            _ = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.GetEnumerator();
        }

        [Fact]
        [HotUpdate]
        public long IndexOf_2_DesignerOptionService_DesignerOptionCollection_0()
        {
            var result_2_0 = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.IndexOf(default(DesignerOptionService.DesignerOptionCollection)!);
            return (long)(result_2_0);
        }

        [Benchmark]
        public static void Benchmark_IndexOf_2_DesignerOptionService_DesignerOptionCollection_0()
        {
            _ = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.IndexOf(default(DesignerOptionService.DesignerOptionCollection)!);
        }

        [Fact]
        [HotUpdate]
        public long ShowDialog_3__3()
        {
            var result_3_3 = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.ShowDialog();
            return result_3_3 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ShowDialog_3__3()
        {
            _ = default(global::System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection)!.ShowDialog();
        }
    }
}
