<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GuidRandomHashcodePatchEntry</AssemblyName>
    <RootNamespace>GuidRandomHashcodePatchEntry</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="GuidRandomHashcodePatchEntry.cs" />
  </ItemGroup>
</Project>
