#include <chaos/common.h>
#include <chaos/type_info.h>
#include "runtime_core.h"
#include <chaos/eh.h>
#include "codegen_bridge.h"
#include "module_registry.h"
#include "abi_manifest.h"
#include "hotpatch_table.h"
#include "runtime_vtable.h"
#include "runtime_instantiation.h"
#include "reflection_query_model.h"
#include "load_store_chaos_bridge.h"
#include "interpreter_entry.h"
#include <gc/gc_bgc_inline.h>
#include <gc/gc_card_table.h>
#include <ChaosGeneratedRuntimePrelude.h>
#include "enum_stubs.h"
#include "async_stubs.h"
#include "exception_stubs.h"
#include "enum_metadata.generated.h"
#include "native-aot.generated.header.h"

// Forward declaration for dispatch table entries (defined in runtime_stubs.cpp)
extern "C" void InterpreterEntryDirect(
    CHAOS_IL2CPP_UINTPTR method_key,
    void*     args_buf,
    void*     ret_buf) noexcept;

#pragma warning(push)
#pragma warning(disable: 4065 4244)

namespace chaos::il2cpp::codegen::CombinedSubjects {

// Bring runtime_core and jit declarations into scope for unqualified lookup
using namespace chaos::il2cpp::runtime_core;
using namespace chaos::il2cpp::jit;

extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Boolean_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_System_Byte_System_String(CHAOS_IL2CPP_UINT8 chaos_fn_arg_0, CHAOS_IL2CPP_UINT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Byte_array_System_Byte_array_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Char_System_Char_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Decimal_System_Decimal_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Double_System_Double_System_String(double chaos_fn_arg_0, double chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int16_System_Int16_System_String(CHAOS_IL2CPP_INT16 chaos_fn_arg_0, CHAOS_IL2CPP_INT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int32_System_Int32_System_String(CHAOS_IL2CPP_INT32 chaos_fn_arg_0, CHAOS_IL2CPP_INT32 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Int64_System_Int64_System_String(CHAOS_IL2CPP_INT64 chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Object_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_SByte_System_SByte_System_String(CHAOS_IL2CPP_INT8 chaos_fn_arg_0, CHAOS_IL2CPP_INT8 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_Single_System_Single_System_String(float chaos_fn_arg_0, float chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_String_System_String_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt16_System_UInt16_System_String(CHAOS_IL2CPP_UINT16 chaos_fn_arg_0, CHAOS_IL2CPP_UINT16 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt32_System_UInt32_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_System_UInt64_System_UInt64_System_String(CHAOS_IL2CPP_UINT64 chaos_fn_arg_0, CHAOS_IL2CPP_UINT64 chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_AreNotEqual_0_0_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Complete(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Fail_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT32 Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_get_ExitCode(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsFalse_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNotNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsNull_System_Object_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_IsTrue_System_Boolean_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_RecordFailure(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Reset(void);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_Action(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_ArgumentNullException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_ArgumentNullException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert_Throws_System_NotSupportedException_System_Action__generic(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void chaos_stub_definition_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__Throws_System_Void_System_Action__type____method__System_NotSupportedException(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_generic_context);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException__ctor_System_String(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_BenchmarkAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_FactAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void Chaos_TestFramework_Sdk_Chaos_TestFramework_HotUpdateAttribute__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateArrayInfo_0_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Int32_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateConcurrentQueueInfo_14_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentQueueint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateConcurrentStackInfo_13_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentStackint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateDictionaryInfo_2_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateICollectionInfo_10_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIDictionaryInfo_4_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIEnumerableInfo_15_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIEnumerableInfo_18_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIListInfo_7_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIListInfo_8_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateIReadOnlyDictionaryInfo_5_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateISetInfo_9_JsonSerializerOptions_JsonCollectionInfoValuesHashSetint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateListInfo_1_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateMemoryInfo_19_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Memoryint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateObjectInfo_25_JsonSerializerOptions_JsonObjectInfoValuesint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateQueueInfo_12_JsonSerializerOptions_JsonCollectionInfoValuesQueueint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateReadOnlyMemoryInfo_20_JsonSerializerOptions_JsonCollectionInfoValuesSystem_ReadOnlyMemoryint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateStackInfo_11_JsonSerializerOptions_JsonCollectionInfoValuesStackint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_CreateValueInfo_26_JsonSerializerOptions_JsonConverter_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_GetEnumConverter_22_JsonSerializerOptions_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_GetNullableConverter_23_JsonTypeInfoint_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_GetNullableConverter_24_JsonSerializerOptions_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_Benchmark_GetUnsupportedTypeConverter_21__21(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateArrayInfo_0_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Int32_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateConcurrentQueueInfo_14_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentQueueint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateConcurrentStackInfo_13_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentStackint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateDictionaryInfo_2_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateICollectionInfo_10_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIDictionaryInfo_4_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIEnumerableInfo_15_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIEnumerableInfo_18_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIListInfo_7_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIListInfo_8_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateIReadOnlyDictionaryInfo_5_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateISetInfo_9_JsonSerializerOptions_JsonCollectionInfoValuesHashSetint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateListInfo_1_JsonSerializerOptions_JsonCollectionInfoValuesListint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateMemoryInfo_19_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Memoryint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateObjectInfo_25_JsonSerializerOptions_JsonObjectInfoValuesint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateQueueInfo_12_JsonSerializerOptions_JsonCollectionInfoValuesQueueint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateReadOnlyMemoryInfo_20_JsonSerializerOptions_JsonCollectionInfoValuesSystem_ReadOnlyMemoryint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateStackInfo_11_JsonSerializerOptions_JsonCollectionInfoValuesStackint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_CreateValueInfo_26_JsonSerializerOptions_JsonConverter_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_GetEnumConverter_22_JsonSerializerOptions_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_GetNullableConverter_23_JsonTypeInfoint_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_GetNullableConverter_24_JsonSerializerOptions_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests_GetUnsupportedTypeConverter_21__21(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_Benchmark_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_1_b__9_0_System_Collections_Generic_IEnumerable_System_Collections_Generic_KeyValuePair_System_Int32_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_Benchmark_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_1_b__17_0_System_Collections_Generic_IEnumerable_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_Benchmark_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__43_0_System_Collections_ArrayList_System_Object(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_Benchmark_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__39_0_System_Collections_ArrayList_System_Object(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateArrayInfo_0_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Int32_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateConcurrentQueueInfo_14_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentQueueint_0_b__32_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateConcurrentStackInfo_13_JsonSerializerOptions_JsonCollectionInfoValuesConcurrentStackint_0_b__30_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateDictionaryInfo_2_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0_b__4_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateICollectionInfo_10_JsonSerializerOptions_JsonCollectionInfoValuesListint_0_b__24_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIDictionaryInfo_4_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0_b__10_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIEnumerableInfo_15_JsonSerializerOptions_JsonCollectionInfoValuesListint_0_b__34_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIEnumerableInfo_18_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0_b__44_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIListInfo_7_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_0_b__18_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIListInfo_8_JsonSerializerOptions_JsonCollectionInfoValuesListint_0_b__20_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableDictionaryInfo_3_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_System_FuncIEnumerableKeyValuePairintintDictionaryintint_1_b__8_1_System_Collections_Generic_IEnumerable_System_Collections_Generic_KeyValuePair_System_Int32_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_0_b__14_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_1_b__16_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INTPTR CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateImmutableEnumerableInfo_6_JsonSerializerOptions_JsonCollectionInfoValuesListint_System_FuncIEnumerableintListint_1_b__16_1_System_Collections_Generic_IEnumerable_System_Int32(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateIReadOnlyDictionaryInfo_5_JsonSerializerOptions_JsonCollectionInfoValuesDictionaryintint_0_b__12_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateISetInfo_9_JsonSerializerOptions_JsonCollectionInfoValuesHashSetint_0_b__22_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateListInfo_1_JsonSerializerOptions_JsonCollectionInfoValuesListint_0_b__2_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateMemoryInfo_19_JsonSerializerOptions_JsonCollectionInfoValuesSystem_Memoryint_0_b__46_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateObjectInfo_25_JsonSerializerOptions_JsonObjectInfoValuesint_0_b__58_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateQueueInfo_12_JsonSerializerOptions_JsonCollectionInfoValuesQueueint_0_b__28_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0_b__40_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__42_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateQueueInfo_17_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__42_1_System_Collections_ArrayList_System_Object(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateReadOnlyMemoryInfo_20_JsonSerializerOptions_JsonCollectionInfoValuesSystem_ReadOnlyMemoryint_0_b__48_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateStackInfo_11_JsonSerializerOptions_JsonCollectionInfoValuesStackint_0_b__26_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_0_b__36_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__38_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateStackInfo_16_JsonSerializerOptions_JsonCollectionInfoValuesArrayList_System_ActionArrayListobject_1_b__38_1_System_Collections_ArrayList_System_Object(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INTPTR chaos_fn_arg_2);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_CreateValueInfo_26_JsonSerializerOptions_JsonConverter_0_b__60_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_GetEnumConverter_22_JsonSerializerOptions_0_b__52_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_GetNullableConverter_23_JsonTypeInfoint_0_b__54_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_GetNullableConverter_24_JsonSerializerOptions_0_b__56_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonMetadataServicesTests___c_GetUnsupportedTypeConverter_21__21_b__50_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Benchmark_Combine_0_IJsonTypeInfoResolver_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Benchmark_Combine_0_IJsonTypeInfoResolver_1(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Benchmark_Combine_0_IJsonTypeInfoResolver_2(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Benchmark_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_0(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Benchmark_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1(void);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Combine_0_IJsonTypeInfoResolver_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Combine_0_IJsonTypeInfoResolver_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_Combine_0_IJsonTypeInfoResolver_2(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" CHAOS_IL2CPP_INT64 CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_cctor(void);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c__ctor(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_Benchmark_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1_b__9_0_System_Text_Json_Serialization_Metadata_JsonTypeInfo(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_Combine_0_IJsonTypeInfoResolver_0_b__0_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_0_b__6_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0);
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1_b__8_1_System_Text_Json_Serialization_Metadata_JsonTypeInfo(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1);





// Managed method: CombinedSubjects/AutoGenerated.System_Text_Json.System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests+<>c::<WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1>b__8_0()
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1_b__8_0(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	CHAOS_IL2CPP_INTPTR _s0;
	CHAOS_IL2CPP_INTPTR _s1;
	CHAOS_IL2CPP_INTPTR _s2;
	_s0 = 0;
	_s1 = chaos_static_CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c____9__8_1;
	_s2 = _s1;
	{
		if (_s2 == 0)
		{
			_s1 = chaos_static_CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c____9;
			{
				// Hotpatch-aware ldftn wrapper (slot 155)
				static auto* chaos_ftn_thunk = +[](CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1) -> void {
					auto& _d_entry = s_hotpatch_entries[155];
					if (::chaos::il2cpp::runtime_core::HotpatchIsActive(_d_entry)
						&& !::chaos::il2cpp::runtime_core::HotpatchShouldKeepNative(_d_entry))
					{
						alignas(16) uint8_t _d_ab[16];
						ArgBuffer _d_bw(_d_ab);
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_0));
						_d_bw.WritePtr(reinterpret_cast<void*>(chaos_fn_arg_1));
						::chaos::il2cpp::runtime_core::InterpreterEntryDirect(
							_d_entry.method_key, _d_ab, nullptr);
						return;
					}
					reinterpret_cast<void(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(_d_entry.direct_ptr)(chaos_fn_arg_0, chaos_fn_arg_1);
				};
			_s2 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_ftn_thunk);
			}
			{
				const auto chaos_method_ptr = _s2;
				const auto chaos_target = _s1;
				auto* chaos_object = CHAOS_IL2CPP_NEW_GC(chaos_type_System_Private_CoreLib_System_Action_System_Text_Json_Serialization_Metadata_JsonTypeInfo_, {});
				chaos_object->header.type_info = chaos_mt_System_Private_CoreLib_System_Action_System_Text_Json_Serialization_Metadata_JsonTypeInfo_.AsTypeInfoHot();
				chaos_object->chaos_delegate_target = chaos_target;
				chaos_object->chaos_delegate_method_ptr = chaos_method_ptr;
				_s1 = reinterpret_cast<CHAOS_IL2CPP_INTPTR>(chaos_object);
			}
			_s2 = _s1;
			{
				auto chaos_value = _s2;
				chaos_static_CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c____9__8_1 = chaos_value;
			}
		}
		{
			const auto chaos_arg_1 = _s1;
			const auto chaos_arg_0 = _s0;
			const auto chaos_result = reinterpret_cast<CHAOS_IL2CPP_INTPTR(*)(CHAOS_IL2CPP_INTPTR, CHAOS_IL2CPP_INTPTR)>(kChaosExternalRuntimeFnTable[98])(chaos_arg_0, chaos_arg_1);
			_s0 = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_result);
		}
		return;
	}
}

// Managed method: CombinedSubjects/AutoGenerated.System_Text_Json.System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests+<>c::<WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1>b__8_1(System.Text.Json.Serialization.Metadata.JsonTypeInfo)
extern "C" void CombinedSubjects_AutoGenerated_System_Text_Json_System_Text_Json_Serialization_Metadata_JsonTypeInfoResolverTests___c_WithAddedModifier_1_IJsonTypeInfoResolver_System_ActionJsonTypeInfo_1_b__8_1_System_Text_Json_Serialization_Metadata_JsonTypeInfo(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1)
{
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 2) chaos_args{};
	CHAOS_IL2CPP_ARRAY(CHAOS_IL2CPP_INTPTR, 1) chaos_locals{};
	chaos_args[0] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_0);
	chaos_args[1] = static_cast<CHAOS_IL2CPP_INTPTR>(chaos_fn_arg_1);
	return;
}



}  // namespace chaos::il2cpp::codegen::CombinedSubjects
#pragma warning(pop)

// extern "C" definition for link-time visibility from runtime-entry.cpp
extern "C" const int kAotMethodCount = 157;

extern "C" void ChaosJitRegisterAll() {}