<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ErrorInfoBasicPatchEntry</AssemblyName>
    <RootNamespace>ErrorInfoBasicPatchEntry</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ErrorInfoBasicPatchEntry.cs" />
  </ItemGroup>
</Project>
