<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Pipelines" HintPath="C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.IO.Pipelines.dll" />
  </ItemGroup>
</Project>
