<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PropertyChangeNotificationsSubjects</AssemblyName>
    <RootNamespace>PropertyChangeNotificationsSubjects</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SYSLIB0011;SYSLIB0050</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PropertyChangeNotificationsSubjects.cs" />
  </ItemGroup>
</Project>
