// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.ComponentModel;

namespace AutoGenerated.System_ComponentModel_TypeConverter
{
    public unsafe partial class System_ComponentModel_LicenseManagerTests
    {

        [Fact]
        [HotUpdate]
        public long CreateWithContext_0_System_Type_LicenseContext_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CreateWithContext_0_System_Type_LicenseContext_0()
        {
            _ = global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!);
        }

        [Fact]
        [HotUpdate]
        public long CreateWithContext_1_System_Type_LicenseContext_System_Object_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, default(System.Object[])!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CreateWithContext_1_System_Type_LicenseContext_System_Object_0()
        {
            _ = global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, default(System.Object[])!);
        }

        [Fact]
        [HotUpdate]
        public long CreateWithContext_1_System_Type_LicenseContext_System_Object_1()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, System.Array.Empty<object>()));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CreateWithContext_1_System_Type_LicenseContext_System_Object_1()
        {
            _ = global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, System.Array.Empty<object>());
        }

        [Fact]
        [HotUpdate]
        public long CreateWithContext_1_System_Type_LicenseContext_System_Object_2()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, new object[2] { default(object)!, default(object)! }));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CreateWithContext_1_System_Type_LicenseContext_System_Object_2()
        {
            _ = global::System.ComponentModel.LicenseManager.CreateWithContext(default(System.Type)!, default(System.ComponentModel.LicenseContext)!, new object[2] { default(object)!, default(object)! });
        }

        [Fact]
        [HotUpdate]
        public long IsLicensed_2_System_Type_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.IsLicensed(default(System.Type)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_IsLicensed_2_System_Type_0()
        {
            _ = global::System.ComponentModel.LicenseManager.IsLicensed(default(System.Type)!);
        }

        [Fact]
        [HotUpdate]
        public long IsValid_3_System_Type_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.IsValid(default(System.Type)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_IsValid_3_System_Type_0()
        {
            _ = global::System.ComponentModel.LicenseManager.IsValid(default(System.Type)!);
        }

        [Fact]
        [HotUpdate]
        public long IsValid_4_System_Type_object_License_0()
        {
            License __ref_4_0_0 = default;

            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.IsValid(default(System.Type)!, default(object)!, out __ref_4_0_0));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_IsValid_4_System_Type_object_License_0()
        {
            License __ref_4_0_0 = default;
            _ = global::System.ComponentModel.LicenseManager.IsValid(default(System.Type)!, default(object)!, out __ref_4_0_0);
        }

        [Fact]
        [HotUpdate]
        public long LockContext_5_object_0()
        {
            global::System.ComponentModel.LicenseManager.LockContext(default(object)!);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_LockContext_5_object_0()
        {
            global::System.ComponentModel.LicenseManager.LockContext(default(object)!);
        }

        [Fact]
        [HotUpdate]
        public long UnlockContext_6_object_0()
        {
            global::System.ComponentModel.LicenseManager.UnlockContext(default(object)!);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_UnlockContext_6_object_0()
        {
            global::System.ComponentModel.LicenseManager.UnlockContext(default(object)!);
        }

        [Fact]
        [HotUpdate]
        public long Validate_7_System_Type_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.Validate(default(System.Type)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Validate_7_System_Type_0()
        {
            global::System.ComponentModel.LicenseManager.Validate(default(System.Type)!);
        }

        [Fact]
        [HotUpdate]
        public long Validate_8_System_Type_object_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.ComponentModel.LicenseManager.Validate(default(System.Type)!, default(object)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Validate_8_System_Type_object_0()
        {
            _ = global::System.ComponentModel.LicenseManager.Validate(default(System.Type)!, default(object)!);
        }
    }
}
