// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.Data.SqlTypes;

namespace AutoGenerated.System_Data_Common
{
    public unsafe partial class System_Data_SqlTypes_SqlMoneyTests
    {

        [Fact]
        [HotUpdate]
        public long ToDecimal_0__0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToDecimal());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToDecimal_0__0()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToDecimal();
        }

        [Fact]
        [HotUpdate]
        public long ToInt64_1__1()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToInt64());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToInt64_1__1()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToInt64();
        }

        [Fact]
        [HotUpdate]
        public long ToInt32_2__2()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToInt32());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToInt32_2__2()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToInt32();
        }

        [Fact]
        [HotUpdate]
        public long ToDouble_3__3()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToDouble());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToDouble_3__3()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToDouble();
        }

        [Fact]
        [HotUpdate]
        public long GetTdsValue_4__4()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.GetTdsValue());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_GetTdsValue_4__4()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.GetTdsValue();
        }

        [Fact]
        [HotUpdate]
        public long Parse_5_string_0()
        {
            Assert.Throws<System.ArgumentNullException>(() => global::System.Data.SqlTypes.SqlMoney.Parse(default(string)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Parse_5_string_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Parse(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long Parse_5_string_1()
        {
            Assert.Throws<System.FormatException>(() => global::System.Data.SqlTypes.SqlMoney.Parse(""));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Parse_5_string_1()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Parse("");
        }

        [Fact]
        [HotUpdate]
        public long FromTdsValue_6_long_0()
        {
            var result_6_0 = global::System.Data.SqlTypes.SqlMoney.FromTdsValue(default(long));
            return (object)(result_6_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_FromTdsValue_6_long_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.FromTdsValue(default(long));
        }

        [Fact]
        [HotUpdate]
        public long FromTdsValue_6_long_1()
        {
            var result_6_1 = global::System.Data.SqlTypes.SqlMoney.FromTdsValue((long)0);
            return (object)(result_6_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_FromTdsValue_6_long_1()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.FromTdsValue((long)0);
        }

        [Fact]
        [HotUpdate]
        public long Add_7_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.Add(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Add_7_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Add(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long Subtract_8_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.Subtract(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Subtract_8_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Subtract(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long Multiply_9_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.Multiply(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Multiply_9_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Multiply(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long Divide_10_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.Divide(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Divide_10_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.Divide(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long NotEquals_11_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.NotEquals(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_NotEquals_11_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.NotEquals(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long LessThan_12_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.LessThan(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_LessThan_12_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.LessThan(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long GreaterThan_13_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.GreaterThan(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_GreaterThan_13_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.GreaterThan(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long LessThanOrEqual_14_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.LessThanOrEqual(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_LessThanOrEqual_14_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.LessThanOrEqual(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long GreaterThanOrEqual_15_SqlMoney_SqlMoney_0()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => global::System.Data.SqlTypes.SqlMoney.GreaterThanOrEqual(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_GreaterThanOrEqual_15_SqlMoney_SqlMoney_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.GreaterThanOrEqual(default(System.Data.SqlTypes.SqlMoney)!, default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long ToSqlBoolean_16__16()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlBoolean());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlBoolean_16__16()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlBoolean();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlByte_17__17()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlByte());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlByte_17__17()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlByte();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlDouble_18__18()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlDouble());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlDouble_18__18()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlDouble();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlInt16_19__19()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt16());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlInt16_19__19()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt16();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlInt32_20__20()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt32());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlInt32_20__20()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt32();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlInt64_21__21()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt64());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlInt64_21__21()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlInt64();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlDecimal_22__22()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlDecimal());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlDecimal_22__22()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlDecimal();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlSingle_23__23()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlSingle());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlSingle_23__23()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlSingle();
        }

        [Fact]
        [HotUpdate]
        public long ToSqlString_24__24()
        {
            Assert.Throws<System.Data.SqlTypes.SqlNullValueException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlString());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ToSqlString_24__24()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.ToSqlString();
        }

        [Fact]
        [HotUpdate]
        public long CompareTo_25_object_0()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.Data.SqlTypes.SqlMoney)!.CompareTo(default(object)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CompareTo_25_object_0()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.CompareTo(default(object)!);
        }

        [Fact]
        [HotUpdate]
        public long CompareTo_26_SqlMoney_0()
        {
            var result_26_0 = default(global::System.Data.SqlTypes.SqlMoney)!.CompareTo(default(System.Data.SqlTypes.SqlMoney)!);
            Assert.AreEqual(0, result_26_0);
            return (long)(result_26_0);
        }

        [Benchmark]
        public static void Benchmark_CompareTo_26_SqlMoney_0()
        {
            _ = default(global::System.Data.SqlTypes.SqlMoney)!.CompareTo(default(System.Data.SqlTypes.SqlMoney)!);
        }

        [Fact]
        [HotUpdate]
        public long GetXsdType_27_XmlSchemaSet_0()
        {
            var result_27_0 = global::System.Data.SqlTypes.SqlMoney.GetXsdType(default(System.Xml.Schema.XmlSchemaSet)!);
            return (object)(result_27_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetXsdType_27_XmlSchemaSet_0()
        {
            _ = global::System.Data.SqlTypes.SqlMoney.GetXsdType(default(System.Xml.Schema.XmlSchemaSet)!);
        }
    }
}
