<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chaos.IL2CPP.Contracts\Chaos.IL2CPP.Contracts.csproj" />
    <ProjectReference Include="..\Chaos.IL2CPP.Pipeline\Chaos.IL2CPP.Pipeline.csproj" />
  </ItemGroup>
</Project>
