if(NOT DEFINED CHAOS_SUBJECT_REFERENCE_PROOF_EXE OR CHAOS_SUBJECT_REFERENCE_PROOF_EXE STREQUAL "")
    message(FATAL_ERROR "CHAOS_SUBJECT_REFERENCE_PROOF_EXE is required")
endif()

if(NOT DEFINED CHAOS_SUBJECT_REFERENCE_RUN_OUTPUT_ROOT OR CHAOS_SUBJECT_REFERENCE_RUN_OUTPUT_ROOT STREQUAL "")
    message(FATAL_ERROR "CHAOS_SUBJECT_REFERENCE_RUN_OUTPUT_ROOT is required")
endif()

if(NOT DEFINED CHAOS_SUBJECT_REFERENCE_STDOUT_PATH OR CHAOS_SUBJECT_REFERENCE_STDOUT_PATH STREQUAL "")
    message(FATAL_ERROR "CHAOS_SUBJECT_REFERENCE_STDOUT_PATH is required")
endif()

if(NOT DEFINED CHAOS_SUBJECT_REFERENCE_STDERR_PATH OR CHAOS_SUBJECT_REFERENCE_STDERR_PATH STREQUAL "")
    message(FATAL_ERROR "CHAOS_SUBJECT_REFERENCE_STDERR_PATH is required")
endif()

if(NOT DEFINED CHAOS_SUBJECT_REFERENCE_EXIT_CODE_PATH OR CHAOS_SUBJECT_REFERENCE_EXIT_CODE_PATH STREQUAL "")
    message(FATAL_ERROR "CHAOS_SUBJECT_REFERENCE_EXIT_CODE_PATH is required")
endif()

file(MAKE_DIRECTORY "${CHAOS_SUBJECT_REFERENCE_RUN_OUTPUT_ROOT}")

execute_process(
    COMMAND "${CHAOS_SUBJECT_REFERENCE_PROOF_EXE}"
    WORKING_DIRECTORY "${CHAOS_SUBJECT_REFERENCE_RUN_OUTPUT_ROOT}"
    RESULT_VARIABLE proof_exit_code
    OUTPUT_FILE "${CHAOS_SUBJECT_REFERENCE_STDOUT_PATH}"
    ERROR_FILE "${CHAOS_SUBJECT_REFERENCE_STDERR_PATH}")

file(WRITE "${CHAOS_SUBJECT_REFERENCE_EXIT_CODE_PATH}" "${proof_exit_code}\n")

if(NOT proof_exit_code EQUAL 0)
    message(FATAL_ERROR
        "Subject native reference proof failed with exit code ${proof_exit_code}; "
        "see ${CHAOS_SUBJECT_REFERENCE_STDOUT_PATH}, ${CHAOS_SUBJECT_REFERENCE_STDERR_PATH}, and ${CHAOS_SUBJECT_REFERENCE_EXIT_CODE_PATH}.")
endif()
