// Auto-generated type declarations (TU paging)
#pragma once

#include <chaos/native_types.h>
#include <chaos/type_info.h>  // MethodTable, TypeInfoV0 (complete type)
#include "generated_code_compat.h"  // PureTypeHeader for delegate type definitions
#include "ChaosGeneratedRuntimePrelude.h"
#include "vector_stubs.h"  // Vector<T> comparison stubs  // chaos_managed_array for array-compat checks

typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_DateTime;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_DateTimeOffset;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_Guid;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_TimeSpan;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Xml_ReaderWriter_System_Xml_XmlNodeType;

struct chaos_type_System_Private_CoreLib_System_Object

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_Boolean : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_Byte

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_Char

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_DateTime : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_DateTimeOffset : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_Decimal

{

    PureTypeHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_Guid : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_IO_Stream

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_IO_Stream_NullStream

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_IO_TextReader

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_IO_TextWriter

{

    ThinLockableHeader header{};

};



struct chaos_type_System_Private_CoreLib_System_Int32 : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly

{

    ThinLockableHeader header{};

    CHAOS_IL2CPP_INTPTR runtime_assembly_name_value = 0;

};



struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName

{

    ThinLockableHeader header{};

    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;

};



struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase

{

    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;

    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;

    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;

    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;

};



struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo

{

    ThinLockableHeader header{};

    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;

    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;

};



struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase

{

    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;

    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;

    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;

    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;

};



struct chaos_type_System_Private_CoreLib_System_String

{

    ThinLockableHeader header{};

    CHAOS_IL2CPP_INTPTR length = 0;

    const char* utf8_data = nullptr;

    CHAOS_IL2CPP_UINT64 string_id = 0u;  // stable StringId, 0 = not yet materialized

};



struct chaos_type_System_Private_CoreLib_System_TimeSpan : public chaos_type_System_Private_CoreLib_System_Object

{

};



struct chaos_type_System_Private_CoreLib_System_Type : public chaos_type_System_Private_CoreLib_System_Object

{

    CHAOS_IL2CPP_INTPTR runtime_type_handle = 0;

    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;

    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;

};



struct chaos_type_System_Xml_ReaderWriter_System_Xml_XmlNodeType : public chaos_type_System_Private_CoreLib_System_Object

{

};




struct chaos_type_System_Private_CoreLib_System_Boolean;
struct chaos_boxed_type_System_Private_CoreLib_System_Boolean {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR value = 0;
};
struct chaos_type_System_Private_CoreLib_System_Byte;
struct chaos_boxed_type_System_Private_CoreLib_System_Byte;
struct chaos_type_System_Private_CoreLib_System_Char;
struct chaos_boxed_type_System_Private_CoreLib_System_Char;
struct chaos_type_System_Private_CoreLib_System_DateTime;
struct chaos_boxed_type_System_Private_CoreLib_System_DateTime {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_DateTime value{};
};
struct chaos_type_System_Private_CoreLib_System_DateTimeOffset;
struct chaos_boxed_type_System_Private_CoreLib_System_DateTimeOffset {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_DateTimeOffset value{};
};
struct chaos_type_System_Private_CoreLib_System_Decimal;
struct chaos_boxed_type_System_Private_CoreLib_System_Decimal;
struct chaos_type_System_Private_CoreLib_System_Guid;
struct chaos_boxed_type_System_Private_CoreLib_System_Guid {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_Guid value{};
};
struct chaos_type_System_Private_CoreLib_System_IO_Stream;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream;
struct chaos_type_System_Private_CoreLib_System_IO_Stream_NullStream;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream_NullStream;
struct chaos_type_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader;
struct chaos_type_System_Private_CoreLib_System_IO_TextReader;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_TextReader;
struct chaos_type_System_Private_CoreLib_System_IO_TextWriter;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_TextWriter;
struct chaos_type_System_Private_CoreLib_System_Int32;
struct chaos_boxed_type_System_Private_CoreLib_System_Int32 {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR value = 0;
};
struct chaos_type_System_Private_CoreLib_System_Object;
struct chaos_boxed_type_System_Private_CoreLib_System_Object;
struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_type_System_Private_CoreLib_System_String;
struct chaos_boxed_type_System_Private_CoreLib_System_String;
struct chaos_type_System_Private_CoreLib_System_TimeSpan;
struct chaos_boxed_type_System_Private_CoreLib_System_TimeSpan {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_TimeSpan value{};
};
struct chaos_type_System_Private_CoreLib_System_Type;
struct chaos_boxed_type_System_Private_CoreLib_System_Type;
struct chaos_type_System_Xml_ReaderWriter_System_Xml_XmlNodeType;
struct chaos_boxed_type_System_Xml_ReaderWriter_System_Xml_XmlNodeType {
    PureTypeHeader header{};
    chaos_valuetype_System_Xml_ReaderWriter_System_Xml_XmlNodeType value{};
};

struct HotpatchEntryV0;
extern "C" HotpatchEntryV0 s_hotpatch_entries[];

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern MethodTable chaos_mt_System_Private_CoreLib_System_Boolean;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Byte;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Char;
extern MethodTable chaos_mt_System_Private_CoreLib_System_DateTime;
extern MethodTable chaos_mt_System_Private_CoreLib_System_DateTimeOffset;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Decimal;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Guid;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream_NullStream;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_TextReader;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_TextWriter;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Int32;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Object;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_Assembly;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_AssemblyName;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_FieldInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodBase;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_String;
extern MethodTable chaos_mt_System_Private_CoreLib_System_TimeSpan;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Type;
extern MethodTable chaos_mt_System_Xml_ReaderWriter_System_Xml_XmlNodeType;


extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Decimal__Zero;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__Null;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_TextReader__Null;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_TextWriter__Null;

extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Boolean;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Byte;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Char;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_DateTime;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_DateTimeOffset;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Decimal;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Guid;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream_NullStream;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_TextReader;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_TextWriter;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Int32;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Object;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_Assembly;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_AssemblyName;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_FieldInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_MethodBase;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_MethodInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_String;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_TimeSpan;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Type;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Xml_ReaderWriter_System_Xml_XmlNodeType;

extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_String(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Char(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_TextReader(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_TextWriter(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Byte(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Decimal(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream_NullStream(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_StreamReader_NullStreamReader(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Type(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Object(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_MethodBase(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_MethodInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_ConstructorInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_FieldInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_Assembly(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_AssemblyName(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_DateTime(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_DateTimeOffset(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Guid(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_TimeSpan(void);
extern "C" void chaos_ensure_type_initialized_System_Xml_ReaderWriter_System_Xml_XmlNodeType(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Boolean(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Int32(void);

CHAOS_IL2CPP_INTPTR chaos_string_materialize(CHAOS_IL2CPP_INTPTR chaos_value) noexcept;
inline CHAOS_IL2CPP_INTPTR chaos_string_materialize(CHAOS_IL2CPP_INTPTR chaos_value) noexcept { return chaos_value; }

bool chaos_is_array_store_compatible(const chaos_managed_array* chaos_array, CHAOS_IL2CPP_INTPTR chaos_value) noexcept;

void chaos_default_interpolated_string_handler_reset(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_literal_length, CHAOS_IL2CPP_INT32 chaos_trailing_count);
void chaos_default_interpolated_string_handler_append_string(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INTPTR chaos_string_value);
void chaos_default_interpolated_string_handler_append_int32(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_value);
CHAOS_IL2CPP_INTPTR chaos_default_interpolated_string_handler_to_string_and_clear(CHAOS_IL2CPP_INTPTR chaos_handler_ref);

} // namespace chaos::il2cpp::codegen::CombinedSubjects

extern "C" void* kChaosExternalRuntimeFnTable[];

extern "C" CHAOS_IL2CPP_INT32 kChaosExternalRuntimeCount;

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_NullStreamReader___ctor() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_NullStream___ctor() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Array__Empty_System_Char__System_Char____() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Array__Empty_System_String__System_String____() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_BitConverter__DoubleToInt64Bits_System_Int64_System_Double_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_BitConverter__SingleToInt32Bits_System_Int32_System_Single_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Boolean() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Byte() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Char() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_DateTime() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_DateTimeOffset() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Decimal__Zero() noexcept;
extern CHAOS_IL2CPP_INT32 chaos_external_runtime_System_Private_CoreLib_System_Decimal__op_Explicit_System_Int64_System_Decimal_(CHAOS_IL2CPP_INTPTR chaos_arg_0) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Guid() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__Null() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_TextReader__Null() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_TextWriter__Null() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Int32() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_Object___ctor_System_Void__(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Boolean___GetResult_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Object___GetResult_System_Object__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_String___GetResult_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Xml_XmlNodeType___GetResult_System_Xml_XmlNodeType__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_String() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_Boolean___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Boolean___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_Object___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Object___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_String___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_Xml_XmlNodeType___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Xml_XmlNodeType___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_TimeSpan() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__Append_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__InsertAfter_System_Xml_XmlAttribute_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__InsertBefore_System_Xml_XmlAttribute_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__Prepend_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__RemoveAll_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__RemoveAt_System_Xml_XmlAttribute_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlAttributeCollection__Remove_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlCharacterData__AppendData_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlCharacterData__DeleteData_System_Void_System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlCharacterData__InsertData_System_Void_System_Int32_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlCharacterData__ReplaceData_System_Void_System_Int32_System_Int32_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlCharacterData__Substring_System_String_System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__DecodeName_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__EncodeLocalName_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__EncodeName_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__EncodeNmToken_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsNCNameChar_System_Boolean_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsPublicIdChar_System_Boolean_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsStartNCNameChar_System_Boolean_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsWhitespaceChar_System_Boolean_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsXmlChar_System_Boolean_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__IsXmlSurrogatePair_System_Boolean_System_Char_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToBoolean_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToByte_System_Byte_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToChar_System_Char_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTimeOffset_System_DateTimeOffset_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTimeOffset_System_DateTimeOffset_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTimeOffset_System_DateTimeOffset_System_String_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTime_System_DateTime_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTime_System_DateTime_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTime_System_DateTime_System_String_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDateTime_System_DateTime_System_String_System_Xml_XmlDateTimeSerializationMode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDecimal_System_Decimal_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToDouble_System_Double_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToGuid_System_Guid_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToInt16_System_Int16_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToInt32_System_Int32_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToInt64_System_Int64_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToSByte_System_SByte_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToSingle_System_Single_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToTimeSpan_System_TimeSpan_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToUInt16_System_UInt16_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToUInt32_System_UInt32_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__ToUInt64_System_UInt64_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyNCName_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyNMTOKEN_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyName_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyPublicId_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyTOKEN_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyWhitespace_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlConvert__VerifyXmlChars_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateAttribute_System_Xml_XmlAttribute_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateAttribute_System_Xml_XmlAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateAttribute_System_Xml_XmlAttribute_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateCDataSection_System_Xml_XmlCDataSection_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateComment_System_Xml_XmlComment_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateDocumentFragment_System_Xml_XmlDocumentFragment__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateDocumentType_System_Xml_XmlDocumentType_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateElement_System_Xml_XmlElement_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateElement_System_Xml_XmlElement_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateElement_System_Xml_XmlElement_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateEntityReference_System_Xml_XmlEntityReference_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateNode_System_Xml_XmlNode_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateNode_System_Xml_XmlNode_System_Xml_XmlNodeType_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateNode_System_Xml_XmlNode_System_Xml_XmlNodeType_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateProcessingInstruction_System_Xml_XmlProcessingInstruction_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateSignificantWhitespace_System_Xml_XmlSignificantWhitespace_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateTextNode_System_Xml_XmlText_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateWhitespace_System_Xml_XmlWhitespace_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__CreateXmlDeclaration_System_Xml_XmlDeclaration_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__GetElementById_System_Xml_XmlElement_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__GetElementsByTagName_System_Xml_XmlNodeList_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__GetElementsByTagName_System_Xml_XmlNodeList_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__ImportNode_System_Xml_XmlNode_System_Xml_XmlNode_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__LoadXml_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Load_System_Void_System_IO_Stream_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Load_System_Void_System_IO_TextReader_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Load_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Load_System_Void_System_Xml_XmlReader_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__ReadNode_System_Xml_XmlNode_System_Xml_XmlReader_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Save_System_Void_System_IO_Stream_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Save_System_Void_System_IO_TextWriter_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Save_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Save_System_Void_System_Xml_XmlWriter_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Validate_System_Void_System_Xml_Schema_ValidationEventHandler_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlDocument__Validate_System_Void_System_Xml_Schema_ValidationEventHandler_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetAttributeNode_System_Xml_XmlAttribute_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetAttributeNode_System_Xml_XmlAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetAttribute_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetElementsByTagName_System_Xml_XmlNodeList_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__GetElementsByTagName_System_Xml_XmlNodeList_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__HasAttribute_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__HasAttribute_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAllAttributes_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAttributeAt_System_Xml_XmlNode_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAttributeNode_System_Xml_XmlAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAttributeNode_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAttribute_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__RemoveAttribute_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__SetAttributeNode_System_Xml_XmlAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__SetAttributeNode_System_Xml_XmlAttribute_System_Xml_XmlAttribute_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__SetAttribute_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlElement__SetAttribute_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlImplementation__CreateDocument_System_Xml_XmlDocument__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlImplementation__HasFeature_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNameTable__Add_System_String_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNameTable__Add_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNameTable__Get_System_String_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNameTable__Get_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__GetEnumerator_System_Collections_IEnumerator__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__GetNamedItem_System_Xml_XmlNode_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__GetNamedItem_System_Xml_XmlNode_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__Item_System_Xml_XmlNode_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__RemoveNamedItem_System_Xml_XmlNode_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__RemoveNamedItem_System_Xml_XmlNode_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamedNodeMap__SetNamedItem_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__AddNamespace_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__GetEnumerator_System_Collections_IEnumerator__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__GetNamespacesInScope_System_Collections_Generic_IDictionary_System_String_System_String__System_Xml_XmlNamespaceScope_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__HasNamespace_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__LookupNamespace_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__LookupPrefix_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__PopScope_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__PushScope_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNamespaceManager__RemoveNamespace_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNodeList__GetEnumerator_System_Collections_IEnumerator__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNodeList__Item_System_Xml_XmlNode_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNodeType() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__AppendChild_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__CloneNode_System_Xml_XmlNode_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__Clone_System_Xml_XmlNode__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__CreateNavigator_System_Xml_XPath_XPathNavigator__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__GetEnumerator_System_Collections_IEnumerator__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__GetNamespaceOfPrefix_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__GetPrefixOfNamespace_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__InsertAfter_System_Xml_XmlNode_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__InsertBefore_System_Xml_XmlNode_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__PrependChild_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__RemoveAll_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__RemoveChild_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__ReplaceChild_System_Xml_XmlNode_System_Xml_XmlNode_System_Xml_XmlNode_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__SelectNodes_System_Xml_XmlNodeList_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__SelectNodes_System_Xml_XmlNodeList_System_String_System_Xml_XmlNamespaceManager_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__SelectSingleNode_System_Xml_XmlNode_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__SelectSingleNode_System_Xml_XmlNode_System_String_System_Xml_XmlNamespaceManager_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__Supports_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__WriteContentTo_System_Void_System_Xml_XmlWriter_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlNode__WriteTo_System_Void_System_Xml_XmlWriter_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReaderSettings__Clone_System_Xml_XmlReaderSettings__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__Close_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__Dispose_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__GetAttribute_System_String_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__GetAttribute_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__GetAttribute_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__GetValueAsync_System_Threading_Tasks_Task_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__IsNameToken_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__IsName_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__IsStartElement_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__IsStartElement_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__IsStartElement_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__LookupNamespace_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToAttribute_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToAttribute_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToAttribute_System_Void_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToContentAsync_System_Threading_Tasks_Task_System_Xml_XmlNodeType___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToContent_System_Xml_XmlNodeType__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToElement_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToFirstAttribute_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__MoveToNextAttribute_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadAsync_System_Threading_Tasks_Task_System_Boolean___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadAttributeValue_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsAsync_System_Threading_Tasks_Task_System_Object__System_Type_System_Xml_IXmlNamespaceResolver_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsBase64Async_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsBase64_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsBinHexAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsBinHex_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsBoolean_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsDateTimeOffset_System_DateTimeOffset__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsDateTime_System_DateTime__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsDecimal_System_Decimal__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsDouble_System_Double__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsFloat_System_Single__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsInt_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsLong_System_Int64__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsObjectAsync_System_Threading_Tasks_Task_System_Object___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsObject_System_Object__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsStringAsync_System_Threading_Tasks_Task_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAsString_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadContentAs_System_Object_System_Type_System_Xml_IXmlNamespaceResolver_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsAsync_System_Threading_Tasks_Task_System_Object__System_Type_System_Xml_IXmlNamespaceResolver_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBase64Async_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBase64_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBinHexAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBinHex_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBoolean_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsBoolean_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDateTime_System_DateTime_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDateTime_System_DateTime__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDecimal_System_Decimal_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDecimal_System_Decimal__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDouble_System_Double_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsDouble_System_Double__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsFloat_System_Single_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsFloat_System_Single__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsInt_System_Int32_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsInt_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsLong_System_Int64_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsLong_System_Int64__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsObjectAsync_System_Threading_Tasks_Task_System_Object___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsObject_System_Object_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsObject_System_Object__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsStringAsync_System_Threading_Tasks_Task_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsString_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAsString_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAs_System_Object_System_Type_System_Xml_IXmlNamespaceResolver_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementContentAs_System_Object_System_Type_System_Xml_IXmlNamespaceResolver_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementString_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementString_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadElementString_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadEndElement_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadInnerXmlAsync_System_Threading_Tasks_Task_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadInnerXml_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadOuterXmlAsync_System_Threading_Tasks_Task_System_String___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadOuterXml_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadStartElement_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadStartElement_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadStartElement_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadString_System_String__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadSubtree_System_Xml_XmlReader__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToDescendant_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToDescendant_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToFollowing_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToFollowing_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToNextSibling_System_Boolean_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadToNextSibling_System_Boolean_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadValueChunkAsync_System_Threading_Tasks_Task_System_Int32__System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ReadValueChunk_System_Int32_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__Read_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__ResolveEntity_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__SkipAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlReader__Skip_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlResolver__GetEntityAsync_System_Threading_Tasks_Task_System_Object__System_Uri_System_String_System_Type_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlResolver__GetEntity_System_Object_System_Uri_System_String_System_Type_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlResolver__ResolveUri_System_Uri_System_Uri_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlResolver__SupportsType_System_Boolean_System_Uri_System_Type_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__GetNamespacesInScope_System_Collections_Generic_IDictionary_System_String_System_String__System_Xml_XmlNamespaceScope_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__GetRemainder_System_IO_TextReader__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__HasLineInfo_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__ReadBase64_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__ReadBinHex_System_Int32_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__ReadChars_System_Int32_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlTextReader__ResetState_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlText__SplitText_System_Xml_XmlText_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlValidatingReader__HasLineInfo_System_Boolean__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlValidatingReader__ReadTypedValue_System_Object__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriterSettings__Clone_System_Xml_XmlWriterSettings__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__Close_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__DisposeAsync_System_Threading_Tasks_ValueTask__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__Dispose_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__FlushAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__Flush_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__LookupPrefix_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributeStringAsync_System_Threading_Tasks_Task_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributeString_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributeString_System_Void_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributeString_System_Void_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributesAsync_System_Threading_Tasks_Task_System_Xml_XmlReader_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteAttributes_System_Void_System_Xml_XmlReader_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteBase64Async_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteBase64_System_Void_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteBinHexAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteBinHex_System_Void_System_Byte___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCDataAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCData_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCharEntityAsync_System_Threading_Tasks_Task_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCharEntity_System_Void_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCharsAsync_System_Threading_Tasks_Task_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteChars_System_Void_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteCommentAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteComment_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteDocTypeAsync_System_Threading_Tasks_Task_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteDocType_System_Void_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteElementStringAsync_System_Threading_Tasks_Task_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteElementString_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteElementString_System_Void_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteElementString_System_Void_System_String_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEndAttribute_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEndDocumentAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEndDocument_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEndElementAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEndElement_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEntityRefAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteEntityRef_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteFullEndElementAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteFullEndElement_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNameAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteName_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNmTokenAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNmToken_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNodeAsync_System_Threading_Tasks_Task_System_Xml_XPath_XPathNavigator_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNodeAsync_System_Threading_Tasks_Task_System_Xml_XmlReader_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNode_System_Void_System_Xml_XPath_XPathNavigator_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteNode_System_Void_System_Xml_XmlReader_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteProcessingInstructionAsync_System_Threading_Tasks_Task_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteProcessingInstruction_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteQualifiedNameAsync_System_Threading_Tasks_Task_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteQualifiedName_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteRawAsync_System_Threading_Tasks_Task_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteRawAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteRaw_System_Void_System_Char___System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteRaw_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartAttribute_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartAttribute_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartAttribute_System_Void_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartDocumentAsync_System_Threading_Tasks_Task_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartDocumentAsync_System_Threading_Tasks_Task__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartDocument_System_Void_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartDocument_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartElementAsync_System_Threading_Tasks_Task_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartElement_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartElement_System_Void_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStartElement_System_Void_System_String_System_String_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteStringAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteString_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteSurrogateCharEntityAsync_System_Threading_Tasks_Task_System_Char_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteSurrogateCharEntity_System_Void_System_Char_System_Char_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Boolean_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_DateTimeOffset_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_DateTime_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Decimal_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Double_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Int64_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Object_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_Single_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteValue_System_Void_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteWhitespaceAsync_System_Threading_Tasks_Task_System_String_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Xml_ReaderWriter_System_Xml_XmlWriter__WriteWhitespace_System_Void_System_String_() noexcept;

} // namespace chaos::il2cpp::codegen::CombinedSubjects

void ChaosReflectionSetExceptionMetadata_2params(CHAOS_IL2CPP_INTPTR chaos_exception, CHAOS_IL2CPP_INTPTR chaos_message, CHAOS_IL2CPP_INTPTR chaos_param_name);

