# CMake generated Testfile for 
# Source directory: /home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading
# Build directory: /home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_threading_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_threading_smoke")
set_tests_properties([=[test_threading_smoke]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;19;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_synchronization_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_synchronization_smoke")
set_tests_properties([=[test_synchronization_smoke]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;26;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_threading_benchmark]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_threading_benchmark")
set_tests_properties([=[test_threading_benchmark]=] PROPERTIES  LABELS "benchmark;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;33;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_async_integration_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_async_integration_smoke")
set_tests_properties([=[test_async_integration_smoke]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;40;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_execution_context_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_execution_context_smoke")
set_tests_properties([=[test_execution_context_smoke]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;48;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_queue_backpressure]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_queue_backpressure")
set_tests_properties([=[test_queue_backpressure]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;56;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_threading_stress]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_threading_stress")
set_tests_properties([=[test_threading_stress]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;63;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_hc_cpu_feedback]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_hc_cpu_feedback")
set_tests_properties([=[test_hc_cpu_feedback]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;70;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_rwlock_upgrade]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_rwlock_upgrade")
set_tests_properties([=[test_rwlock_upgrade]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;79;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_phase3_industrialization]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_phase3_industrialization")
set_tests_properties([=[test_phase3_industrialization]=] PROPERTIES  LABELS "unit;threading" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;87;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_object_header_stress]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_object_header_stress")
set_tests_properties([=[test_object_header_stress]=] PROPERTIES  LABELS "stress;threading;typesystem" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;95;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
add_test([=[test_object_header_benchmark]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/threading/test_object_header_benchmark")
set_tests_properties([=[test_object_header_benchmark]=] PROPERTIES  LABELS "benchmark;threading;typesystem" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;103;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/threading/CMakeLists.txt;0;")
