// Auto-generated type declarations (TU paging)
#pragma once

#include <chaos/native_types.h>
#include <chaos/type_info.h>  // MethodTable, TypeInfoV0 (complete type)
#include "generated_code_compat.h"  // PureTypeHeader for delegate type definitions
#include "ChaosGeneratedRuntimePrelude.h"  // chaos_managed_array for array-compat checks

typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_Memory_System_Byte_;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Private_CoreLib_System_Threading_CancellationToken;

struct chaos_type_System_Private_CoreLib_System_Object
{
    ThinLockableHeader header{};
};

struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Byte
{
    ThinLockableHeader header{};
};

struct chaos_type_System_Private_CoreLib_System_Int32 : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Memory_System_Byte_ : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_ : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR runtime_assembly_name_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase
{
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase
{
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_String
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR length = 0;
    const char* utf8_data = nullptr;
    CHAOS_IL2CPP_UINT64 string_id = 0u;  // stable StringId, 0 = not yet materialized
};

struct chaos_type_System_Private_CoreLib_System_Threading_CancellationToken : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Type : public chaos_type_System_Private_CoreLib_System_Object
{
    CHAOS_IL2CPP_INTPTR runtime_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};


struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder;
struct chaos_boxed_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder {
    PureTypeHeader header{};
    chaos_valuetype_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder value{};
};
struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__;
struct chaos_boxed_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__;
struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder;
struct chaos_boxed_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder value{};
};
struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__;
struct chaos_boxed_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__;
struct chaos_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_;
struct chaos_boxed_type_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_Array;
struct chaos_boxed_type_System_Private_CoreLib_System_Array;
struct chaos_type_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____;
struct chaos_boxed_type_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____;
struct chaos_type_System_Private_CoreLib_System_Byte;
struct chaos_boxed_type_System_Private_CoreLib_System_Byte;
struct chaos_type_System_Private_CoreLib_System_IO_Stream;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_;
struct chaos_type_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_;
struct chaos_boxed_type_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_;
struct chaos_type_System_Private_CoreLib_System_Int32;
struct chaos_boxed_type_System_Private_CoreLib_System_Int32 {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR value = 0;
};
struct chaos_type_System_Private_CoreLib_System_Memory_System_Byte_;
struct chaos_boxed_type_System_Private_CoreLib_System_Memory_System_Byte_ {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_Memory_System_Byte_ value{};
};
struct chaos_type_System_Private_CoreLib_System_Object;
struct chaos_boxed_type_System_Private_CoreLib_System_Object;
struct chaos_type_System_Private_CoreLib_System_Object___ctor_System_Void__;
struct chaos_boxed_type_System_Private_CoreLib_System_Object___ctor_System_Void__;
struct chaos_type_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_;
struct chaos_boxed_type_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_ {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_ value{};
};
struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__;
struct chaos_boxed_type_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__;
struct chaos_type_System_Private_CoreLib_System_String;
struct chaos_boxed_type_System_Private_CoreLib_System_String;
struct chaos_type_System_Private_CoreLib_System_Threading_CancellationToken;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_CancellationToken {
    PureTypeHeader header{};
    chaos_valuetype_System_Private_CoreLib_System_Threading_CancellationToken value{};
};
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_Task;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_Task;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32_;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32_;
struct chaos_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___;
struct chaos_boxed_type_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___;
struct chaos_type_System_Private_CoreLib_System_Type;
struct chaos_boxed_type_System_Private_CoreLib_System_Type;

struct HotpatchEntryV0;
extern "C" HotpatchEntryV0 s_hotpatch_entries[];

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern MethodTable chaos_mt_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder;
extern MethodTable chaos_mt_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__;
extern MethodTable chaos_mt_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder;
extern MethodTable chaos_mt_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__;
extern MethodTable chaos_mt_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Array;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Byte;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Int32;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Memory_System_Byte_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Object;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Object___ctor_System_Void__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_Assembly;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_AssemblyName;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_FieldInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodBase;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_String;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_CancellationToken;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_Task;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_ValueTask;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Type;


extern CHAOS_IL2CPP_INTPTR chaos_static_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Byte;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Int32;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Memory_System_Byte_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Object___ctor_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Threading_CancellationToken;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__;
extern CHAOS_IL2CPP_INTPTR chaos_static_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___;

extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Array;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Byte;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Int32;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Memory_System_Byte_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Object;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Object___ctor_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_Assembly;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_AssemblyName;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_FieldInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_MethodBase;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Reflection_MethodInfo;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_String;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_CancellationToken;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_Task;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_ValueTask;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32_;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___;
extern const CHAOS_IL2CPP_UINT64 chaos_type_id_System_Private_CoreLib_System_Type;

extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Byte(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_String(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Type(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Object(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_MethodBase(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_MethodInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_ConstructorInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_FieldInfo(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_Assembly(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Reflection_AssemblyName(void);
extern "C" void chaos_ensure_type_initialized_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder(void);
extern "C" void chaos_ensure_type_initialized_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_CancellationToken(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Memory_System_Byte_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Int32(void);
extern "C" void chaos_ensure_type_initialized_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Object___ctor_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Array(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_Task(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_ValueTask(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_(void);
extern "C" void chaos_ensure_type_initialized_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_(void);

CHAOS_IL2CPP_INTPTR chaos_string_materialize(CHAOS_IL2CPP_INTPTR chaos_value) noexcept;
inline CHAOS_IL2CPP_INTPTR chaos_string_materialize(CHAOS_IL2CPP_INTPTR chaos_value) noexcept { return chaos_value; }

bool chaos_is_array_store_compatible(const chaos_managed_array* chaos_array, CHAOS_IL2CPP_INTPTR chaos_value) noexcept;

void chaos_default_interpolated_string_handler_reset(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_literal_length, CHAOS_IL2CPP_INT32 chaos_trailing_count);
void chaos_default_interpolated_string_handler_append_string(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INTPTR chaos_string_value);
void chaos_default_interpolated_string_handler_append_int32(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_value);
CHAOS_IL2CPP_INTPTR chaos_default_interpolated_string_handler_to_string_and_clear(CHAOS_IL2CPP_INTPTR chaos_handler_ref);

} // namespace chaos::il2cpp::codegen::CombinedSubjects

extern "C" void* kChaosExternalRuntimeFnTable[];

extern "C" CHAOS_IL2CPP_INT32 kChaosExternalRuntimeCount;

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_IO_Compression_Brotli_System_IO_Compression_BrotliDecoder__Dispose_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__Dispose_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_IO_Compression_Brotli_System_IO_Compression_BrotliEncoder__GetMaxCompressedLength_System_Int32_System_Int32_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Byte() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__BeginRead_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__BeginWrite_System_IAsyncResult_System_Byte___System_Int32_System_Int32_System_AsyncCallback_System_Object_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__DisposeAsync_System_Threading_Tasks_ValueTask__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__EndRead_System_Int32_System_IAsyncResult_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__EndWrite_System_Void_System_IAsyncResult_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__FlushAsync_System_Threading_Tasks_Task_System_Threading_CancellationToken_() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__Flush_System_Void__(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_Task_System_Int32__System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__ReadAsync_System_Threading_Tasks_ValueTask_System_Int32__System_Memory_System_Byte__System_Threading_CancellationToken_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__ReadByte_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INT32 chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__Read_System_Int32_System_Byte___System_Int32_System_Int32_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INT32 chaos_fn_arg_2, CHAOS_IL2CPP_INT32 chaos_fn_arg_3) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__Seek_System_Int64_System_Int64_System_IO_SeekOrigin_() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__SetLength_System_Void_System_Int64_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INT64 chaos_fn_arg_1) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_Task_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__WriteAsync_System_Threading_Tasks_ValueTask_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__WriteByte_System_Void_System_Byte_() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_IO_Stream__Write_System_Void_System_Byte___System_Int32_System_Int32_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1, CHAOS_IL2CPP_INT32 chaos_fn_arg_2, CHAOS_IL2CPP_INT32 chaos_fn_arg_3) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Int32() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Memory_System_Byte_() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_Object___ctor_System_Void__(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_ReadOnlyMemory_System_Byte_() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___GetResult_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_TaskAwaiter__GetResult_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___GetResult_System_Int32__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Runtime_CompilerServices_ValueTaskAwaiter__GetResult_System_Void__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_CancellationToken() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task_System_Int32___GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter_System_Int32___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_Task__GetAwaiter_System_Runtime_CompilerServices_TaskAwaiter__() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_ValueTask_System_Int32___GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter_System_Int32___() noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Threading_Tasks_ValueTask__GetAwaiter_System_Runtime_CompilerServices_ValueTaskAwaiter__() noexcept;

} // namespace chaos::il2cpp::codegen::CombinedSubjects

void ChaosReflectionSetExceptionMetadata_2params(CHAOS_IL2CPP_INTPTR chaos_exception, CHAOS_IL2CPP_INTPTR chaos_message, CHAOS_IL2CPP_INTPTR chaos_param_name);

