// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Xml.Xsl;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.Xml;

namespace AutoGenerated.System_Private_Xml
{
    public unsafe partial class System_Xml_XmlReaderTests
    {

        [Fact]
        [HotUpdate]
        public long ReadContentAsObject_0__0()
        {
            var result_0_0 = default(global::System.Xml.XmlReader)!.ReadContentAsObject();
            return (object)(result_0_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsObject_0__0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsObject();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBoolean_1__1()
        {
            var result_1_1 = default(global::System.Xml.XmlReader)!.ReadContentAsBoolean();
            return result_1_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBoolean_1__1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBoolean();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsDateTime_2__2()
        {
            var result_2_2 = default(global::System.Xml.XmlReader)!.ReadContentAsDateTime();
            return (object)(result_2_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsDateTime_2__2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsDateTime();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsDateTimeOffset_3__3()
        {
            var result_3_3 = default(global::System.Xml.XmlReader)!.ReadContentAsDateTimeOffset();
            return (object)(result_3_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsDateTimeOffset_3__3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsDateTimeOffset();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsDouble_4__4()
        {
            var result_4_4 = default(global::System.Xml.XmlReader)!.ReadContentAsDouble();
            return BitConverter.DoubleToInt64Bits(result_4_4);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsDouble_4__4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsDouble();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsFloat_5__5()
        {
            var result_5_5 = default(global::System.Xml.XmlReader)!.ReadContentAsFloat();
            return BitConverter.SingleToInt32Bits(result_5_5);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsFloat_5__5()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsFloat();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsDecimal_6__6()
        {
            var result_6_6 = default(global::System.Xml.XmlReader)!.ReadContentAsDecimal();
            return (long)(result_6_6);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsDecimal_6__6()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsDecimal();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsInt_7__7()
        {
            var result_7_7 = default(global::System.Xml.XmlReader)!.ReadContentAsInt();
            return (long)(result_7_7);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsInt_7__7()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsInt();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsLong_8__8()
        {
            var result_8_8 = default(global::System.Xml.XmlReader)!.ReadContentAsLong();
            return (long)(result_8_8);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsLong_8__8()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsLong();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsString_9__9()
        {
            var result_9_9 = default(global::System.Xml.XmlReader)!.ReadContentAsString();
            return (object)(result_9_9) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsString_9__9()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsString();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAs_10_System_Type_IXmlNamespaceResolver_0()
        {
            var result_10_0 = default(global::System.Xml.XmlReader)!.ReadContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
            return (object)(result_10_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAs_10_System_Type_IXmlNamespaceResolver_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsObject_11__11()
        {
            var result_11_11 = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject();
            return (object)(result_11_11) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsObject_11__11()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsObject_12_string_string_0()
        {
            var result_12_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject(default(string)!, default(string)!);
            return (object)(result_12_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsObject_12_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsObject_12_string_string_1()
        {
            var result_12_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject("", default(string)!);
            return (object)(result_12_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsObject_12_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsObject_12_string_string_2()
        {
            var result_12_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject(default(string)!, "");
            return (object)(result_12_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsObject_12_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsObject(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBoolean_13__13()
        {
            var result_13_13 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean();
            return result_13_13 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBoolean_13__13()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBoolean_14_string_string_0()
        {
            var result_14_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean(default(string)!, default(string)!);
            return result_14_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBoolean_14_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBoolean_14_string_string_1()
        {
            var result_14_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean("", default(string)!);
            return result_14_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBoolean_14_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBoolean_14_string_string_2()
        {
            var result_14_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean(default(string)!, "");
            return result_14_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBoolean_14_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBoolean(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDateTime_15__15()
        {
            var result_15_15 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime();
            return (object)(result_15_15) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDateTime_15__15()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDateTime_16_string_string_0()
        {
            var result_16_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime(default(string)!, default(string)!);
            return (object)(result_16_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDateTime_16_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDateTime_16_string_string_1()
        {
            var result_16_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime("", default(string)!);
            return (object)(result_16_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDateTime_16_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDateTime_16_string_string_2()
        {
            var result_16_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime(default(string)!, "");
            return (object)(result_16_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDateTime_16_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDateTime(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDouble_17__17()
        {
            var result_17_17 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble();
            return BitConverter.DoubleToInt64Bits(result_17_17);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDouble_17__17()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDouble_18_string_string_0()
        {
            var result_18_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble(default(string)!, default(string)!);
            return BitConverter.DoubleToInt64Bits(result_18_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDouble_18_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDouble_18_string_string_1()
        {
            var result_18_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble("", default(string)!);
            return BitConverter.DoubleToInt64Bits(result_18_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDouble_18_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDouble_18_string_string_2()
        {
            var result_18_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble(default(string)!, "");
            return BitConverter.DoubleToInt64Bits(result_18_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDouble_18_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDouble(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsFloat_19__19()
        {
            var result_19_19 = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat();
            return BitConverter.SingleToInt32Bits(result_19_19);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsFloat_19__19()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsFloat_20_string_string_0()
        {
            var result_20_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat(default(string)!, default(string)!);
            return BitConverter.SingleToInt32Bits(result_20_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsFloat_20_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsFloat_20_string_string_1()
        {
            var result_20_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat("", default(string)!);
            return BitConverter.SingleToInt32Bits(result_20_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsFloat_20_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsFloat_20_string_string_2()
        {
            var result_20_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat(default(string)!, "");
            return BitConverter.SingleToInt32Bits(result_20_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsFloat_20_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsFloat(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDecimal_21__21()
        {
            var result_21_21 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal();
            return (long)(result_21_21);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDecimal_21__21()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDecimal_22_string_string_0()
        {
            var result_22_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal(default(string)!, default(string)!);
            return (long)(result_22_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDecimal_22_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDecimal_22_string_string_1()
        {
            var result_22_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal("", default(string)!);
            return (long)(result_22_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDecimal_22_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsDecimal_22_string_string_2()
        {
            var result_22_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal(default(string)!, "");
            return (long)(result_22_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsDecimal_22_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsDecimal(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsInt_23__23()
        {
            var result_23_23 = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt();
            return (long)(result_23_23);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsInt_23__23()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsInt_24_string_string_0()
        {
            var result_24_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt(default(string)!, default(string)!);
            return (long)(result_24_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsInt_24_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsInt_24_string_string_1()
        {
            var result_24_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt("", default(string)!);
            return (long)(result_24_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsInt_24_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsInt_24_string_string_2()
        {
            var result_24_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt(default(string)!, "");
            return (long)(result_24_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsInt_24_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsInt(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsLong_25__25()
        {
            var result_25_25 = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong();
            return (long)(result_25_25);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsLong_25__25()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsLong_26_string_string_0()
        {
            var result_26_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong(default(string)!, default(string)!);
            return (long)(result_26_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsLong_26_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsLong_26_string_string_1()
        {
            var result_26_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong("", default(string)!);
            return (long)(result_26_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsLong_26_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsLong_26_string_string_2()
        {
            var result_26_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong(default(string)!, "");
            return (long)(result_26_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsLong_26_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsLong(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsString_27__27()
        {
            var result_27_27 = default(global::System.Xml.XmlReader)!.ReadElementContentAsString();
            return (object)(result_27_27) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsString_27__27()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsString();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsString_28_string_string_0()
        {
            var result_28_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsString(default(string)!, default(string)!);
            return (object)(result_28_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsString_28_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsString(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsString_28_string_string_1()
        {
            var result_28_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsString("", default(string)!);
            return (object)(result_28_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsString_28_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsString("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsString_28_string_string_2()
        {
            var result_28_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsString(default(string)!, "");
            return (object)(result_28_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsString_28_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsString(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAs_29_System_Type_IXmlNamespaceResolver_0()
        {
            var result_29_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
            return (object)(result_29_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAs_29_System_Type_IXmlNamespaceResolver_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAs_30_System_Type_IXmlNamespaceResolver_string_string_0()
        {
            var result_30_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!, default(string)!, default(string)!);
            return (object)(result_30_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAs_30_System_Type_IXmlNamespaceResolver_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!, default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAs_30_System_Type_IXmlNamespaceResolver_string_string_1()
        {
            var result_30_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!, "", default(string)!);
            return (object)(result_30_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAs_30_System_Type_IXmlNamespaceResolver_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAs(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!, "", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_31_string_0()
        {
            var result_31_0 = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!);
            return (object)(result_31_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_31_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_31_string_1()
        {
            var result_31_1 = default(global::System.Xml.XmlReader)!.GetAttribute("");
            return (object)(result_31_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_31_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute("");
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_32_string_string_0()
        {
            var result_32_0 = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!, default(string)!);
            return (object)(result_32_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_32_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_32_string_string_1()
        {
            var result_32_1 = default(global::System.Xml.XmlReader)!.GetAttribute("", default(string)!);
            return (object)(result_32_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_32_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_32_string_string_2()
        {
            var result_32_2 = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!, "");
            return (object)(result_32_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_32_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_33_int_0()
        {
            var result_33_0 = default(global::System.Xml.XmlReader)!.GetAttribute(default(int));
            return (object)(result_33_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_33_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute(default(int));
        }

        [Fact]
        [HotUpdate]
        public long GetAttribute_33_int_1()
        {
            var result_33_1 = default(global::System.Xml.XmlReader)!.GetAttribute((int)0);
            return (object)(result_33_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetAttribute_33_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.GetAttribute((int)0);
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_34_string_0()
        {
            var result_34_0 = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!);
            return result_34_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_34_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_34_string_1()
        {
            var result_34_1 = default(global::System.Xml.XmlReader)!.MoveToAttribute("");
            return result_34_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_34_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToAttribute("");
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_35_string_string_0()
        {
            var result_35_0 = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!, default(string)!);
            return result_35_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_35_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_35_string_string_1()
        {
            var result_35_1 = default(global::System.Xml.XmlReader)!.MoveToAttribute("", default(string)!);
            return result_35_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_35_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToAttribute("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_35_string_string_2()
        {
            var result_35_2 = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!, "");
            return result_35_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_35_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToAttribute(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_36_int_0()
        {
            default(global::System.Xml.XmlReader)!.MoveToAttribute(default(int));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_36_int_0()
        {
            default(global::System.Xml.XmlReader)!.MoveToAttribute(default(int));
        }

        [Fact]
        [HotUpdate]
        public long MoveToAttribute_36_int_1()
        {
            default(global::System.Xml.XmlReader)!.MoveToAttribute((int)0);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_MoveToAttribute_36_int_1()
        {
            default(global::System.Xml.XmlReader)!.MoveToAttribute((int)0);
        }

        [Fact]
        [HotUpdate]
        public long MoveToFirstAttribute_37__37()
        {
            var result_37_37 = default(global::System.Xml.XmlReader)!.MoveToFirstAttribute();
            return result_37_37 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToFirstAttribute_37__37()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToFirstAttribute();
        }

        [Fact]
        [HotUpdate]
        public long MoveToNextAttribute_38__38()
        {
            var result_38_38 = default(global::System.Xml.XmlReader)!.MoveToNextAttribute();
            return result_38_38 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToNextAttribute_38__38()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToNextAttribute();
        }

        [Fact]
        [HotUpdate]
        public long MoveToElement_39__39()
        {
            var result_39_39 = default(global::System.Xml.XmlReader)!.MoveToElement();
            return result_39_39 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToElement_39__39()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToElement();
        }

        [Fact]
        [HotUpdate]
        public long ReadAttributeValue_40__40()
        {
            var result_40_40 = default(global::System.Xml.XmlReader)!.ReadAttributeValue();
            return result_40_40 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadAttributeValue_40__40()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadAttributeValue();
        }

        [Fact]
        [HotUpdate]
        public long Read_41__41()
        {
            var result_41_41 = default(global::System.Xml.XmlReader)!.Read();
            return result_41_41 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Read_41__41()
        {
            _ = default(global::System.Xml.XmlReader)!.Read();
        }

        [Benchmark]
        public static void Benchmark_Close_42__42()
        {
            default(global::System.Xml.XmlReader)!.Close();
        }

        [Benchmark]
        public static void Benchmark_Skip_43__43()
        {
            default(global::System.Xml.XmlReader)!.Skip();
        }

        [Fact]
        [HotUpdate]
        public long LookupNamespace_44_string_0()
        {
            var result_44_0 = default(global::System.Xml.XmlReader)!.LookupNamespace(default(string)!);
            return (object)(result_44_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_LookupNamespace_44_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.LookupNamespace(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long LookupNamespace_44_string_1()
        {
            var result_44_1 = default(global::System.Xml.XmlReader)!.LookupNamespace("");
            return (object)(result_44_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_LookupNamespace_44_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.LookupNamespace("");
        }

        [Benchmark]
        public static void Benchmark_ResolveEntity_45__45()
        {
            default(global::System.Xml.XmlReader)!.ResolveEntity();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64_46_System_Byte_int_int_0()
        {
            var result_46_0 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, default(int), default(int));
            return (long)(result_46_0);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64_46_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64_46_System_Byte_int_int_1()
        {
            var result_46_1 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, (int)0, default(int));
            return (long)(result_46_1);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64_46_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64_46_System_Byte_int_int_2()
        {
            var result_46_2 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, default(int), (int)0);
            return (long)(result_46_2);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64_46_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64_46_System_Byte_int_int_3()
        {
            var result_46_3 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(System.Array.Empty<byte>(), default(int), default(int));
            return (long)(result_46_3);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64_46_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64_46_System_Byte_int_int_4()
        {
            var result_46_4 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
            return (long)(result_46_4);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64_46_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64_47_System_Byte_int_int_0()
        {
            var result_47_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, default(int), default(int));
            return (long)(result_47_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64_47_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64_47_System_Byte_int_int_1()
        {
            var result_47_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, (int)0, default(int));
            return (long)(result_47_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64_47_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64_47_System_Byte_int_int_2()
        {
            var result_47_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, default(int), (int)0);
            return (long)(result_47_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64_47_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64_47_System_Byte_int_int_3()
        {
            var result_47_3 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(System.Array.Empty<byte>(), default(int), default(int));
            return (long)(result_47_3);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64_47_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64_47_System_Byte_int_int_4()
        {
            var result_47_4 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
            return (long)(result_47_4);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64_47_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHex_48_System_Byte_int_int_0()
        {
            var result_48_0 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, default(int), default(int));
            return (long)(result_48_0);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHex_48_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHex_48_System_Byte_int_int_1()
        {
            var result_48_1 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, (int)0, default(int));
            return (long)(result_48_1);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHex_48_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHex_48_System_Byte_int_int_2()
        {
            var result_48_2 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, default(int), (int)0);
            return (long)(result_48_2);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHex_48_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHex_48_System_Byte_int_int_3()
        {
            var result_48_3 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(System.Array.Empty<byte>(), default(int), default(int));
            return (long)(result_48_3);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHex_48_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHex_48_System_Byte_int_int_4()
        {
            var result_48_4 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
            return (long)(result_48_4);
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHex_48_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHex(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHex_49_System_Byte_int_int_0()
        {
            var result_49_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, default(int), default(int));
            return (long)(result_49_0);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHex_49_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHex_49_System_Byte_int_int_1()
        {
            var result_49_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, (int)0, default(int));
            return (long)(result_49_1);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHex_49_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHex_49_System_Byte_int_int_2()
        {
            var result_49_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, default(int), (int)0);
            return (long)(result_49_2);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHex_49_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHex_49_System_Byte_int_int_3()
        {
            var result_49_3 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(System.Array.Empty<byte>(), default(int), default(int));
            return (long)(result_49_3);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHex_49_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHex_49_System_Byte_int_int_4()
        {
            var result_49_4 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
            return (long)(result_49_4);
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHex_49_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHex(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunk_50_System_Char_int_int_0()
        {
            var result_50_0 = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, default(int), default(int));
            return (long)(result_50_0);
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunk_50_System_Char_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunk_50_System_Char_int_int_1()
        {
            var result_50_1 = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, (int)0, default(int));
            return (long)(result_50_1);
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunk_50_System_Char_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunk_50_System_Char_int_int_2()
        {
            var result_50_2 = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, default(int), (int)0);
            return (long)(result_50_2);
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunk_50_System_Char_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunk(default(System.Char[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunk_50_System_Char_int_int_3()
        {
            var result_50_3 = default(global::System.Xml.XmlReader)!.ReadValueChunk(System.Array.Empty<char>(), default(int), default(int));
            return (long)(result_50_3);
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunk_50_System_Char_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunk(System.Array.Empty<char>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunk_50_System_Char_int_int_4()
        {
            var result_50_4 = default(global::System.Xml.XmlReader)!.ReadValueChunk(new char[2] { default(char)!, default(char)! }, default(int), default(int));
            return (long)(result_50_4);
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunk_50_System_Char_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunk(new char[2] { default(char)!, default(char)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadString_51__51()
        {
            var result_51_51 = default(global::System.Xml.XmlReader)!.ReadString();
            return (object)(result_51_51) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadString_51__51()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadString();
        }

        [Fact]
        [HotUpdate]
        public long MoveToContent_52__52()
        {
            var result_52_52 = default(global::System.Xml.XmlReader)!.MoveToContent();
            return (object)(result_52_52) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToContent_52__52()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToContent();
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_53__53()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement();
        }

        [Fact]
        [HotUpdate]
        public long ReadStartElement_54_string_0()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_54_string_0()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadStartElement_54_string_1()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement("");
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_54_string_1()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement("");
        }

        [Fact]
        [HotUpdate]
        public long ReadStartElement_55_string_string_0()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!, default(string)!);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_55_string_string_0()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadStartElement_55_string_string_1()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement("", default(string)!);
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_55_string_string_1()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadStartElement_55_string_string_2()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!, "");
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ReadStartElement_55_string_string_2()
        {
            default(global::System.Xml.XmlReader)!.ReadStartElement(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_56__56()
        {
            var result_56_56 = default(global::System.Xml.XmlReader)!.ReadElementString();
            return (object)(result_56_56) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_56__56()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_57_string_0()
        {
            var result_57_0 = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!);
            return (object)(result_57_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_57_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_57_string_1()
        {
            var result_57_1 = default(global::System.Xml.XmlReader)!.ReadElementString("");
            return (object)(result_57_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_57_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString("");
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_58_string_string_0()
        {
            var result_58_0 = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!, default(string)!);
            return (object)(result_58_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_58_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_58_string_string_1()
        {
            var result_58_1 = default(global::System.Xml.XmlReader)!.ReadElementString("", default(string)!);
            return (object)(result_58_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_58_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementString_58_string_string_2()
        {
            var result_58_2 = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!, "");
            return (object)(result_58_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementString_58_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementString(default(string)!, "");
        }

        [Benchmark]
        public static void Benchmark_ReadEndElement_59__59()
        {
            default(global::System.Xml.XmlReader)!.ReadEndElement();
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_60__60()
        {
            var result_60_60 = default(global::System.Xml.XmlReader)!.IsStartElement();
            return result_60_60 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_60__60()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement();
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_61_string_0()
        {
            var result_61_0 = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!);
            return result_61_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_61_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_61_string_1()
        {
            var result_61_1 = default(global::System.Xml.XmlReader)!.IsStartElement("");
            return result_61_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_61_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement("");
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_62_string_string_0()
        {
            var result_62_0 = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!, default(string)!);
            return result_62_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_62_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_62_string_string_1()
        {
            var result_62_1 = default(global::System.Xml.XmlReader)!.IsStartElement("", default(string)!);
            return result_62_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_62_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long IsStartElement_62_string_string_2()
        {
            var result_62_2 = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!, "");
            return result_62_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsStartElement_62_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.IsStartElement(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadToFollowing_63_string_0()
        {
            var result_63_0 = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!);
            return result_63_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToFollowing_63_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToFollowing_63_string_1()
        {
            var result_63_1 = default(global::System.Xml.XmlReader)!.ReadToFollowing("");
            return result_63_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToFollowing_63_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToFollowing("");
        }

        [Fact]
        [HotUpdate]
        public long ReadToFollowing_64_string_string_0()
        {
            var result_64_0 = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!, default(string)!);
            return result_64_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToFollowing_64_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToFollowing_64_string_string_1()
        {
            var result_64_1 = default(global::System.Xml.XmlReader)!.ReadToFollowing("", default(string)!);
            return result_64_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToFollowing_64_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToFollowing("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToFollowing_64_string_string_2()
        {
            var result_64_2 = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!, "");
            return result_64_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToFollowing_64_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToFollowing(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadToDescendant_65_string_0()
        {
            var result_65_0 = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!);
            return result_65_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToDescendant_65_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToDescendant_65_string_1()
        {
            var result_65_1 = default(global::System.Xml.XmlReader)!.ReadToDescendant("");
            return result_65_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToDescendant_65_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToDescendant("");
        }

        [Fact]
        [HotUpdate]
        public long ReadToDescendant_66_string_string_0()
        {
            var result_66_0 = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!, default(string)!);
            return result_66_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToDescendant_66_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToDescendant_66_string_string_1()
        {
            var result_66_1 = default(global::System.Xml.XmlReader)!.ReadToDescendant("", default(string)!);
            return result_66_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToDescendant_66_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToDescendant("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToDescendant_66_string_string_2()
        {
            var result_66_2 = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!, "");
            return result_66_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToDescendant_66_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToDescendant(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long ReadToNextSibling_67_string_0()
        {
            var result_67_0 = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!);
            return result_67_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToNextSibling_67_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToNextSibling_67_string_1()
        {
            var result_67_1 = default(global::System.Xml.XmlReader)!.ReadToNextSibling("");
            return result_67_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToNextSibling_67_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToNextSibling("");
        }

        [Fact]
        [HotUpdate]
        public long ReadToNextSibling_68_string_string_0()
        {
            var result_68_0 = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!, default(string)!);
            return result_68_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToNextSibling_68_string_string_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToNextSibling_68_string_string_1()
        {
            var result_68_1 = default(global::System.Xml.XmlReader)!.ReadToNextSibling("", default(string)!);
            return result_68_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToNextSibling_68_string_string_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToNextSibling("", default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadToNextSibling_68_string_string_2()
        {
            var result_68_2 = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!, "");
            return result_68_2 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadToNextSibling_68_string_string_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadToNextSibling(default(string)!, "");
        }

        [Fact]
        [HotUpdate]
        public long IsName_69_string_0()
        {
            var result_69_0 = global::System.Xml.XmlReader.IsName(default(string)!);
            return result_69_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsName_69_string_0()
        {
            _ = global::System.Xml.XmlReader.IsName(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long IsName_69_string_1()
        {
            var result_69_1 = global::System.Xml.XmlReader.IsName("");
            return result_69_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsName_69_string_1()
        {
            _ = global::System.Xml.XmlReader.IsName("");
        }

        [Fact]
        [HotUpdate]
        public long IsNameToken_70_string_0()
        {
            var result_70_0 = global::System.Xml.XmlReader.IsNameToken(default(string)!);
            return result_70_0 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsNameToken_70_string_0()
        {
            _ = global::System.Xml.XmlReader.IsNameToken(default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long IsNameToken_70_string_1()
        {
            var result_70_1 = global::System.Xml.XmlReader.IsNameToken("");
            return result_70_1 ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_IsNameToken_70_string_1()
        {
            _ = global::System.Xml.XmlReader.IsNameToken("");
        }

        [Fact]
        [HotUpdate]
        public long ReadInnerXml_71__71()
        {
            var result_71_71 = default(global::System.Xml.XmlReader)!.ReadInnerXml();
            return (object)(result_71_71) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadInnerXml_71__71()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadInnerXml();
        }

        [Fact]
        [HotUpdate]
        public long ReadOuterXml_72__72()
        {
            var result_72_72 = default(global::System.Xml.XmlReader)!.ReadOuterXml();
            return (object)(result_72_72) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadOuterXml_72__72()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadOuterXml();
        }

        [Fact]
        [HotUpdate]
        public long ReadSubtree_73__73()
        {
            var result_73_73 = default(global::System.Xml.XmlReader)!.ReadSubtree();
            return (object)(result_73_73) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadSubtree_73__73()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadSubtree();
        }

        [Benchmark]
        public static void Benchmark_Dispose_74__74()
        {
            default(global::System.Xml.XmlReader)!.Dispose();
        }

        [Fact]
        [HotUpdate]
        public long GetValueAsync_75__75()
        {
            var result_75_75 = default(global::System.Xml.XmlReader)!.GetValueAsync().GetAwaiter().GetResult();
            return (object)(result_75_75) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetValueAsync_75__75()
        {
            _ = default(global::System.Xml.XmlReader)!.GetValueAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsObjectAsync_76__76()
        {
            var result_76_76 = default(global::System.Xml.XmlReader)!.ReadContentAsObjectAsync().GetAwaiter().GetResult();
            return (object)(result_76_76) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsObjectAsync_76__76()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsObjectAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsStringAsync_77__77()
        {
            var result_77_77 = default(global::System.Xml.XmlReader)!.ReadContentAsStringAsync().GetAwaiter().GetResult();
            return (object)(result_77_77) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsStringAsync_77__77()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsStringAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsAsync_78_System_Type_IXmlNamespaceResolver_0()
        {
            var result_78_0 = default(global::System.Xml.XmlReader)!.ReadContentAsAsync(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!).GetAwaiter().GetResult();
            return (object)(result_78_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsAsync_78_System_Type_IXmlNamespaceResolver_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsAsync(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsObjectAsync_79__79()
        {
            var result_79_79 = default(global::System.Xml.XmlReader)!.ReadElementContentAsObjectAsync().GetAwaiter().GetResult();
            return (object)(result_79_79) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsObjectAsync_79__79()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsObjectAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsStringAsync_80__80()
        {
            var result_80_80 = default(global::System.Xml.XmlReader)!.ReadElementContentAsStringAsync().GetAwaiter().GetResult();
            return (object)(result_80_80) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsStringAsync_80__80()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsStringAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsAsync_81_System_Type_IXmlNamespaceResolver_0()
        {
            var result_81_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsAsync(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!).GetAwaiter().GetResult();
            return (object)(result_81_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsAsync_81_System_Type_IXmlNamespaceResolver_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsAsync(default(System.Type)!, default(System.Xml.IXmlNamespaceResolver)!);
        }

        [Fact]
        [HotUpdate]
        public long ReadAsync_82__82()
        {
            var result_82_82 = default(global::System.Xml.XmlReader)!.ReadAsync().GetAwaiter().GetResult();
            return (object)(result_82_82) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadAsync_82__82()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadAsync();
        }

        [Fact]
        [HotUpdate]
        public long SkipAsync_83__83()
        {
            default(global::System.Xml.XmlReader)!.SkipAsync().GetAwaiter().GetResult();
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_SkipAsync_83__83()
        {
            _ = default(global::System.Xml.XmlReader)!.SkipAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64Async_84_System_Byte_int_int_0()
        {
            var result_84_0 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_84_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64Async_84_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64Async_84_System_Byte_int_int_1()
        {
            var result_84_1 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, (int)0, default(int)).GetAwaiter().GetResult();
            return (object)(result_84_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64Async_84_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64Async_84_System_Byte_int_int_2()
        {
            var result_84_2 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, default(int), (int)0).GetAwaiter().GetResult();
            return (object)(result_84_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64Async_84_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64Async_84_System_Byte_int_int_3()
        {
            var result_84_3 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(System.Array.Empty<byte>(), default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_84_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64Async_84_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBase64Async_84_System_Byte_int_int_4()
        {
            var result_84_4 = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_84_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBase64Async_84_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBase64Async(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64Async_85_System_Byte_int_int_0()
        {
            var result_85_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_85_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64Async_85_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64Async_85_System_Byte_int_int_1()
        {
            var result_85_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, (int)0, default(int)).GetAwaiter().GetResult();
            return (object)(result_85_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64Async_85_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64Async_85_System_Byte_int_int_2()
        {
            var result_85_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, default(int), (int)0).GetAwaiter().GetResult();
            return (object)(result_85_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64Async_85_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64Async_85_System_Byte_int_int_3()
        {
            var result_85_3 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(System.Array.Empty<byte>(), default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_85_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64Async_85_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBase64Async_85_System_Byte_int_int_4()
        {
            var result_85_4 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_85_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBase64Async_85_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBase64Async(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHexAsync_86_System_Byte_int_int_0()
        {
            var result_86_0 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_86_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHexAsync_86_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHexAsync_86_System_Byte_int_int_1()
        {
            var result_86_1 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, (int)0, default(int)).GetAwaiter().GetResult();
            return (object)(result_86_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHexAsync_86_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHexAsync_86_System_Byte_int_int_2()
        {
            var result_86_2 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, default(int), (int)0).GetAwaiter().GetResult();
            return (object)(result_86_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHexAsync_86_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHexAsync_86_System_Byte_int_int_3()
        {
            var result_86_3 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(System.Array.Empty<byte>(), default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_86_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHexAsync_86_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadContentAsBinHexAsync_86_System_Byte_int_int_4()
        {
            var result_86_4 = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_86_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadContentAsBinHexAsync_86_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadContentAsBinHexAsync(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHexAsync_87_System_Byte_int_int_0()
        {
            var result_87_0 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_87_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHexAsync_87_System_Byte_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHexAsync_87_System_Byte_int_int_1()
        {
            var result_87_1 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, (int)0, default(int)).GetAwaiter().GetResult();
            return (object)(result_87_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHexAsync_87_System_Byte_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHexAsync_87_System_Byte_int_int_2()
        {
            var result_87_2 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, default(int), (int)0).GetAwaiter().GetResult();
            return (object)(result_87_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHexAsync_87_System_Byte_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(default(System.Byte[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHexAsync_87_System_Byte_int_int_3()
        {
            var result_87_3 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(System.Array.Empty<byte>(), default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_87_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHexAsync_87_System_Byte_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(System.Array.Empty<byte>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadElementContentAsBinHexAsync_87_System_Byte_int_int_4()
        {
            var result_87_4 = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_87_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadElementContentAsBinHexAsync_87_System_Byte_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadElementContentAsBinHexAsync(new byte[2] { default(byte)!, default(byte)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunkAsync_88_System_Char_int_int_0()
        {
            var result_88_0 = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_88_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunkAsync_88_System_Char_int_int_0()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunkAsync_88_System_Char_int_int_1()
        {
            var result_88_1 = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, (int)0, default(int)).GetAwaiter().GetResult();
            return (object)(result_88_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunkAsync_88_System_Char_int_int_1()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, (int)0, default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunkAsync_88_System_Char_int_int_2()
        {
            var result_88_2 = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, default(int), (int)0).GetAwaiter().GetResult();
            return (object)(result_88_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunkAsync_88_System_Char_int_int_2()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(default(System.Char[])!, default(int), (int)0);
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunkAsync_88_System_Char_int_int_3()
        {
            var result_88_3 = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(System.Array.Empty<char>(), default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_88_3) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunkAsync_88_System_Char_int_int_3()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(System.Array.Empty<char>(), default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long ReadValueChunkAsync_88_System_Char_int_int_4()
        {
            var result_88_4 = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(new char[2] { default(char)!, default(char)! }, default(int), default(int)).GetAwaiter().GetResult();
            return (object)(result_88_4) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadValueChunkAsync_88_System_Char_int_int_4()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadValueChunkAsync(new char[2] { default(char)!, default(char)! }, default(int), default(int));
        }

        [Fact]
        [HotUpdate]
        public long MoveToContentAsync_89__89()
        {
            var result_89_89 = default(global::System.Xml.XmlReader)!.MoveToContentAsync().GetAwaiter().GetResult();
            return (object)(result_89_89) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_MoveToContentAsync_89__89()
        {
            _ = default(global::System.Xml.XmlReader)!.MoveToContentAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadInnerXmlAsync_90__90()
        {
            var result_90_90 = default(global::System.Xml.XmlReader)!.ReadInnerXmlAsync().GetAwaiter().GetResult();
            return (object)(result_90_90) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadInnerXmlAsync_90__90()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadInnerXmlAsync();
        }

        [Fact]
        [HotUpdate]
        public long ReadOuterXmlAsync_91__91()
        {
            var result_91_91 = default(global::System.Xml.XmlReader)!.ReadOuterXmlAsync().GetAwaiter().GetResult();
            return (object)(result_91_91) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_ReadOuterXmlAsync_91__91()
        {
            _ = default(global::System.Xml.XmlReader)!.ReadOuterXmlAsync();
        }
    }
}
