# CMake generated Testfile for 
# Source directory: /home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs
# Build directory: /home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[string_stubs_test]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/string_stubs_test")
set_tests_properties([=[string_stubs_test]=] PROPERTIES  LABELS "unit;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;10;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
add_test([=[enum_stubs_test]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/enum_stubs_test")
set_tests_properties([=[enum_stubs_test]=] PROPERTIES  LABELS "unit;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;22;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
add_test([=[datetime_guid_math_test]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/datetime_guid_math_test")
set_tests_properties([=[datetime_guid_math_test]=] PROPERTIES  LABELS "unit;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;34;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
add_test([=[collection_stubs_test]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/collection_stubs_test")
set_tests_properties([=[collection_stubs_test]=] PROPERTIES  LABELS "unit;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;56;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
add_test([=[convert_stubs_test]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/convert_stubs_test")
set_tests_properties([=[convert_stubs_test]=] PROPERTIES  LABELS "unit;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;66;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
add_test([=[runtime_stubs_benchmark]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/runtime_stubs/runtime_stubs_benchmark")
set_tests_properties([=[runtime_stubs_benchmark]=] PROPERTIES  LABELS "benchmark;core" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;74;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/runtime_stubs/CMakeLists.txt;0;")
