# CMake generated Testfile for 
# Source directory: /home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter
# Build directory: /home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_interpreter_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_smoke")
set_tests_properties([=[test_interpreter_smoke]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;33;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_mini_smoke]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_mini_smoke")
set_tests_properties([=[test_interpreter_mini_smoke]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;39;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_smoke_isolated]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_smoke_isolated")
set_tests_properties([=[test_interpreter_smoke_isolated]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;45;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_integration]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_integration")
set_tests_properties([=[test_interpreter_integration]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;51;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_bridge]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_bridge")
set_tests_properties([=[test_interpreter_bridge]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;57;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_entry]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_entry")
set_tests_properties([=[test_interpreter_entry]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;63;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_new_features]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_new_features")
set_tests_properties([=[test_interpreter_new_features]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;69;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_profile]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_profile")
set_tests_properties([=[test_interpreter_profile]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;75;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_tiering_benchmark]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_tiering_benchmark")
set_tests_properties([=[test_tiering_benchmark]=] PROPERTIES  LABELS "benchmark;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;82;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_tiering_benchmark]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_tiering_benchmark")
set_tests_properties([=[test_interpreter_tiering_benchmark]=] PROPERTIES  LABELS "benchmark;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;89;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_interpreter_stress]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_interpreter_stress")
set_tests_properties([=[test_interpreter_stress]=] PROPERTIES  LABELS "stress;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;98;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_osr_state]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_osr_state")
set_tests_properties([=[test_osr_state]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;106;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
add_test([=[test_ir_reg_alloc]=] "/home/debian/agent/booming-il2cpp/testing/foundation-dll/src/native/runtime-core/interpreter/test_ir_reg_alloc")
set_tests_properties([=[test_ir_reg_alloc]=] PROPERTIES  LABELS "unit;interpreter" _BACKTRACE_TRIPLES "/home/debian/agent/booming-il2cpp/testing/src/native/CMakeLists.txt;155;add_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;112;add_chaos_test;/home/debian/agent/booming-il2cpp/testing/src/native/runtime-core/interpreter/CMakeLists.txt;0;")
