// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.Reflection.Metadata.Ecma335;

namespace AutoGenerated.System_Reflection_Metadata
{
    public unsafe partial class System_Reflection_Metadata_Ecma335_CodedIndexTests
    {

        [Fact]
        [HotUpdate]
        public long HasCustomAttribute_0_EntityHandle_0()
        {
            var result_0_0 = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasCustomAttribute(default(System.Reflection.Metadata.EntityHandle)!);
            Assert.AreEqual(7, result_0_0);
            return (long)(result_0_0);
        }

        [Benchmark]
        public static void Benchmark_HasCustomAttribute_0_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasCustomAttribute(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long HasConstant_1_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.HasConstant(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_HasConstant_1_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasConstant(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long CustomAttributeType_2_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.CustomAttributeType(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CustomAttributeType_2_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.CustomAttributeType(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long HasDeclSecurity_3_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.HasDeclSecurity(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_HasDeclSecurity_3_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasDeclSecurity(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long HasFieldMarshal_4_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.HasFieldMarshal(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_HasFieldMarshal_4_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasFieldMarshal(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long HasSemantics_5_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.HasSemantics(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_HasSemantics_5_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasSemantics(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long Implementation_6_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.Implementation(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_Implementation_6_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.Implementation(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long MemberForwarded_7_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.MemberForwarded(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_MemberForwarded_7_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.MemberForwarded(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long MemberRefParent_8_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.MemberRefParent(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_MemberRefParent_8_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.MemberRefParent(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long MethodDefOrRef_9_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.MethodDefOrRef(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_MethodDefOrRef_9_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.MethodDefOrRef(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long ResolutionScope_10_EntityHandle_0()
        {
            var result_10_0 = global::System.Reflection.Metadata.Ecma335.CodedIndex.ResolutionScope(default(System.Reflection.Metadata.EntityHandle)!);
            Assert.AreEqual(0, result_10_0);
            return (long)(result_10_0);
        }

        [Benchmark]
        public static void Benchmark_ResolutionScope_10_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.ResolutionScope(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long TypeDefOrRef_11_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRef(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_TypeDefOrRef_11_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRef(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long TypeDefOrRefOrSpec_12_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRefOrSpec(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_TypeDefOrRefOrSpec_12_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRefOrSpec(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long TypeOrMethodDef_13_EntityHandle_0()
        {
            Assert.Throws<System.ArgumentException>(() => global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeOrMethodDef(default(System.Reflection.Metadata.EntityHandle)!));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_TypeOrMethodDef_13_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.TypeOrMethodDef(default(System.Reflection.Metadata.EntityHandle)!);
        }

        [Fact]
        [HotUpdate]
        public long HasCustomDebugInformation_14_EntityHandle_0()
        {
            var result_14_0 = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasCustomDebugInformation(default(System.Reflection.Metadata.EntityHandle)!);
            Assert.AreEqual(7, result_14_0);
            return (long)(result_14_0);
        }

        [Benchmark]
        public static void Benchmark_HasCustomDebugInformation_14_EntityHandle_0()
        {
            _ = global::System.Reflection.Metadata.Ecma335.CodedIndex.HasCustomDebugInformation(default(System.Reflection.Metadata.EntityHandle)!);
        }
    }
}
