<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\managed\Chaos.IL2CPP.RuntimeSupport\Chaos.IL2CPP.RuntimeSupport.csproj" />
  </ItemGroup>
</Project>
