// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.ComponentModel;

namespace AutoGenerated.System_ComponentModel_TypeConverter
{
    public unsafe partial class System_ComponentModel_BindingListSystem_Int32Tests
    {

        [Fact]
        [HotUpdate]
        public long ResetBindings_0__0()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetBindings());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ResetBindings_0__0()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetBindings();
        }

        [Fact]
        [HotUpdate]
        public long ResetItem_1_int_0()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetItem(default(int)));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ResetItem_1_int_0()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetItem(default(int));
        }

        [Fact]
        [HotUpdate]
        public long ResetItem_1_int_1()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetItem((int)0));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_ResetItem_1_int_1()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.ResetItem((int)0);
        }

        [Fact]
        [HotUpdate]
        public long CancelNew_2_int_0()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.CancelNew(default(int)));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CancelNew_2_int_0()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.CancelNew(default(int));
        }

        [Fact]
        [HotUpdate]
        public long CancelNew_2_int_1()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.CancelNew((int)0));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_CancelNew_2_int_1()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.CancelNew((int)0);
        }

        [Fact]
        [HotUpdate]
        public long EndNew_3_int_0()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.EndNew(default(int)));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_EndNew_3_int_0()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.EndNew(default(int));
        }

        [Fact]
        [HotUpdate]
        public long EndNew_3_int_1()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.EndNew((int)0));
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_EndNew_3_int_1()
        {
            default(global::System.ComponentModel.BindingList<System.Int32>)!.EndNew((int)0);
        }

        [Fact]
        [HotUpdate]
        public long AddNew_4__4()
        {
            Assert.Throws<System.NullReferenceException>(() => default(global::System.ComponentModel.BindingList<System.Int32>)!.AddNew());
            return 42L;
        }

        [Benchmark]
        public static void Benchmark_AddNew_4__4()
        {
            _ = default(global::System.ComponentModel.BindingList<System.Int32>)!.AddNew();
        }
    }
}
