<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GoldenReferenceAssembly.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ReferenceGreeter">
      <HintPath>..\..\..\..\..\..\assets\reference-bundles\dotnet-foundation\lib\ReferenceGreeter.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
