<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FoundationDllTranslation.App</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.NETCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Extensions">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Runtime.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Console">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Console.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Linq.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>

