// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Xml.Xsl;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System.ComponentModel;

namespace AutoGenerated.System_ComponentModel_TypeConverter
{
    public unsafe partial class System_ComponentModel_PropertyDescriptorTests
    {

        [Fact]
        [HotUpdate]
        public long AddValueChanged_0_object_System_EventHandler_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.AddValueChanged(default(object)!, default(System.EventHandler)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long AddValueChanged_0_object_System_EventHandler_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.AddValueChanged(default(object)!, (object? sender, System.EventArgs e) => { }) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long CanResetValue_1_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.CanResetValue(default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_2__2()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties() (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_3_System_Attribute_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(default(System.Attribute[])!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_3_System_Attribute_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(System.Array.Empty<System.Attribute>()) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_3_System_Attribute_2()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(new System.Attribute[2] { default(System.Attribute)!, default(System.Attribute)! }) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_4_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_5_object_System_Attribute_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(default(object)!, default(System.Attribute[])!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_5_object_System_Attribute_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(default(object)!, System.Array.Empty<System.Attribute>()) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetChildProperties_5_object_System_Attribute_2()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetChildProperties(default(object)!, new System.Attribute[2] { default(System.Attribute)!, default(System.Attribute)! }) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetEditor_6_System_Type_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetEditor(default(System.Type)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long GetValue_7_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.GetValue(default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long RemoveValueChanged_8_object_System_EventHandler_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.RemoveValueChanged(default(object)!, default(System.EventHandler)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long RemoveValueChanged_8_object_System_EventHandler_1()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.RemoveValueChanged(default(object)!, (object? sender, System.EventArgs e) => { }) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long ResetValue_9_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.ResetValue(default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long SetValue_10_object_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.SetValue(default(object)!, default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }

        [Fact]
        [HotUpdate]
        public long ShouldSerializeValue_11_object_0()
        {
            // [AOT smoke] System.NullReferenceException thrown by default(global::System.ComponentModel.PropertyDescriptor)!.ShouldSerializeValue(default(object)!) (external assembly stub — skipping Throws)
            return 42L;
        }
    }
}
