<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>HotUpdateHostPack</AssemblyName>
    <RootNamespace>HotUpdateHostPack</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\\..\\proofs\\**\\*.cs" />
    <Compile Include="..\\..\\benchmarks\\**\\*.cs" />
    <Compile Include="..\\patch\\**\\*.cs" />
    <Compile Include="..\\shared-contracts\\**\\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\..\\..\\..\\..\\src\\reference\\Chaos.TestFramework.Sdk\\Chaos.TestFramework.Sdk.csproj" />
    <ProjectReference Include="..\\..\\..\\..\\..\\..\\src\\managed\\Chaos.IL2CPP.HotUpdate\\Chaos.IL2CPP.HotUpdate.csproj" />
  </ItemGroup>
</Project>

