// hotpatch_dispatch.h — Dispatch routing with hotpatch awareness
//
// Replaces the dispatch function bodies that were previously emitted inline
// by codegen's Scriban template (RunNativeAot, RunNativeAotAll, etc.).
//
// These functions are parameter-based (entries pointer + count) so the
// generated code passes its own s_hotpatch_entries array and method table.
// The dispatch logic itself (hotpatch check, interpreter fallback) lives
// in the runtime library, keeping the generated code as pure data.
//
// AOT mode path:
//   hotpatch inactive → call kDefaultArgThunks[index]()
//   hotpatch active   → InterpreterEntryDirect(method_key, args, ret)
//
// JIT mode path:
//   direct_ptr → direct call (precode handles JIT compilation)
//
// Usage in generated code:
//   #include <chaos/hotpatch_dispatch.h>
//   // ... s_hotpatch_entries[], kMethodTable[], kDefaultArgThunks[] defined ...
//   auto result = ChaosDispatchMethod(s_hotpatch_entries, kAotMethodCount, i, kDefaultArgThunks);

#ifndef CHAOS_IL2CPP_HOTPATCH_DISPATCH_H_
#define CHAOS_IL2CPP_HOTPATCH_DISPATCH_H_

#include <cstdint>
#include <chaos/config.h>

// Must precede <chaos/eh.h> on Windows SEH path (provides CHAOS_SEH_FILTER_ALL)
#include <exception_jmp.h>
#include <chaos/eh.h>

// HotpatchEntryV0, kHotpatchActive, kHotpatchKeepNative
#include <codegen_bridge.h>
// HotpatchIsActive, HotpatchShouldKeepNative  (inline in hotpatch_table.h)
#include <hotpatch_table.h>
// InterpreterEntryDirect, InterpreterEntryDirectFast
#include <interpreter_entry.h>

namespace chaos {
namespace il2cpp {
namespace runtime_core {

// ── ChaosDispatchMethod (AOT mode) ──────────────────────────────────────
// Single-method dispatch with hotpatch awareness.
//   entries: pointer to s_hotpatch_entries[] generated by codegen
//   count:   kAotMethodCount
//   index:   method slot to dispatch
//   thunks:  kDefaultArgThunks[] (may be nullptr in non-benchmark contexts)
//
// Dispatch priority:
//   1. Hotpatch active (not keep-native) → InterpreterEntryDirect
//   2. thunks provided → thunks[index]()
//   3. direct_ptr available → direct_ptr()  (AOT-compiled function body)
//   4. otherwise → no-op (graceful fallback)
//
// Returns 0 on success, -1 on invalid index.
inline int32_t ChaosDispatchMethod(
    const HotpatchEntryV0* entries,
    int32_t count,
    int32_t index,
    void (* const* thunks)() noexcept = nullptr) noexcept
{
    if (index < 0 || index >= count) return -1;
    auto& entry = entries[index];

#if defined(CHAOS_IL2CPP_JIT_MODE)
    // JIT mode: prefer AOT thunks when available (verification pipeline uses
    // AOT-compiled function bodies).  Only use direct_ptr when thunks are
    // null (true JIT path with precode trampoline + JIT compilation).
    if (thunks) {
        thunks[index]();
    } else {
        auto fn = reinterpret_cast<void(*)()>(entry.direct_ptr);
        if (fn == nullptr) {
            return -1;
        }
        fn();
    }
#else
    // AOT mode: check hotpatch status
    if (HotpatchIsActive(entry) && !HotpatchShouldKeepNative(entry)) {
        // Route to interpreter: patched method
        uint64_t __chaos_args[4] = {};
        uint64_t __chaos_ret[2] = {};
        InterpreterEntryDirect(
            entry.method_key, __chaos_args, __chaos_ret);
    } else if (thunks) {
        // Native execution via default-arg thunks (verification pipeline path)
        thunks[index]();
    } else if (entry.direct_ptr) {
        // Direct AOT function body (no thunks / JIT codegen compatibility)
        reinterpret_cast<void(*)()>(entry.direct_ptr)();
    }
#endif
    return 0;
}

// ── ChaosDispatchMethodAll (AOT mode) ──────────────────────────────────
// Loop dispatch over all methods. Returns count of failures.
inline int32_t ChaosDispatchMethodAll(
    const HotpatchEntryV0* entries,
    int32_t count,
    void (* const* thunks)() noexcept = nullptr) noexcept
{
    int32_t failures = 0;
    for (int32_t i = 0; i < count; i++) {
        CHAOS_EH_TRY
            ChaosDispatchMethod(entries, count, i, thunks);
        CHAOS_EH_CATCH_BEGIN
            ++failures;
        CHAOS_EH_END
    }
    return failures;
}

// ── ChaosDispatchMethodAllModules (AOT mode) ────────────────────────────
// Iterate dispatch over ALL registered modules' hotpatch entries.
// Uses HotpatchNameRegistry singleton to enumerate all modules.
// Each module's entries are dispatched individually; failures are summed.
// Returns total failures across all modules.
inline int32_t ChaosDispatchMethodAllModules(
    void (* const* thunks)() noexcept = nullptr) noexcept
{
    int32_t failures = 0;
    auto& registry = GetHotpatchNameRegistry();
    size_t moduleCount = registry.ModuleCount();
    for (size_t mi = 0; mi < moduleCount; ++mi) {
        const auto* mod = registry.GetModuleByIndex(mi);
        if (mod == nullptr || mod->entry_table == nullptr || mod->entry_table_size == 0) {
            continue;
        }
        int32_t count = static_cast<int32_t>(mod->entry_table_size);
        for (int32_t i = 0; i < count; ++i) {
            CHAOS_EH_TRY
                ChaosDispatchMethod(mod->entry_table, count, i, thunks);
            CHAOS_EH_CATCH_BEGIN
                ++failures;
            CHAOS_EH_END
        }
    }
    return failures;
}

// ── ChaosDispatchMethodBench (AOT mode, fast path) ──────────────────────
// Fast single-method dispatch: no setjmp, inline slot access.
// Uses InterpreterEntryDirectFast for patched methods (no zero-init overhead).
inline int32_t ChaosDispatchMethodBench(
    const HotpatchEntryV0* entries,
    int32_t count,
    int32_t index,
    void (* const* thunks)() noexcept = nullptr) noexcept
{
    if (index < 0 || index >= count) return -1;
    auto& entry = entries[index];

#if defined(CHAOS_IL2CPP_JIT_MODE)
    if (thunks) {
        thunks[index]();
    } else {
        reinterpret_cast<void(*)()>(entry.direct_ptr)();
    }
#else
    if (HotpatchIsActive(entry) && !HotpatchShouldKeepNative(entry)) {
        InterpreterEntryDirectFast(entry.method_key);
    } else if (thunks) {
        thunks[index]();
    } else if (entry.direct_ptr) {
        reinterpret_cast<void(*)()>(entry.direct_ptr)();
    }
#endif
    return 0;
}

}  // namespace runtime_core
}  // namespace il2cpp
}  // namespace chaos

#endif  // CHAOS_IL2CPP_HOTPATCH_DISPATCH_H_
