from tests.unit.compatibility.solution_core_pack_subject_test_support import *


class TestSolutionCorePackSubjectRuntime(SolutionCorePackSubjectTestSupport):
    def test_solution_core_launcher_uses_compact_subject_entry_selection_only(self) -> None:
        launcher_source = LAUNCHER_PROGRAM_PATH.read_text(encoding="utf-8")

        for required_fragment in [
            "ChaosSubjectEntryArguments.TryParse",
            "ChaosSubjectEntryKind.Proof",
            "ChaosSubjectSlice.CoreRuntimeFeaturesProof",
            "ChaosSubjectSlice.CoreRuntimeInterfaceDispatchProof",
        ]:
            self.assertIn(required_fragment, launcher_source)
        self.assertNotIn("ChaosSourceEntryArguments.TryParse", launcher_source)
        self.assertNotIn("InvokeSourceEntry(", launcher_source)

    def test_solution_core_pack_corelib_native_proof_program_uses_main_forwarder_shape(self) -> None:
        program_source = CORELIB_NATIVE_PROOF_PROGRAM_PATH.read_text(encoding="utf-8")

        self.assertIn("private static int Main()", program_source)
        self.assertIn("return PrintAndExit();", program_source)
        self.assertIn("private static int PrintAndExit()", program_source)
        self.assertIn("return ComposeAndPrint();", program_source)
        self.assertIn("private static int ComposeAndPrint()", program_source)
        self.assertIn("private sealed class AuxiliaryHolder", program_source)
        self.assertIn("private static int ComposeAuxiliary()", program_source)
        self.assertIn('new AuxiliaryHolder("System.Runtime").Render()', program_source)
        self.assertIn("private sealed class EchoHolder", program_source)
        self.assertIn("private static string EchoValue(string value)", program_source)
        self.assertIn("private static int ComposeEcho()", program_source)
        self.assertIn('new EchoHolder(EchoValue("corelib-reference-echo:System.Private.CoreLib|System.Console")).GetValue()', program_source)
        self.assertIn("private static int ComposeLiteral()", program_source)
        self.assertIn('Console.WriteLine("corelib-reference-literal:System.Console");', program_source)
        self.assertIn("private static string BuildLiteralMessage()", program_source)
        self.assertIn("private static int ComposeStaticMessage()", program_source)
        self.assertIn('Console.WriteLine(BuildLiteralMessage());', program_source)
        self.assertIn("private static int ComposeForwardedLiteral()", program_source)
        self.assertIn('Console.WriteLine(EchoValue("corelib-reference-forwarded:System.Private.CoreLib|System.Console"));', program_source)
        self.assertIn("private static int ComposeForwardedStaticMessage()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(BuildLiteralMessage()));', program_source)
        self.assertIn("private static int ComposeProducedEcho()", program_source)
        self.assertIn('Console.WriteLine(new EchoHolder(BuildLiteralMessage()).GetValue());', program_source)
        self.assertIn("private static int ComposeProducedRender()", program_source)
        self.assertIn('Console.WriteLine(new Holder(BuildLiteralMessage()).Render());', program_source)
        self.assertIn("private static int ComposeProducedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(new Holder(BuildLiteralMessage()).Render()));', program_source)
        self.assertIn("private static int ComposeProducedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(new EchoHolder(BuildLiteralMessage()).GetValue()));', program_source)
        self.assertIn("private static int ComposeForwardedProducedEcho()", program_source)
        self.assertIn('Console.WriteLine(new EchoHolder(EchoValue(BuildLiteralMessage())).GetValue());', program_source)
        self.assertIn("private static int ComposeForwardedProducedRender()", program_source)
        self.assertIn('Console.WriteLine(new Holder(EchoValue(BuildLiteralMessage())).Render());', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(new Holder(EchoValue(BuildLiteralMessage())).Render()));', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(new EchoHolder(EchoValue(BuildLiteralMessage())).GetValue()));', program_source)
        self.assertIn("private static int ComposeProducedForwardedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(new Holder(BuildLiteralMessage()).Render())));', program_source)
        self.assertIn("private static int ComposeProducedForwardedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(new EchoHolder(BuildLiteralMessage()).GetValue())));', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(new Holder(EchoValue(BuildLiteralMessage())).Render())));', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(new EchoHolder(EchoValue(BuildLiteralMessage())).GetValue())));', program_source)
        self.assertIn("private static int ComposeProducedForwardedForwardedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(EchoValue(new Holder(BuildLiteralMessage()).Render()))));', program_source)
        self.assertIn("private static int ComposeProducedForwardedForwardedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(EchoValue(new EchoHolder(BuildLiteralMessage()).GetValue()))));', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedForwardedForwardedRender()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(EchoValue(new Holder(EchoValue(BuildLiteralMessage())).Render()))));', program_source)
        self.assertIn("private static int ComposeForwardedProducedForwardedForwardedForwardedEcho()", program_source)
        self.assertIn('Console.WriteLine(EchoValue(EchoValue(EchoValue(new EchoHolder(EchoValue(BuildLiteralMessage())).GetValue()))));', program_source)
        self.assertIn("using System.Threading.Tasks;", program_source)
        self.assertIn("private static async Task<int> AddAsync(int left, int right)", program_source)
        self.assertIn("await Task.Yield();", program_source)
        self.assertIn("return left + right;", program_source)
        self.assertIn("private static async Task<int> ComputeAsyncValue(int seed)", program_source)
        self.assertIn("return await AddAsync(seed, 2);", program_source)
        self.assertIn("private static async Task<bool> CheckAsyncFlag(bool left, bool right)", program_source)
        self.assertIn("return left && right;", program_source)
        self.assertIn("private static async Task<bool> ComputeAsyncFlag(bool seed)", program_source)
        self.assertIn("return await CheckAsyncFlag(seed, false);", program_source)
        self.assertIn("private static async Task<bool> RelayAsyncFlag(bool left, bool right)", program_source)
        self.assertIn("return await CheckAsyncFlag(left, right);", program_source)
        self.assertIn("private static async Task<bool> RelayAsyncComputedFlag(bool seed)", program_source)
        self.assertIn("return await ComputeAsyncFlag(seed);", program_source)
        self.assertIn("private static int ComposeAsyncValue()", program_source)
        self.assertIn("return ComputeAsyncValue(40).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static int ComposeAsyncAddDirectValue()", program_source)
        self.assertIn("return AddAsync(40, 2).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static int ComposeForwardedAsyncAddDirectValue()", program_source)
        self.assertIn("return ComposeAsyncAddDirectValue();", program_source)
        self.assertIn("private static bool ComposeAsyncFlagDirectValue()", program_source)
        self.assertIn("return CheckAsyncFlag(true, false).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static bool ComposeForwardedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedForwardedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedForwardedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComputeAsyncFlag(true).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static bool ComposeRelayedAsyncFlagDirectValue()", program_source)
        self.assertIn("return RelayAsyncFlag(true, false).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static bool ComposeForwardedRelayedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeRelayedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedRelayedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedRelayedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedRelayedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedRelayedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedForwardedRelayedAsyncFlagDirectValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedForwardedRelayedAsyncFlagDirectValue();", program_source)
        self.assertIn("private static bool ComposeRelayedAsyncComputedFlagValue()", program_source)
        self.assertIn("return RelayAsyncComputedFlag(true).GetAwaiter().GetResult();", program_source)
        self.assertIn("private static bool ComposeForwardedRelayedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeRelayedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedRelayedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedRelayedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedRelayedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedRelayedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedForwardedRelayedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedForwardedRelayedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ComposeForwardedForwardedForwardedForwardedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ComposeForwardedForwardedForwardedAsyncComputedFlagValue();", program_source)
        self.assertIn("private static bool ForwardBoolValue(bool value)", program_source)
        self.assertIn("return value;", program_source)
        self.assertIn("private static bool ComposeBoolIdentityForwardedAsyncComputedFlagValue()", program_source)
        self.assertIn("return ForwardBoolValue(ComposeAsyncComputedFlagValue());", program_source)
        self.assertIn("private static async Task<string> BuildAsyncLiteralMessage()", program_source)
        self.assertIn("return BuildLiteralMessage();", program_source)
        self.assertIn("private static async Task<string> RelayAsyncLiteralMessage()", program_source)
        self.assertIn("return await BuildAsyncLiteralMessage();", program_source)
        self.assertIn("private static string ComposeAsyncLiteralMessageValue()", program_source)
        self.assertIn("return BuildAsyncLiteralMessage().GetAwaiter().GetResult();", program_source)
        self.assertIn("private static string ComposeRelayedAsyncLiteralMessageValue()", program_source)
        self.assertIn("return RelayAsyncLiteralMessage().GetAwaiter().GetResult();", program_source)
        self.assertIn("private static string ComposeForwardedRelayedAsyncLiteralMessageValue()", program_source)
        self.assertIn("return ComposeRelayedAsyncLiteralMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedRelayedAsyncLiteralMessageValue()", program_source)
        self.assertIn("return ComposeForwardedRelayedAsyncLiteralMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedAsyncLiteralMessageValue()", program_source)
        self.assertIn("return ComposeAsyncLiteralMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedAsyncLiteralMessageValue()", program_source)
        self.assertIn("return ComposeForwardedAsyncLiteralMessageValue();", program_source)
        self.assertIn("private static int ComposeAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static int ComposeRelayedAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeRelayedAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedRelayedAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedRelayedAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedRelayedAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedRelayedAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedAsyncLiteralMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedAsyncLiteralMessageValue());", program_source)
        self.assertIn("private static async Task<string> JoinAsync(string left, string right)", program_source)
        self.assertIn("return string.Concat(left, right);", program_source)
        self.assertIn("private static async Task<string> RelayJoinAsync(string left, string right)", program_source)
        self.assertIn("return await JoinAsync(left, right);", program_source)
        self.assertIn("private static async Task<string> BuildAsyncComposedMessage(string prefix)", program_source)
        self.assertIn('return await JoinAsync(prefix, "|System.Console");', program_source)
        self.assertIn("private static async Task<string> RelayAsyncComposedMessage(string prefix)", program_source)
        self.assertIn("return await BuildAsyncComposedMessage(prefix);", program_source)
        self.assertIn("private static string ComposeAsyncComposedMessageValue()", program_source)
        self.assertIn('return BuildAsyncComposedMessage("corelib-reference-async-string:System.Private.CoreLib|System.Runtime").GetAwaiter().GetResult();', program_source)
        self.assertIn("private static string ComposeRelayedAsyncComposedMessageValue()", program_source)
        self.assertIn('return RelayAsyncComposedMessage("corelib-reference-async-string:System.Private.CoreLib|System.Runtime").GetAwaiter().GetResult();', program_source)
        self.assertIn("private static string ComposeForwardedRelayedAsyncComposedMessageValue()", program_source)
        self.assertIn("return ComposeRelayedAsyncComposedMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedRelayedAsyncComposedMessageValue()", program_source)
        self.assertIn("return ComposeForwardedRelayedAsyncComposedMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedAsyncComposedMessageValue()", program_source)
        self.assertIn("return ComposeAsyncComposedMessageValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedAsyncComposedMessageValue()", program_source)
        self.assertIn("return ComposeForwardedAsyncComposedMessageValue();", program_source)
        self.assertIn("private static int ComposeAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeAsyncComposedMessageValue());", program_source)
        self.assertIn("private static int ComposeRelayedAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeRelayedAsyncComposedMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedRelayedAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedRelayedAsyncComposedMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedRelayedAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedRelayedAsyncComposedMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedAsyncComposedMessageValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedAsyncComposedMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedAsyncComposedMessageValue());", program_source)
        self.assertIn("private static string ComposeJoinAsyncDirectValue()", program_source)
        self.assertIn('return JoinAsync("corelib-reference-async-join:System.Private.CoreLib|System.Runtime", "|System.Console").GetAwaiter().GetResult();', program_source)
        self.assertIn("private static string ComposeRelayedJoinAsyncDirectValue()", program_source)
        self.assertIn('return RelayJoinAsync("corelib-reference-async-join:System.Private.CoreLib|System.Runtime", "|System.Console").GetAwaiter().GetResult();', program_source)
        self.assertIn("private static string ComposeForwardedRelayedJoinAsyncDirectValue()", program_source)
        self.assertIn("return ComposeRelayedJoinAsyncDirectValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedRelayedJoinAsyncDirectValue()", program_source)
        self.assertIn("return ComposeForwardedRelayedJoinAsyncDirectValue();", program_source)
        self.assertIn("private static string ComposeForwardedJoinAsyncDirectValue()", program_source)
        self.assertIn("return ComposeJoinAsyncDirectValue();", program_source)
        self.assertIn("private static string ComposeForwardedForwardedJoinAsyncDirectValue()", program_source)
        self.assertIn("return ComposeForwardedJoinAsyncDirectValue();", program_source)
        self.assertIn("private static int ComposeJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeJoinAsyncDirectValue());", program_source)
        self.assertIn("private static int ComposeRelayedJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeRelayedJoinAsyncDirectValue());", program_source)
        self.assertIn("private static int ComposeForwardedRelayedJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedRelayedJoinAsyncDirectValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedRelayedJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedRelayedJoinAsyncDirectValue());", program_source)
        self.assertIn("private static int ComposeForwardedJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedJoinAsyncDirectValue());", program_source)
        self.assertIn("private static int ComposeForwardedForwardedJoinAsyncDirectMessage()", program_source)
        self.assertIn("Console.WriteLine(ComposeForwardedForwardedJoinAsyncDirectValue());", program_source)
        self.assertIn("private static void ThrowExceptionNow()", program_source)
        self.assertIn('throw new InvalidOperationException("corelib-reference-exception-proof");', program_source)
        self.assertIn("private static string CaptureExceptionMessage()", program_source)
        self.assertIn("ThrowExceptionNow();", program_source)
        self.assertIn('return "corelib-reference-exception:System.Private.CoreLib|System.Console";', program_source)
        self.assertIn("catch (InvalidOperationException)", program_source)
        self.assertIn("private static int ComposeExceptionMessage()", program_source)
        self.assertIn("Console.WriteLine(CaptureExceptionMessage());", program_source)
        self.assertIn("private static class BoxingSink", program_source)
        self.assertIn("public static void Consume(object value)", program_source)
        self.assertIn("private sealed class ArrayBanner", program_source)
        self.assertIn('string.Concat("Array boxing native proof: ", _name)', program_source)
        self.assertIn("private static int ComposeArrayBoxingReferenceArray()", program_source)
        self.assertIn("BoxingSink.Consume(42);", program_source)
        self.assertIn("var banners = new ArrayBanner[1];", program_source)
        self.assertIn('banners[0] = new ArrayBanner("boxed int 42");', program_source)
        self.assertIn("Console.WriteLine(banners[0].BuildMessage());", program_source)
        self.assertIn("private sealed class ArrayCopyBanner", program_source)
        self.assertIn('string.Concat("Array copy native proof: ", _name)', program_source)
        self.assertIn("private static int ComposeArrayCopyReferenceArray()", program_source)
        self.assertIn("var source = new ArrayCopyBanner[2];", program_source)
        self.assertIn('source[1] = new ArrayCopyBanner("copied banner");', program_source)
        self.assertIn("var target = new ArrayCopyBanner[2];", program_source)
        self.assertIn("Array.Copy(source, 0, target, 0, 2);", program_source)
        self.assertIn("private static int ComposeArrayCopyLengthOnlyInt64ReferenceArray()", program_source)
        self.assertIn("Array.Copy(source, target, 2L);", program_source)
        self.assertIn("private static int ComposeArrayCopyInt64ReferenceArray()", program_source)
        self.assertIn("Array.Copy(source, 0L, target, 0L, 2L);", program_source)
        self.assertIn("private static int ComposeArrayConstrainedCopyReferenceArray()", program_source)
        self.assertIn("Array.ConstrainedCopy(source, 0, target, 0, 2);", program_source)
        self.assertIn("private static int ComposeArrayCopyToReferenceArray()", program_source)
        self.assertIn("var target = new ArrayCopyBanner[3];", program_source)
        self.assertIn("source.CopyTo(target, 1);", program_source)
        self.assertIn("private static int ComposeArrayCopyToInt64ReferenceArray()", program_source)
        self.assertIn("source.CopyTo(target, 1L);", program_source)
        self.assertIn("Console.WriteLine(target[2].BuildMessage());", program_source)
        self.assertIn("private sealed class ArrayReverseBanner", program_source)
        self.assertIn('string.Concat("Array reverse native proof: ", _name)', program_source)
        self.assertIn("private static int ComposeArrayReverseReferenceArray()", program_source)
        self.assertIn("var banners = new ArrayReverseBanner[3];", program_source)
        self.assertIn('banners[1] = new ArrayReverseBanner("reversed banner");', program_source)
        self.assertIn("Array.Reverse(banners, 1, 2);", program_source)
        self.assertIn("Console.WriteLine(banners[2].BuildMessage());", program_source)
        self.assertIn("private static int ComposeArrayReverseWholeReferenceArray()", program_source)
        self.assertIn("Array.Reverse(banners);", program_source)
        self.assertIn("Console.WriteLine(banners[1].BuildMessage());", program_source)
        self.assertIn("private static int ComposeArrayClearReferenceArray()", program_source)
        self.assertIn("var messages = new string[3];", program_source)
        self.assertIn('messages[1] = "cleared banner";', program_source)
        self.assertIn("Array.Clear(messages, 1, 2);", program_source)
        self.assertIn('Console.WriteLine(string.Concat("Array clear native proof: ", messages[1]));', program_source)
        self.assertIn("private static int ComposeArrayClearWholeReferenceArray()", program_source)
        self.assertIn("Array.Clear(messages);", program_source)
        self.assertIn("Console.WriteLine(target[1].BuildMessage());", program_source)
        self.assertIn('new Holder("System.Private.CoreLib").Render()', program_source)
        self.assertIn("Console.WriteLine(", program_source)

    def test_solution_core_pack_corelib_native_proof_program_contains_interface_dispatch_entry(self) -> None:
        program_source = CORELIB_NATIVE_PROOF_PROGRAM_PATH.read_text(encoding="utf-8")

        for required_fragment in [
            "internal interface IMessageBanner",
            "internal sealed class InterfaceDispatchBanner : IMessageBanner",
            "private static int ComposeInterfaceDispatchMessage()",
            'IMessageBanner banner = new InterfaceDispatchBanner("System.Private.CoreLib");',
            "Console.WriteLine(banner.Render());",
        ]:
            self.assertIn(required_fragment, program_source)

    def test_solution_core_pack_corelib_native_proof_program_contains_delegate_closed_target_relay_entry(self) -> None:
        program_source = CORELIB_NATIVE_PROOF_PROGRAM_PATH.read_text(encoding="utf-8")

        for required_fragment in [
            "internal delegate string CoreLibMessageFormatter(string prefix);",
            "internal delegate string CoreLibTailFormatter(string value);",
            "private sealed class DelegateRelayBanner",
            "public string BuildMessage(string prefix)",
            'return string.Concat(prefix, _name, ".");',
            "private static class DelegateRelayTail",
            "public static string AppendSuffix(string value)",
            'return string.Concat(value, "|System.Console");',
            "private static int ComposeDelegateClosedTargetRelayMessage()",
            'var banner = new DelegateRelayBanner("delegate packet");',
            "CoreLibMessageFormatter formatter = banner.BuildMessage;",
            "CoreLibTailFormatter tail = DelegateRelayTail.AppendSuffix;",
            'Console.WriteLine(tail(formatter("corelib-reference-delegate:System.Private.CoreLib|System.Runtime:")));',
        ]:
            self.assertIn(required_fragment, program_source)
