<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>PerformanceFeaturePack</AssemblyName>
    <RootNamespace>PerformanceFeaturePack</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/reference/Chaos.TestFramework/Chaos.TestFramework.csproj" />
  </ItemGroup>
</Project>
