<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SnapshotProverSubjects</AssemblyName>
    <RootNamespace>SnapshotProverSubjects</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="SnapshotProverSubjects.cs" />
    <Compile Include="GlobalUsings.cs" />
    <Compile Include="SnapshotProverSubjects.Custom.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../../tests/snapshots/Chaos.IL2CPP.CodeGen.SnapshotTests/FixtureAssembly/SnapshotTestFixtures.csproj" />
  </ItemGroup>
</Project>
