using System.Diagnostics;
using System.Text;
using System.Text.Json;

namespace Chaos.IL2CPP.Tools.AutoTestGenerator;

public sealed class ProbeEmitter
{
    private readonly CSharpSerializer _serializer;

    public ProbeEmitter(CSharpSerializer serializer)
    {
        _serializer = serializer;
    }

    public IReadOnlyList<ProbeResult> Probe(
        string outputDir,
        string assemblyName,
        string typeFullName,
        IReadOnlyList<MethodSignature> methods,
        IReadOnlyList<IReadOnlyList<ValueSet>> allValueSets)
    {
        var probeDir = Path.Combine(outputDir, ".probe");
        Directory.CreateDirectory(probeDir);

        var typeShortName = CSharpSerializer.MapToCSharpType(typeFullName);
        var probeSource = GenerateProbeSource(typeShortName, methods, allValueSets);
        File.WriteAllText(Path.Combine(probeDir, "Probe.cs"), probeSource);

        var probeCsproj = GenerateProbeCsproj();
        File.WriteAllText(Path.Combine(probeDir, "Probe.csproj"), probeCsproj);

        Console.Write("  Building probe... ");
        if (!RunDotnetBuild(probeDir, out var buildOk))
        {
            Console.WriteLine("FAILED");
            return Array.Empty<ProbeResult>();
        }
        Console.WriteLine("OK");

        Console.Write("  Run 1/2... ");
        var run1 = RunProbe(probeDir);
        Console.WriteLine($"{run1.Count} results");

        Console.Write("  Run 2/2... ");
        var run2 = RunProbe(probeDir);
        Console.WriteLine($"{run2.Count} results");

        return MergeResults(methods, allValueSets, run1, run2);
    }

    private string GenerateProbeSource(
        string typeShortName,
        IReadOnlyList<MethodSignature> methods,
        IReadOnlyList<IReadOnlyList<ValueSet>> allValueSets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated probe");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoGeneratedProbe;");
        sb.AppendLine();
        sb.AppendLine("public static class Probe");
        sb.AppendLine("{");
        sb.AppendLine("    public static void Main()");
        sb.AppendLine("    {");
        sb.AppendLine("        var results = new System.Collections.Generic.List<object>();");

        for (int mi = 0; mi < methods.Count; mi++)
        {
            var method = methods[mi];

            var instanceExpr = method.IsStatic ? typeShortName : $"default({typeShortName})!";

            sb.AppendLine($"        // --- {method.Name} ---");

            foreach (var set in allValueSets[mi])
            {
                // Generate variable declarations for out/ref params
                var prelude = new List<string>();
                var finalArgs = new List<string>();
                int refVarCounter = 0;

                for (int pi = 0; pi < method.Parameters.Count; pi++)
                {
                    var param = method.Parameters[pi];
                    var argExpr = set.ArgumentExpressions[pi];

                    if (param.IsOut || param.IsRef)
                    {
                        var baseTypeName = param.TypeName.EndsWith('&')
                            ? param.TypeName[..^1].Trim()
                            : param.TypeName;
                        var csType = CSharpSerializer.MapToCSharpType(baseTypeName);
                        if (csType == "string") csType = baseTypeName; // string is special

                        var varName = $"__ref_{mi}_{set.SetIndex}_{refVarCounter++}";
                        prelude.Add($"            {csType} {varName} = default({csType});");
                        finalArgs.Add(param.IsOut ? $"out {varName}" : $"ref {varName}");
                    }
                    else
                    {
                        // Add explicit cast for overload disambiguation
                        // e.g. (int)default(int) -> disambiguates Math.DivRem(int,int) vs Math.DivRem(short,short)
                        var csType = CSharpSerializer.MapToCSharpType(param.TypeName);
                        if (csType != "int" && !param.TypeName.Contains('.') && !param.TypeName.EndsWith('&'))
                        {
                            // It's a primitive type alias like byte, short — add explicit cast
                            finalArgs.Add($"{argExpr}");
                        }
                        else
                        {
                            finalArgs.Add($"{argExpr}");
                        }
                    }
                }

                // Join prelude
                var preludeStr = prelude.Count > 0
                    ? string.Join("\n", prelude) + "\n"
                    : "";

                var argsStr = string.Join(", ", finalArgs);
                var callExpr = $"{instanceExpr}.{method.Name}({argsStr})";

                sb.AppendLine("        try");
                sb.AppendLine("        {");
                if (preludeStr.Length > 0)
                    sb.Append(preludeStr);

                if (method.IsVoid)
                {
                    sb.AppendLine($"            {callExpr};");
                    sb.AppendLine("            results.Add(new { MethodIndex = " +
                                   $"{mi}, SetIndex = {set.SetIndex}, " +
                                   "HasException = false, ExceptionType = (string?)null, " +
                                   "ReturnValue = (long?)0 });");
                }
                else
                {
                    sb.AppendLine($"            var result = {callExpr};");
                    sb.AppendLine("            results.Add(new { MethodIndex = " +
                                   $"{mi}, SetIndex = {set.SetIndex}, " +
                                   "HasException = false, ExceptionType = (string?)null, " +
                                   "ReturnValue = ToLong(result) });");
                }
                sb.AppendLine("        }");
                sb.AppendLine("        catch (Exception ex)");
                sb.AppendLine("        {");
                sb.AppendLine("            results.Add(new { MethodIndex = " +
                               $"{mi}, SetIndex = {set.SetIndex}, " +
                               "HasException = true, ExceptionType = ex.GetType().FullName, " +
                               "ReturnValue = (long?)null });");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        var json = JsonSerializer.Serialize(results, new JsonSerializerOptions { WriteIndented = false });");
        sb.AppendLine("        Console.WriteLine(\"[PROBE_RESULT]\" + json);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static long ToLong(object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value == null) return 0;");
        sb.AppendLine("        if (value is int i) return i;");
        sb.AppendLine("        if (value is long l) return l;");
        sb.AppendLine("        if (value is short s) return s;");
        sb.AppendLine("        if (value is byte b) return b;");
        sb.AppendLine("        if (value is sbyte sb) return sb;");
        sb.AppendLine("        if (value is uint ui) return ui;");
        sb.AppendLine("        if (value is ulong ul) return (long)ul;");
        sb.AppendLine("        if (value is ushort us) return us;");
        sb.AppendLine("        if (value is char c) return c;");
        sb.AppendLine("        if (value is bool bl) return bl ? 1 : 0;");
        sb.AppendLine("        if (value is float f) return (long)f;");
        sb.AppendLine("        if (value is double d) return (long)d;");
        sb.AppendLine("        if (value is decimal dm) return (long)dm;");
        sb.AppendLine("        if (value is string str) return str.Length;");
        sb.AppendLine("        return value.GetHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateProbeCsproj()
    {
        return
            "<Project Sdk=\"Microsoft.NET.Sdk\">\n" +
            "  <PropertyGroup>\n" +
            "    <OutputType>Exe</OutputType>\n" +
            "    <TargetFramework>net8.0</TargetFramework>\n" +
            "    <ImplicitUsings>enable</ImplicitUsings>\n" +
            "    <Nullable>enable</Nullable>\n" +
            "  </PropertyGroup>\n" +
            "</Project>\n";
    }

    private bool RunDotnetBuild(string probeDir, out bool success)
    {
        success = false;
        try
        {
            var psi = new ProcessStartInfo("dotnet", $"build \"{probeDir}\" -nologo -v q")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            };
            using var process = Process.Start(psi);
            if (process is null) return false;

            var error = process.StandardError.ReadToEnd();
            process.WaitForExit(120_000);

            success = process.ExitCode == 0;
            if (!success)
            {
                // Print only first 500 chars of build errors
                var brief = error.Length > 500 ? error[..500] + "..." : error;
                Console.Error.WriteLine(brief);
            }
            return success;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[Probe] Build error: {ex.Message}");
            return false;
        }
    }

    private IReadOnlyList<ProbeRunResult> RunProbe(string probeDir)
    {
        var results = new List<ProbeRunResult>();
        try
        {
            var psi = new ProcessStartInfo("dotnet", $"run --project \"{probeDir}\" -nologo")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            };
            using var process = Process.Start(psi);
            if (process is null) return results;

            var output = process.StandardOutput.ReadToEnd();
            process.WaitForExit(60_000);

            foreach (var line in output.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            {
                var trimmed = line.Trim();
                if (trimmed.StartsWith("[PROBE_RESULT]"))
                {
                    var json = trimmed["[PROBE_RESULT]".Length..];
                    var parsed = JsonSerializer.Deserialize<List<ProbeEntry>>(json);
                    if (parsed is not null)
                    {
                        results.AddRange(parsed.Select((p, i) =>
                            new ProbeRunResult(i, p.MethodIndex, p.SetIndex,
                                p.HasException, p.ExceptionType, p.ReturnValue)));
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[Probe] Run error: {ex.Message}");
        }
        return results;
    }

    private static IReadOnlyList<ProbeResult> MergeResults(
        IReadOnlyList<MethodSignature> methods,
        IReadOnlyList<IReadOnlyList<ValueSet>> allValueSets,
        IReadOnlyList<ProbeRunResult> run1,
        IReadOnlyList<ProbeRunResult> run2)
    {
        var results = new List<ProbeResult>();
        var run1Lookup = run1.ToDictionary(r => (r.MethodIndex, r.SetIndex));
        var run2Lookup = run2.ToDictionary(r => (r.MethodIndex, r.SetIndex));

        for (int mi = 0; mi < methods.Count; mi++)
        {
            var method = methods[mi];
            var sets = allValueSets[mi];

            foreach (var set in sets)
            {
                var r1 = run1Lookup.GetValueOrDefault((mi, set.SetIndex));
                var r2 = run2Lookup.GetValueOrDefault((mi, set.SetIndex));

                if (r1 is null)
                {
                    results.Add(new ProbeResult(mi, set.SetIndex,
                        BuildSubjectId(method, set.SetIndex),
                        method.IsVoid, false, null, null, false));
                    continue;
                }

                var deterministic = r2 is not null &&
                    r1.HasException == r2.HasException &&
                    r1.ExceptionType == r2.ExceptionType &&
                    r1.ReturnValue == r2.ReturnValue;

                results.Add(new ProbeResult(mi, set.SetIndex,
                    BuildSubjectId(method, set.SetIndex),
                    method.IsVoid,
                    r1.HasException, r1.ExceptionType, r1.ReturnValue,
                    deterministic));
            }
        }

        return results;
    }

    internal static string BuildSubjectId(MethodSignature method, int setIndex)
    {
        var paramPart = string.Join(",",
            method.Parameters.Select(p => p.TypeName));
        var returnPart = method.IsVoid ? "System.Void" : method.ReturnTypeName;

        return $"{method.DeclaringTypeFullName}::{method.Name}:{returnPart}({paramPart})__Set{setIndex}";
    }

    private sealed record ProbeEntry(
        int MethodIndex, int SetIndex,
        bool HasException, string? ExceptionType, long? ReturnValue);

    private sealed record ProbeRunResult(
        int Index, int MethodIndex, int SetIndex,
        bool HasException, string? ExceptionType, long? ReturnValue);
}
