<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ThreadingTasksPrimitivesSubjects</AssemblyName>
    <RootNamespace>ThreadingTasksPrimitivesSubjects</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ThreadingTasksPrimitivesSubjects.cs" />
    <Compile Include="ThreadingTasksPrimitivesNativeEntry.Custom.cs" />
    <Compile Include="ThreadingTasksPrimitivesSubjects.Custom.cs" />
  </ItemGroup>
</Project>
