<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ErrorInfoBasicNativeEntry</AssemblyName>
    <RootNamespace>ErrorInfoBasicNativeEntry</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ErrorInfoBasicNativeEntry.cs" />
  </ItemGroup>
</Project>
