<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>GoldenCoreLibReference.HotUpdatePatch</AssemblyName>
    <RootNamespace>GoldenCoreLibReference.HotUpdatePatch</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.NETCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\src\reference\Chaos.TestFramework.Sdk\Chaos.TestFramework.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Extensions">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Runtime.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Console">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Console.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq">
      <HintPath>..\..\..\..\..\..\src\dll\dotnet-foundation\net8.0\ref\System.Linq.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
