// Auto-generated probe
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using Microsoft.Win32.SafeHandles;

namespace AutoGeneratedProbe;

public static class Probe
{
    public static unsafe void Main()
    {
        var results = new System.Collections.Generic.List<object>();
        // --- SetStatus ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetStatus(default(System.Diagnostics.ActivityStatusCode)!, default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 0, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 0, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetStatus(default(System.Diagnostics.ActivityStatusCode)!, "");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 0, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 0, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- GetBaggageItem ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetBaggageItem(default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 1, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 1, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetBaggageItem("");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 1, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 1, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- GetTagItem ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetTagItem(default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 2, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 2, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetTagItem("");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 2, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 2, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddTag ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddTag(default(string)!, default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 3, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 3, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddTag("", default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 3, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 3, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddTag(default(string)!, "");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 3, SetIndex = 2, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 3, SetIndex = 2, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddTag ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddTag(default(string)!, default(object)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 4, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 4, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddTag("", default(object)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 4, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 4, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetTag ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetTag(default(string)!, default(object)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 5, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 5, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetTag("", default(object)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 5, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 5, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddEvent ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddEvent(default(System.Diagnostics.ActivityEvent)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 6, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 6, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddException ---
        try
        {
            TagList __ref_7_0_0 = default(TagList);
            var result = default(global::System.Diagnostics.Activity)!.AddException(default(System.Exception)!, ref __ref_7_0_0, default(System.DateTimeOffset));
            var _outValues = new System.Collections.Generic.List<string>();
            _outValues.Add(System.Text.Json.JsonSerializer.Serialize(__ref_7_0_0));
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 7, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)_outValues });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 7, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddLink ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddLink(default(System.Diagnostics.ActivityLink)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 8, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 8, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- AddBaggage ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddBaggage(default(string)!, default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 9, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 9, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddBaggage("", default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 9, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 9, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.AddBaggage(default(string)!, "");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 9, SetIndex = 2, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 9, SetIndex = 2, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetBaggage ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetBaggage(default(string)!, default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 10, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 10, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetBaggage("", default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 10, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 10, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetBaggage(default(string)!, "");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 10, SetIndex = 2, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 10, SetIndex = 2, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetParentId ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetParentId(default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 11, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 11, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetParentId("");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 11, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 11, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetParentId ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetParentId(default(System.Diagnostics.ActivityTraceId)!, default(System.Diagnostics.ActivitySpanId)!, default(System.Diagnostics.ActivityTraceFlags)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 12, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 12, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetStartTime ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetStartTime(default(System.DateTime));
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 13, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 13, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetEndTime ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetEndTime(default(System.DateTime));
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 14, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 14, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- Stop ---
        try
        {
            default(global::System.Diagnostics.Activity)!.Stop();
            results.Add(new { MethodIndex = 15, SetIndex = 15, HasException = false, ExceptionType = (string?)null, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 15, SetIndex = 15, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetIdFormat ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.SetIdFormat(default(System.Diagnostics.ActivityIdFormat)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 16, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 16, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- SetCustomProperty ---
        try
        {
            default(global::System.Diagnostics.Activity)!.SetCustomProperty(default(string)!, default(object)!);
            results.Add(new { MethodIndex = 17, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 17, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            default(global::System.Diagnostics.Activity)!.SetCustomProperty("", default(object)!);
            results.Add(new { MethodIndex = 17, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 17, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        // --- GetCustomProperty ---
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetCustomProperty(default(string)!);
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 18, SetIndex = 0, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 18, SetIndex = 0, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        try
        {
            var result = default(global::System.Diagnostics.Activity)!.GetCustomProperty("");
            string _rvJson = System.Text.Json.JsonSerializer.Serialize(result);
            string _rvType = ((object)result)?.GetType().FullName ?? "";
            long _rvLong = ToLong(result);
            results.Add(new { MethodIndex = 18, SetIndex = 1, HasException = false, ExceptionType = (string?)null, ReturnValueJson = _rvJson, ReturnValueType = _rvType, ReturnValue = (long?)_rvLong, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }
        catch (Exception ex)
        {
            results.Add(new { MethodIndex = 18, SetIndex = 1, HasException = true, ExceptionType = ex.GetType().FullName, ReturnValueJson = (string?)null, ReturnValueType = (string?)null, ReturnValue = (long?)null, OutRefValues = (System.Collections.Generic.List<string>?)null });
        }

        var json = System.Text.Json.JsonSerializer.Serialize(results, new JsonSerializerOptions { WriteIndented = false });
        Console.WriteLine("[PROBE_RESULT]" + json);
    }

    private static long ToLong(object value)
    {
        if (value == null) return 0;
        if (value is int i) return i;
        if (value is long l) return l;
        if (value is short s) return s;
        if (value is byte b) return b;
        if (value is sbyte sb) return sb;
        if (value is uint ui) return ui;
        if (value is ulong ul) return (long)ul;
        if (value is ushort us) return us;
        if (value is char c) return c;
        if (value is bool bl) return bl ? 1 : 0;
        if (value is float f) return (long)f;
        if (value is double d) return (long)d;
        if (value is decimal dm) return (long)dm;
        if (value is string str) return str.Length;
        return value.GetHashCode();
    }
}
