<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CollectionsGenericCoreNativeEntry</AssemblyName>
    <RootNamespace>CollectionsGenericCoreNativeEntry</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CollectionsGenericCoreNativeEntry.cs" />
  </ItemGroup>
</Project>
