// Auto-generated type declarations (TU paging)
#pragma once

#include <chaos/native_types.h>
#include <chaos/type_info.h>  // MethodTable, TypeInfoV0 (complete type)
#include "generated_code_compat.h"  // PureTypeHeader for delegate type definitions
#include "ChaosGeneratedRuntimePrelude.h"  // chaos_managed_array for array-compat checks

typedef CHAOS_IL2CPP_INT32 chaos_valuetype_Chaos_TestFramework_Sdk___0;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_AssemblyFileHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_AssemblyReferenceHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_BlobHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ConstantHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_CustomAttributeHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_CustomDebugInformationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_DocumentHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_DocumentNameBlobHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_EntityHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_EventDefinitionHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ExportedTypeHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_FieldDefinitionHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_GenericParameterConstraintHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_GenericParameterHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_GuidHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_Handle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ImportScopeHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_InterfaceImplementationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_LocalConstantHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_LocalScopeHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_LocalVariableHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ManifestResourceHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_MemberReferenceHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_MethodDebugInformationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_MethodDefinitionHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_MethodImplementationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_MethodSpecificationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ModuleReferenceHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_ParameterHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_PropertyDefinitionHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_StandaloneSignatureHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_StringHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_TypeDefinitionHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_TypeReferenceHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_TypeSpecificationHandle;
typedef CHAOS_IL2CPP_INT32 chaos_valuetype_System_Reflection_Metadata_UserStringHandle;

struct chaos_type_Chaos_TestFramework_Sdk___0
{
    ThinLockableHeader header{};
};

struct chaos_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert
{
    ThinLockableHeader header{};
};

struct chaos_type_System_Private_CoreLib_System_Exception
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR _message = 0;
    CHAOS_IL2CPP_INTPTR _innerException = 0;
    CHAOS_IL2CPP_INTPTR _stackTrace = 0;
    CHAOS_IL2CPP_INT32 _HResult = 0;
};

struct chaos_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException : public chaos_type_System_Private_CoreLib_System_Exception
{
};

struct chaos_type_System_Private_CoreLib_System_Object
{
    ThinLockableHeader header{};
};

struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Delegate : public chaos_type_System_Private_CoreLib_System_Object
{
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};

struct chaos_type_System_Private_CoreLib_System_MulticastDelegate : public chaos_type_System_Private_CoreLib_System_Delegate
{
};

struct chaos_type_System_Private_CoreLib_System_Byte
{
    ThinLockableHeader header{};
};

struct chaos_type_System_Private_CoreLib_System_Collections_IEnumerable
{
    ThinLockableHeader header{};
};

struct chaos_type_System_Private_CoreLib_System_IDisposable
{
    ThinLockableHeader header{};
};

struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR runtime_assembly_name_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase
{
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo : public chaos_type_System_Private_CoreLib_System_Reflection_MethodBase
{
    CHAOS_IL2CPP_INTPTR declaring_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_definition_method_handle = 0;
    CHAOS_IL2CPP_INTPTR generic_argument_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Private_CoreLib_System_String
{
    ThinLockableHeader header{};
    CHAOS_IL2CPP_INTPTR length = 0;
    const char* utf8_data = nullptr;
    CHAOS_IL2CPP_UINT64 string_id = 0u;  // stable StringId, 0 = not yet materialized
};

struct chaos_type_System_Private_CoreLib_System_Type : public chaos_type_System_Private_CoreLib_System_Object
{
    CHAOS_IL2CPP_INTPTR runtime_type_handle = 0;
    CHAOS_IL2CPP_INTPTR runtime_name_value = 0;
    CHAOS_IL2CPP_INT32 runtime_metadata_token_value = 0;
};

struct chaos_type_System_Reflection_Metadata_AssemblyFileHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_AssemblyReferenceHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_BlobHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ConstantHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_CustomAttributeHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_CustomDebugInformationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_DocumentHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_DocumentNameBlobHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_EntityHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_EventDefinitionHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ExportedTypeHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_FieldDefinitionHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_GenericParameterConstraintHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_GenericParameterHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_GuidHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_Handle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ImportScopeHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_InterfaceImplementationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_LocalConstantHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_LocalScopeHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_LocalVariableHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ManifestResourceHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_MemberReferenceHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_MethodDebugInformationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_MethodDefinitionHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_MethodImplementationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_MethodSpecificationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ModuleReferenceHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_ParameterHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_PropertyDefinitionHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_StandaloneSignatureHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_StringHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_TypeDefinitionHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_TypeReferenceHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_TypeSpecificationHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_System_Reflection_Metadata_UserStringHandle : public chaos_type_System_Private_CoreLib_System_Object
{
};

struct chaos_type_Chaos_TestFramework_Sdk___0;
struct chaos_boxed_type_Chaos_TestFramework_Sdk___0 {
    PureTypeHeader header{};
    chaos_valuetype_Chaos_TestFramework_Sdk___0 value{};
};
struct chaos_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert;
struct chaos_boxed_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert;
struct chaos_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException;
struct chaos_boxed_type_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException;
struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c;
struct chaos_boxed_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c;
struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c;
struct chaos_boxed_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c;
struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c;
struct chaos_boxed_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c;
struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c;
struct chaos_boxed_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c;
struct chaos_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c;
struct chaos_boxed_type_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c;
struct chaos_type_System_Private_CoreLib_System_Action {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ArrayShapeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ArrayShapeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeNamedArgumentsEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeNamedArgumentsEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_FixedArgumentsEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_FixedArgumentsEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_LiteralEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_LiteralEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NameEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NameEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NamedArgumentTypeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NamedArgumentTypeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ParametersEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ParametersEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ReturnTypeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ReturnTypeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ScalarEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ScalarEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder_;
struct chaos_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_VectorEncoder_ {
    PureTypeHeader header{};
    CHAOS_IL2CPP_INTPTR chaos_delegate_target = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_method_ptr = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_list = 0;
    CHAOS_IL2CPP_INTPTR chaos_delegate_invocation_count = 0;
    CHAOS_IL2CPP_UINT32 chaos_delegate_method_token = 0;
    CHAOS_IL2CPP_UINT32 _pad = 0;
};
struct chaos_boxed_type_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_VectorEncoder_;
struct chaos_type_System_Private_CoreLib_System_Byte;
struct chaos_boxed_type_System_Private_CoreLib_System_Byte;
struct chaos_type_System_Private_CoreLib_System_Collections_IEnumerable;
struct chaos_boxed_type_System_Private_CoreLib_System_Collections_IEnumerable;
struct chaos_type_System_Private_CoreLib_System_Delegate;
struct chaos_boxed_type_System_Private_CoreLib_System_Delegate;
struct chaos_type_System_Private_CoreLib_System_Exception;
struct chaos_boxed_type_System_Private_CoreLib_System_Exception;
struct chaos_type_System_Private_CoreLib_System_IDisposable;
struct chaos_boxed_type_System_Private_CoreLib_System_IDisposable;
struct chaos_type_System_Private_CoreLib_System_MulticastDelegate;
struct chaos_boxed_type_System_Private_CoreLib_System_MulticastDelegate;
struct chaos_type_System_Private_CoreLib_System_Object;
struct chaos_boxed_type_System_Private_CoreLib_System_Object;
struct chaos_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_Assembly;
struct chaos_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_AssemblyName;
struct chaos_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_ConstructorInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_FieldInfo;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodBase;
struct chaos_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_boxed_type_System_Private_CoreLib_System_Reflection_MethodInfo;
struct chaos_type_System_Private_CoreLib_System_String;
struct chaos_boxed_type_System_Private_CoreLib_System_String;
struct chaos_type_System_Private_CoreLib_System_Type;
struct chaos_boxed_type_System_Private_CoreLib_System_Type;
struct chaos_type_System_Reflection_Metadata_AssemblyFileHandle;
struct chaos_boxed_type_System_Reflection_Metadata_AssemblyFileHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_AssemblyFileHandle value{};
};
struct chaos_type_System_Reflection_Metadata_AssemblyReferenceHandle;
struct chaos_boxed_type_System_Reflection_Metadata_AssemblyReferenceHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_AssemblyReferenceHandle value{};
};
struct chaos_type_System_Reflection_Metadata_BlobHandle;
struct chaos_boxed_type_System_Reflection_Metadata_BlobHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_BlobHandle value{};
};
struct chaos_type_System_Reflection_Metadata_ConstantHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ConstantHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ConstantHandle value{};
};
struct chaos_type_System_Reflection_Metadata_CustomAttributeHandle;
struct chaos_boxed_type_System_Reflection_Metadata_CustomAttributeHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_CustomAttributeHandle value{};
};
struct chaos_type_System_Reflection_Metadata_CustomDebugInformationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_CustomDebugInformationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_CustomDebugInformationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle;
struct chaos_boxed_type_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle value{};
};
struct chaos_type_System_Reflection_Metadata_DocumentHandle;
struct chaos_boxed_type_System_Reflection_Metadata_DocumentHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_DocumentHandle value{};
};
struct chaos_type_System_Reflection_Metadata_DocumentNameBlobHandle;
struct chaos_boxed_type_System_Reflection_Metadata_DocumentNameBlobHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_DocumentNameBlobHandle value{};
};
struct chaos_type_System_Reflection_Metadata_EntityHandle;
struct chaos_boxed_type_System_Reflection_Metadata_EntityHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_EntityHandle value{};
};
struct chaos_type_System_Reflection_Metadata_EventDefinitionHandle;
struct chaos_boxed_type_System_Reflection_Metadata_EventDefinitionHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_EventDefinitionHandle value{};
};
struct chaos_type_System_Reflection_Metadata_ExportedTypeHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ExportedTypeHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ExportedTypeHandle value{};
};
struct chaos_type_System_Reflection_Metadata_FieldDefinitionHandle;
struct chaos_boxed_type_System_Reflection_Metadata_FieldDefinitionHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_FieldDefinitionHandle value{};
};
struct chaos_type_System_Reflection_Metadata_GenericParameterConstraintHandle;
struct chaos_boxed_type_System_Reflection_Metadata_GenericParameterConstraintHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_GenericParameterConstraintHandle value{};
};
struct chaos_type_System_Reflection_Metadata_GenericParameterHandle;
struct chaos_boxed_type_System_Reflection_Metadata_GenericParameterHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_GenericParameterHandle value{};
};
struct chaos_type_System_Reflection_Metadata_GuidHandle;
struct chaos_boxed_type_System_Reflection_Metadata_GuidHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_GuidHandle value{};
};
struct chaos_type_System_Reflection_Metadata_Handle;
struct chaos_boxed_type_System_Reflection_Metadata_Handle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_Handle value{};
};
struct chaos_type_System_Reflection_Metadata_ImportScopeHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ImportScopeHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ImportScopeHandle value{};
};
struct chaos_type_System_Reflection_Metadata_InterfaceImplementationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_InterfaceImplementationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_InterfaceImplementationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_LocalConstantHandle;
struct chaos_boxed_type_System_Reflection_Metadata_LocalConstantHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_LocalConstantHandle value{};
};
struct chaos_type_System_Reflection_Metadata_LocalScopeHandle;
struct chaos_boxed_type_System_Reflection_Metadata_LocalScopeHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_LocalScopeHandle value{};
};
struct chaos_type_System_Reflection_Metadata_LocalVariableHandle;
struct chaos_boxed_type_System_Reflection_Metadata_LocalVariableHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_LocalVariableHandle value{};
};
struct chaos_type_System_Reflection_Metadata_ManifestResourceHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ManifestResourceHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ManifestResourceHandle value{};
};
struct chaos_type_System_Reflection_Metadata_MemberReferenceHandle;
struct chaos_boxed_type_System_Reflection_Metadata_MemberReferenceHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_MemberReferenceHandle value{};
};
struct chaos_type_System_Reflection_Metadata_MethodDebugInformationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_MethodDebugInformationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_MethodDebugInformationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_MethodDefinitionHandle;
struct chaos_boxed_type_System_Reflection_Metadata_MethodDefinitionHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_MethodDefinitionHandle value{};
};
struct chaos_type_System_Reflection_Metadata_MethodImplementationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_MethodImplementationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_MethodImplementationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_MethodSpecificationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_MethodSpecificationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_MethodSpecificationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_ModuleReferenceHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ModuleReferenceHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ModuleReferenceHandle value{};
};
struct chaos_type_System_Reflection_Metadata_ParameterHandle;
struct chaos_boxed_type_System_Reflection_Metadata_ParameterHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_ParameterHandle value{};
};
struct chaos_type_System_Reflection_Metadata_PropertyDefinitionHandle;
struct chaos_boxed_type_System_Reflection_Metadata_PropertyDefinitionHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_PropertyDefinitionHandle value{};
};
struct chaos_type_System_Reflection_Metadata_StandaloneSignatureHandle;
struct chaos_boxed_type_System_Reflection_Metadata_StandaloneSignatureHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_StandaloneSignatureHandle value{};
};
struct chaos_type_System_Reflection_Metadata_StringHandle;
struct chaos_boxed_type_System_Reflection_Metadata_StringHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_StringHandle value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder;
struct chaos_boxed_type_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder value{};
};
struct chaos_type_System_Reflection_Metadata_TypeDefinitionHandle;
struct chaos_boxed_type_System_Reflection_Metadata_TypeDefinitionHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_TypeDefinitionHandle value{};
};
struct chaos_type_System_Reflection_Metadata_TypeReferenceHandle;
struct chaos_boxed_type_System_Reflection_Metadata_TypeReferenceHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_TypeReferenceHandle value{};
};
struct chaos_type_System_Reflection_Metadata_TypeSpecificationHandle;
struct chaos_boxed_type_System_Reflection_Metadata_TypeSpecificationHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_TypeSpecificationHandle value{};
};
struct chaos_type_System_Reflection_Metadata_UserStringHandle;
struct chaos_boxed_type_System_Reflection_Metadata_UserStringHandle {
    PureTypeHeader header{};
    chaos_valuetype_System_Reflection_Metadata_UserStringHandle value{};
};

struct HotpatchEntryV0;
extern "C" HotpatchEntryV0 s_hotpatch_entries[];

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern MethodTable chaos_mt_Chaos_TestFramework_Sdk___0;
extern MethodTable chaos_mt_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert;
extern MethodTable chaos_mt_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException;
extern MethodTable chaos_mt_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c;
extern MethodTable chaos_mt_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c;
extern MethodTable chaos_mt_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c;
extern MethodTable chaos_mt_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c;
extern MethodTable chaos_mt_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ArrayShapeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeNamedArgumentsEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_FixedArgumentsEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_LiteralEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NameEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NamedArgumentTypeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ParametersEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ReturnTypeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ScalarEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_VectorEncoder_;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Byte;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Collections_IEnumerable;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Delegate;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Exception;
extern MethodTable chaos_mt_System_Private_CoreLib_System_IDisposable;
extern MethodTable chaos_mt_System_Private_CoreLib_System_MulticastDelegate;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Object;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_Assembly;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_AssemblyName;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_FieldInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodBase;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Reflection_MethodInfo;
extern MethodTable chaos_mt_System_Private_CoreLib_System_String;
extern MethodTable chaos_mt_System_Private_CoreLib_System_Type;
extern MethodTable chaos_mt_System_Reflection_Metadata_AssemblyFileHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_AssemblyReferenceHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_BlobHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ConstantHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_CustomAttributeHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_CustomDebugInformationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_DocumentHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_DocumentNameBlobHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_EntityHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_EventDefinitionHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ExportedTypeHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_FieldDefinitionHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_GenericParameterConstraintHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_GenericParameterHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_GuidHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_Handle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ImportScopeHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_InterfaceImplementationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_LocalConstantHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_LocalScopeHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_LocalVariableHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ManifestResourceHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_MemberReferenceHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_MethodDebugInformationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_MethodDefinitionHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_MethodImplementationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_MethodSpecificationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ModuleReferenceHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_ParameterHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_PropertyDefinitionHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_StandaloneSignatureHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_StringHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder;
extern MethodTable chaos_mt_System_Reflection_Metadata_TypeDefinitionHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_TypeReferenceHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_TypeSpecificationHandle;
extern MethodTable chaos_mt_System_Reflection_Metadata_UserStringHandle;

extern const void* chaos_vtable_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException[];
extern const void* chaos_vtable_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c[];
extern const void* chaos_vtable_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c[];
extern const void* chaos_vtable_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c[];
extern const void* chaos_vtable_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c[];
extern const void* chaos_vtable_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c[];

extern CHAOS_IL2CPP_INT32 chaos_static_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert__s_exitCode;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c____9;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c____9__20_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c____9__20_1;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c____9;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c____9__4_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c____9__4_1;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c____9__9_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c____9__9_1;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c____9;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c____9__4_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c____9__4_1;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c____9;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c____9__4_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c____9__4_1;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c____9__4_2;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c____9;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c____9__20_0;
extern CHAOS_IL2CPP_INTPTR chaos_static_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c____9__20_1;

extern const uint64_t chaos_type_id_Chaos_TestFramework_Sdk___0;
extern const uint64_t chaos_type_id_Chaos_TestFramework_Sdk_Chaos_TestFramework_Assert;
extern const uint64_t chaos_type_id_Chaos_TestFramework_Sdk_Chaos_TestFramework_AssertionException;
extern const uint64_t chaos_type_id_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_BlobEncoderTests___c;
extern const uint64_t chaos_type_id_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoderTests___c;
extern const uint64_t chaos_type_id_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoderTests___c;
extern const uint64_t chaos_type_id_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoderTests___c;
extern const uint64_t chaos_type_id_CombinedSubjects_AutoGenerated_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoderTests___c;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ArrayShapeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_CustomAttributeNamedArgumentsEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_FixedArgumentsEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_LiteralEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NameEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_NamedArgumentTypeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ParametersEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ReturnTypeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_ScalarEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Action_System_Reflection_Metadata_Ecma335_VectorEncoder_;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Byte;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Collections_IEnumerable;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Delegate;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Exception;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_IDisposable;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_MulticastDelegate;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Object;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_Assembly;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_AssemblyName;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_ConstructorInfo;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_FieldInfo;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_MethodBase;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Reflection_MethodInfo;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_String;
extern const uint64_t chaos_type_id_System_Private_CoreLib_System_Type;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_AssemblyFileHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_AssemblyReferenceHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_BlobHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ConstantHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_CustomAttributeHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_CustomDebugInformationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_DeclarativeSecurityAttributeHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_DocumentHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_DocumentNameBlobHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_EntityHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_EventDefinitionHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ExportedTypeHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_FieldDefinitionHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_GenericParameterConstraintHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_GenericParameterHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_GuidHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_Handle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ImportScopeHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_InterfaceImplementationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_LocalConstantHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_LocalScopeHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_LocalVariableHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ManifestResourceHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_MemberReferenceHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_MethodDebugInformationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_MethodDefinitionHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_MethodImplementationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_MethodSpecificationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ModuleReferenceHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_ParameterHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_PropertyDefinitionHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_StandaloneSignatureHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_StringHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeArrayTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomAttributeElementTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_CustomModifiersEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_FieldTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_GenericTypeArgumentsEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LiteralEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariableTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_LocalVariablesEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_MethodSignatureEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_NamedArgumentsEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ParameterTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_PermissionSetEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_ScalarEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_SignatureTypeEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_System_Reflection_Metadata_Ecma335_VectorEncoder;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_TypeDefinitionHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_TypeReferenceHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_TypeSpecificationHandle;
extern const uint64_t chaos_type_id_System_Reflection_Metadata_UserStringHandle;

CHAOS_IL2CPP_INTPTR chaos_string_materialize(CHAOS_IL2CPP_INTPTR chaos_value) noexcept;

bool chaos_is_array_store_compatible(const chaos_managed_array* chaos_array, CHAOS_IL2CPP_INTPTR chaos_value) noexcept;

void chaos_default_interpolated_string_handler_reset(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_literal_length, CHAOS_IL2CPP_INT32 chaos_trailing_count);
void chaos_default_interpolated_string_handler_append_string(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INTPTR chaos_string_value);
void chaos_default_interpolated_string_handler_append_int32(CHAOS_IL2CPP_INTPTR chaos_handler_ref, CHAOS_IL2CPP_INT32 chaos_value);
CHAOS_IL2CPP_INTPTR chaos_default_interpolated_string_handler_to_string_and_clear(CHAOS_IL2CPP_INTPTR chaos_handler_ref);

} // namespace chaos::il2cpp::codegen::CombinedSubjects

extern "C" void* kChaosExternalRuntimeFnTable[];

namespace chaos::il2cpp::codegen::CombinedSubjects
{
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Console_System_Console__get_Error_System_IO_TextWriter__(void) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Array__Empty_System_Byte__System_Byte____() noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_Exception___ctor_System_Void_System_String_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1) noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_IO_TextWriter__WriteLine_System_Void_System_String_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Object__Equals_System_Boolean_System_Object_System_Object_(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0, CHAOS_IL2CPP_INTPTR chaos_fn_arg_1) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_Object__ToString_System_String__(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) noexcept;
extern void chaos_external_runtime_System_Private_CoreLib_System_Object___ctor_System_Void__(CHAOS_IL2CPP_INTPTR chaos_fn_arg_0) noexcept;
extern CHAOS_IL2CPP_INTPTR chaos_external_runtime_System_Private_CoreLib_System_String__Concat_System_String_System_String_System_String_(CHAOS_IL2CPP_INTPTR chaos_arg_0, CHAOS_IL2CPP_INTPTR chaos_arg_1) noexcept;

} // namespace chaos::il2cpp::codegen::CombinedSubjects

void ChaosReflectionSetExceptionMetadata_2params(CHAOS_IL2CPP_INTPTR chaos_exception, CHAOS_IL2CPP_INTPTR chaos_message, CHAOS_IL2CPP_INTPTR chaos_param_name);

