// Auto-generated patch subjects for hotupdate verification
// Each method matches baseline [HotUpdate] subject signature,
// but returns a transformed value for semantic change detection.
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Chaos.TestFramework;
using System.Security.Cryptography;

namespace AutoGenerated.Patch
{
    public sealed unsafe class System_Security_CryptographyPatchSubjects
    {

        public long Subject_0_CreateSelfSigned_0_System_DateTimeOffset_System_DateTimeOffset_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRequest)!.CreateSelfSigned(default(System.DateTimeOffset), default(System.DateTimeOffset));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_1_CreateSigningRequest_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRequest)!.CreateSigningRequest();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_2_CreateSigningRequest_2_X509SignatureGenerator_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRequest)!.CreateSigningRequest(default(System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_3_CreateSigningRequestPem_3__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRequest)!.CreateSigningRequestPem();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_4_CreateSigningRequestPem_4_X509SignatureGenerator_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRequest)!.CreateSigningRequestPem(default(System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_5_LoadSigningRequest_5_System_Byte___HashAlgorithmName_CertificateRequestLoadOptions_RSASignaturePadding_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRequest.LoadSigningRequest(default(System.Byte[])!, default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.CertificateRequestLoadOptions)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_6_LoadSigningRequest_5_System_Byte___HashAlgorithmName_CertificateRequestLoadOptions_RSASignaturePadding_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRequest.LoadSigningRequest(System.Array.Empty<byte>(), default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.CertificateRequestLoadOptions)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_7_LoadSigningRequest_5_System_Byte___HashAlgorithmName_CertificateRequestLoadOptions_RSASignaturePadding_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRequest.LoadSigningRequest(new byte[2] { default(byte)!, default(byte)! }, default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.CertificateRequestLoadOptions)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_8_LoadSigningRequestPem_6_string_HashAlgorithmName_CertificateRequestLoadOptions_RSASignaturePadding_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRequest.LoadSigningRequestPem(default(string)!, default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.CertificateRequestLoadOptions)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_9_LoadSigningRequestPem_6_string_HashAlgorithmName_CertificateRequestLoadOptions_RSASignaturePadding_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRequest.LoadSigningRequestPem("", default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.CertificateRequestLoadOptions)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_10_Build_2_X500DistinguishedName_X509SignatureGenerator_BigInteger_System_DateTimeOffset_HashAlgorithmName_X509AuthorityKeyIdentifierExtension_System_Nullable_System_DateTimeOffset__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.Build(default(System.Security.Cryptography.X509Certificates.X500DistinguishedName)!, default(System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!, default(System.Numerics.BigInteger)!, default(System.DateTimeOffset), default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension)!, default(System.Nullable<System.DateTimeOffset>));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_11_Build_2_X500DistinguishedName_X509SignatureGenerator_BigInteger_System_DateTimeOffset_HashAlgorithmName_X509AuthorityKeyIdentifierExtension_System_Nullable_System_DateTimeOffset__1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.Build(default(System.Security.Cryptography.X509Certificates.X500DistinguishedName)!, default(System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!, default(System.Numerics.BigInteger), default(System.DateTimeOffset), default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension)!, default(System.Nullable<System.DateTimeOffset>));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_12_Build_3_X509Certificate2_BigInteger_System_DateTimeOffset_HashAlgorithmName_RSASignaturePadding_System_Nullable_System_DateTimeOffset__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.Build(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(System.Numerics.BigInteger)!, default(System.DateTimeOffset), default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.RSASignaturePadding)!, default(System.Nullable<System.DateTimeOffset>));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_13_Build_3_X509Certificate2_BigInteger_System_DateTimeOffset_HashAlgorithmName_RSASignaturePadding_System_Nullable_System_DateTimeOffset__1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.Build(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(System.Numerics.BigInteger), default(System.DateTimeOffset), default(System.Security.Cryptography.HashAlgorithmName)!, default(System.Security.Cryptography.RSASignaturePadding)!, default(System.Nullable<System.DateTimeOffset>));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_14_BuildCrlDistributionPointExtension_4_IEnumerable_string__bool_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.BuildCrlDistributionPointExtension(default(System.Collections.Generic.IEnumerable<System.String>)!, default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_15_BuildCrlDistributionPointExtension_4_IEnumerable_string__bool_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.BuildCrlDistributionPointExtension(default(System.Collections.Generic.IEnumerable<System.String>)!, false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_16_BuildCrlDistributionPointExtension_4_IEnumerable_string__bool_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.BuildCrlDistributionPointExtension(System.Linq.Enumerable.Empty<string>(), default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_17_Load_5_System_Byte___BigInteger_0()
        {
            System.Numerics.BigInteger __ref_5_0_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.Load(default(System.Byte[])!, out __ref_5_0_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_5_0_0) != null ? 1L : 0L);
        }

        public long Subject_18_Load_5_System_Byte___BigInteger_1()
        {
            System.Numerics.BigInteger __ref_5_1_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.Load(default(System.Byte[])!, out __ref_5_1_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_5_1_0) != null ? 1L : 0L);
        }

        public long Subject_19_Load_5_System_Byte___BigInteger_2()
        {
            System.Numerics.BigInteger __ref_5_2_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.Load(System.Array.Empty<byte>(), out __ref_5_2_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_5_2_0) != null ? 1L : 0L);
        }

        public long Subject_20_Load_5_System_Byte___BigInteger_3()
        {
            System.Numerics.BigInteger __ref_5_3_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.Load(new byte[2] { default(byte)!, default(byte)! }, out __ref_5_3_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_5_3_0) != null ? 1L : 0L);
        }

        public long Subject_21_LoadPem_6_string_BigInteger_0()
        {
            System.Numerics.BigInteger __ref_6_0_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.LoadPem(default(string)!, out __ref_6_0_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_6_0_0) != null ? 1L : 0L);
        }

        public long Subject_22_LoadPem_6_string_BigInteger_1()
        {
            System.Numerics.BigInteger __ref_6_1_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.LoadPem("", out __ref_6_1_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_6_1_0) != null ? 1L : 0L);
        }

        public long Subject_23_LoadPem_6_string_BigInteger_2()
        {
            System.Numerics.BigInteger __ref_6_2_0 = default;
            var result = global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder.LoadPem(default(string)!, out __ref_6_2_0);
            return ((object)(result) != null ? 0L : 1L) ^ ((object)(__ref_6_2_0) != null ? 1L : 0L);
        }

        public long Subject_24_RemoveEntry_7_System_Byte___0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.RemoveEntry(default(System.Byte[])!);
            return result ? 0L : 1L;
        }

        public long Subject_25_RemoveEntry_7_System_Byte___1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.RemoveEntry(System.Array.Empty<byte>());
            return result ? 0L : 1L;
        }

        public long Subject_26_RemoveEntry_7_System_Byte___2()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.CertificateRevocationListBuilder)!.RemoveEntry(new byte[2] { default(byte)!, default(byte)! });
            return result ? 0L : 1L;
        }

        public long Subject_27_CopyWithPrivateKey_0_X509Certificate2_DSA_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.DSACertificateExtensions.CopyWithPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(System.Security.Cryptography.DSA)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_28_GetDSAPrivateKey_1_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.DSACertificateExtensions.GetDSAPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_29_GetDSAPublicKey_2_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.DSACertificateExtensions.GetDSAPublicKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_30_CopyWithPrivateKey_0_X509Certificate2_ECDsa_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(System.Security.Cryptography.ECDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_31_GetECDsaPrivateKey_1_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.GetECDsaPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_32_GetECDsaPublicKey_2_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.GetECDsaPublicKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_33_ExportSubjectPublicKeyInfo_0__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.ExportSubjectPublicKeyInfo();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_34_GetCompositeMLDsaPublicKey_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetCompositeMLDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_35_GetDSAPublicKey_2__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetDSAPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_36_GetECDiffieHellmanPublicKey_3__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetECDiffieHellmanPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_37_GetECDsaPublicKey_4__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetECDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_38_GetMLDsaPublicKey_5__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetMLDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_39_GetMLKemPublicKey_6__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetMLKemPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_40_GetRSAPublicKey_7__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetRSAPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_41_GetSlhDsaPublicKey_8__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.PublicKey)!.GetSlhDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_42_CopyWithPrivateKey_0_X509Certificate2_RSA_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(System.Security.Cryptography.RSA)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_43_GetRSAPrivateKey_1_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_44_GetRSAPublicKey_2_X509Certificate2_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPublicKey(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_45_Build_5_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder)!.Build(default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_46_Build_5_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder)!.Build(false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_47_Decode_0_X500DistinguishedNameFlags_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedName)!.Decode(default(System.Security.Cryptography.X509Certificates.X500DistinguishedNameFlags)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_48_EnumerateRelativeDistinguishedNames_1_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedName)!.EnumerateRelativeDistinguishedNames(default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_49_EnumerateRelativeDistinguishedNames_1_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedName)!.EnumerateRelativeDistinguishedNames(false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_50_Format_2_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedName)!.Format(default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_51_Format_2_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedName)!.Format(false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_52_Build_10__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500DistinguishedNameBuilder)!.Build();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_53_GetSingleElementType_0__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500RelativeDistinguishedName)!.GetSingleElementType();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_54_GetSingleElementValue_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X500RelativeDistinguishedName)!.GetSingleElementValue();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_55_EnumerateCAIssuersUris_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509AuthorityInformationAccessExtension)!.EnumerateCAIssuersUris();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_56_EnumerateOcspUris_2__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509AuthorityInformationAccessExtension)!.EnumerateOcspUris();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_57_EnumerateUris_3_Oid_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509AuthorityInformationAccessExtension)!.EnumerateUris(default(System.Security.Cryptography.Oid)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_58_EnumerateUris_4_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509AuthorityInformationAccessExtension)!.EnumerateUris(default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_59_EnumerateUris_4_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509AuthorityInformationAccessExtension)!.EnumerateUris("");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_60_CreateFromCertificate_1_X509Certificate2_bool_bool_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromCertificate(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(bool), default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_61_CreateFromCertificate_1_X509Certificate2_bool_bool_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromCertificate(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, false, default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_62_CreateFromCertificate_1_X509Certificate2_bool_bool_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromCertificate(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!, default(bool), false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_63_CreateFromIssuerNameAndSerialNumber_2_X500DistinguishedName_System_Byte___0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromIssuerNameAndSerialNumber(default(System.Security.Cryptography.X509Certificates.X500DistinguishedName)!, default(System.Byte[])!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_64_CreateFromIssuerNameAndSerialNumber_2_X500DistinguishedName_System_Byte___1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromIssuerNameAndSerialNumber(default(System.Security.Cryptography.X509Certificates.X500DistinguishedName)!, System.Array.Empty<byte>());
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_65_CreateFromIssuerNameAndSerialNumber_2_X500DistinguishedName_System_Byte___2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromIssuerNameAndSerialNumber(default(System.Security.Cryptography.X509Certificates.X500DistinguishedName)!, new byte[2] { default(byte)!, default(byte)! });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_66_CreateFromSubjectKeyIdentifier_3_System_Byte___0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromSubjectKeyIdentifier(default(System.Byte[])!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_67_CreateFromSubjectKeyIdentifier_3_System_Byte___1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromSubjectKeyIdentifier(System.Array.Empty<byte>());
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_68_CreateFromSubjectKeyIdentifier_3_System_Byte___2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromSubjectKeyIdentifier(new byte[2] { default(byte)!, default(byte)! });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_69_CreateFromSubjectKeyIdentifier_4_X509SubjectKeyIdentifierExtension_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509AuthorityKeyIdentifierExtension.CreateFromSubjectKeyIdentifier(default(System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_70_CreateForCertificateAuthority_1_System_Nullable_int__0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension.CreateForCertificateAuthority(default(System.Nullable<System.Int32>));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_71_CreateForEndEntity_2_bool_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension.CreateForEndEntity(default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_72_CreateForEndEntity_2_bool_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension.CreateForEndEntity(false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_73_CreateFromCertFile_0_string_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromCertFile(default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_74_CreateFromCertFile_0_string_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromCertFile("");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_75_CreateFromSignedFile_1_string_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_76_CreateFromSignedFile_1_string_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile("");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_77_Export_3_X509ContentType_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_78_Export_4_X509ContentType_SecureString_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!, default(System.Security.SecureString)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_79_Export_5_X509ContentType_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_80_Export_5_X509ContentType_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_81_ExportPkcs12_6_PbeParameters_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.ExportPkcs12(default(System.Security.Cryptography.PbeParameters)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_82_ExportPkcs12_6_PbeParameters_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.ExportPkcs12(default(System.Security.Cryptography.PbeParameters)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_83_ExportPkcs12_7_Pkcs12ExportPbeParameters_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.ExportPkcs12(default(System.Security.Cryptography.X509Certificates.Pkcs12ExportPbeParameters)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_84_ExportPkcs12_7_Pkcs12ExportPbeParameters_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.ExportPkcs12(default(System.Security.Cryptography.X509Certificates.Pkcs12ExportPbeParameters)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_85_GetCertHash_8__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetCertHash();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_86_GetCertHash_9_HashAlgorithmName_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetCertHash(default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_87_GetCertHashString_10__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetCertHashString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_88_GetCertHashString_11_HashAlgorithmName_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetCertHashString(default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_89_GetEffectiveDateString_12__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetEffectiveDateString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_90_GetExpirationDateString_13__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetExpirationDateString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_91_GetFormat_14__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetFormat();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_92_GetIssuerName_15__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetIssuerName();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_93_GetKeyAlgorithm_16__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetKeyAlgorithm();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_94_GetKeyAlgorithmParameters_17__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetKeyAlgorithmParameters();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_95_GetKeyAlgorithmParametersString_18__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetKeyAlgorithmParametersString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_96_GetName_19__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetName();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_97_GetPublicKey_20__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_98_GetPublicKeyString_21__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetPublicKeyString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_99_GetRawCertData_22__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetRawCertData();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_100_GetRawCertDataString_23__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetRawCertDataString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_101_GetSerialNumber_24__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetSerialNumber();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_102_GetSerialNumberString_25__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate)!.GetSerialNumberString();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_103_CopyWithPrivateKey_0_CompositeMLDsa_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.CopyWithPrivateKey(default(System.Security.Cryptography.CompositeMLDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_104_CopyWithPrivateKey_1_ECDiffieHellman_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.CopyWithPrivateKey(default(System.Security.Cryptography.ECDiffieHellman)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_105_CopyWithPrivateKey_2_MLDsa_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.CopyWithPrivateKey(default(System.Security.Cryptography.MLDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_106_CopyWithPrivateKey_3_MLKem_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.CopyWithPrivateKey(default(System.Security.Cryptography.MLKem)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_107_CopyWithPrivateKey_4_SlhDsa_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.CopyWithPrivateKey(default(System.Security.Cryptography.SlhDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_108_CreateFromPemFile_5_string_string_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile(default(string)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_109_CreateFromPemFile_5_string_string_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile("", default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_110_CreateFromPemFile_5_string_string_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile(default(string)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_111_ExportCertificatePem_6__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.ExportCertificatePem();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_112_GetCertContentType_7_System_Byte___0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(default(System.Byte[])!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_113_GetCertContentType_7_System_Byte___1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(System.Array.Empty<byte>());
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_114_GetCertContentType_7_System_Byte___2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(new byte[2] { default(byte)!, default(byte)! });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_115_GetCertContentType_8_string_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_116_GetCertContentType_8_string_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType("");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_117_GetCompositeMLDsaPrivateKey_9__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetCompositeMLDsaPrivateKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_118_GetCompositeMLDsaPublicKey_10__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetCompositeMLDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_119_GetECDiffieHellmanPrivateKey_11__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetECDiffieHellmanPrivateKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_120_GetECDiffieHellmanPublicKey_12__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetECDiffieHellmanPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_121_GetMLDsaPrivateKey_13__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetMLDsaPrivateKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_122_GetMLDsaPublicKey_14__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetMLDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_123_GetMLKemPrivateKey_15__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetMLKemPrivateKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_124_GetMLKemPublicKey_16__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetMLKemPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_125_GetNameInfo_17_X509NameType_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetNameInfo(default(System.Security.Cryptography.X509Certificates.X509NameType)!, default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_126_GetNameInfo_17_X509NameType_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetNameInfo(default(System.Security.Cryptography.X509Certificates.X509NameType)!, false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_127_GetSlhDsaPrivateKey_18__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetSlhDsaPrivateKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_128_GetSlhDsaPublicKey_19__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.GetSlhDsaPublicKey();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_129_MatchesHostname_26_string_bool_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.MatchesHostname(default(string)!, default(bool), default(bool));
            return result ? 0L : 1L;
        }

        public long Subject_130_MatchesHostname_26_string_bool_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.MatchesHostname("", default(bool), default(bool));
            return result ? 0L : 1L;
        }

        public long Subject_131_MatchesHostname_26_string_bool_bool_2()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.MatchesHostname(default(string)!, false, default(bool));
            return result ? 0L : 1L;
        }

        public long Subject_132_MatchesHostname_26_string_bool_bool_3()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.MatchesHostname(default(string)!, default(bool), false);
            return result ? 0L : 1L;
        }

        public long Subject_133_Verify_27__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2)!.Verify();
            return result ? 0L : 1L;
        }

        public long Subject_134_Add_0_X509Certificate2_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Add(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return ((long)(result) ^ 0xFF);
        }

        public long Subject_135_Contains_3_X509Certificate2_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Contains(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return result ? 0L : 1L;
        }

        public long Subject_136_Export_4_X509ContentType_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_137_Export_5_X509ContentType_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_138_Export_5_X509ContentType_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Export(default(System.Security.Cryptography.X509Certificates.X509ContentType)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_139_ExportCertificatePems_6__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportCertificatePems();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_140_ExportPkcs12_7_PbeParameters_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportPkcs12(default(System.Security.Cryptography.PbeParameters)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_141_ExportPkcs12_7_PbeParameters_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportPkcs12(default(System.Security.Cryptography.PbeParameters)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_142_ExportPkcs12_8_Pkcs12ExportPbeParameters_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportPkcs12(default(System.Security.Cryptography.X509Certificates.Pkcs12ExportPbeParameters)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_143_ExportPkcs12_8_Pkcs12ExportPbeParameters_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportPkcs12(default(System.Security.Cryptography.X509Certificates.Pkcs12ExportPbeParameters)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_144_ExportPkcs7Pem_9__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.ExportPkcs7Pem();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_145_Find_10_X509FindType_object_bool_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Find(default(System.Security.Cryptography.X509Certificates.X509FindType)!, default(object)!, default(bool));
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_146_Find_10_X509FindType_object_bool_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.Find(default(System.Security.Cryptography.X509Certificates.X509FindType)!, default(object)!, false);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_147_FindByThumbprint_11_HashAlgorithmName_string_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.FindByThumbprint(default(System.Security.Cryptography.HashAlgorithmName)!, default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_148_FindByThumbprint_11_HashAlgorithmName_string_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.FindByThumbprint(default(System.Security.Cryptography.HashAlgorithmName)!, "");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_149_GetEnumerator_12__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Certificate2Collection)!.GetEnumerator();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_150_Add_0_X509Certificate_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509CertificateCollection)!.Add(default(System.Security.Cryptography.X509Certificates.X509Certificate)!);
            return ((long)(result) ^ 0xFF);
        }

        public long Subject_151_Contains_3_X509Certificate_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509CertificateCollection)!.Contains(default(System.Security.Cryptography.X509Certificates.X509Certificate)!);
            return result ? 0L : 1L;
        }

        public long Subject_152_GetEnumerator_4__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509CertificateCollection)!.GetEnumerator();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_153_IndexOf_5_X509Certificate_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509CertificateCollection)!.IndexOf(default(System.Security.Cryptography.X509Certificates.X509Certificate)!);
            return ((long)(result) ^ 0xFF);
        }

        public long Subject_154_LoadCertificate_0_System_Byte___0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadCertificate(default(System.Byte[])!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_155_LoadCertificate_0_System_Byte___1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadCertificate(System.Array.Empty<byte>());
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_156_LoadCertificate_0_System_Byte___2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadCertificate(new byte[2] { default(byte)!, default(byte)! });
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_157_LoadCertificateFromFile_1_string_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadCertificateFromFile(default(string)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_158_LoadCertificateFromFile_1_string_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadCertificateFromFile("");
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_159_LoadPkcs12_2_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(default(System.Byte[])!, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_160_LoadPkcs12_2_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(default(System.Byte[])!, "", default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_161_LoadPkcs12_2_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(System.Array.Empty<byte>(), default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_162_LoadPkcs12_2_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_3()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(new byte[2] { default(byte)!, default(byte)! }, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_163_LoadPkcs12Collection_3_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12Collection(default(System.Byte[])!, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_164_LoadPkcs12Collection_3_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12Collection(default(System.Byte[])!, "", default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_165_LoadPkcs12Collection_3_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12Collection(System.Array.Empty<byte>(), default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_166_LoadPkcs12Collection_3_System_Byte___string_X509KeyStorageFlags_Pkcs12LoaderLimits_3()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12Collection(new byte[2] { default(byte)!, default(byte)! }, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_167_LoadPkcs12CollectionFromFile_4_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12CollectionFromFile(default(string)!, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_168_LoadPkcs12CollectionFromFile_4_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12CollectionFromFile("", default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_169_LoadPkcs12CollectionFromFile_4_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12CollectionFromFile(default(string)!, "", default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_170_LoadPkcs12FromFile_5_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12FromFile(default(string)!, default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_171_LoadPkcs12FromFile_5_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_1()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12FromFile("", default(string)!, default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_172_LoadPkcs12FromFile_5_string_string_X509KeyStorageFlags_Pkcs12LoaderLimits_2()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12FromFile(default(string)!, "", default(System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)!, default(System.Security.Cryptography.X509Certificates.Pkcs12LoaderLimits)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_173_Build_0_X509Certificate2_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509Chain)!.Build(default(System.Security.Cryptography.X509Certificates.X509Certificate2)!);
            return result ? 0L : 1L;
        }

        public long Subject_174_GetEnumerator_0__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509ChainElementCollection)!.GetEnumerator();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_175_Clone_0__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509ChainPolicy)!.Clone();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_176_Add_0_X509Extension_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509ExtensionCollection)!.Add(default(System.Security.Cryptography.X509Certificates.X509Extension)!);
            return ((long)(result) ^ 0xFF);
        }

        public long Subject_177_GetEnumerator_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509ExtensionCollection)!.GetEnumerator();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_178_CreateForCompositeMLDsa_0_CompositeMLDsa_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForCompositeMLDsa(default(System.Security.Cryptography.CompositeMLDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_179_CreateForECDsa_1_ECDsa_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForECDsa(default(System.Security.Cryptography.ECDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_180_CreateForMLDsa_2_MLDsa_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForMLDsa(default(System.Security.Cryptography.MLDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_181_CreateForRSA_3_RSA_RSASignaturePadding_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForRSA(default(System.Security.Cryptography.RSA)!, default(System.Security.Cryptography.RSASignaturePadding)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_182_CreateForSlhDsa_4_SlhDsa_0()
        {
            var result = global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForSlhDsa(default(System.Security.Cryptography.SlhDsa)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_183_GetSignatureAlgorithmIdentifier_5_HashAlgorithmName_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!.GetSignatureAlgorithmIdentifier(default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_184_SignData_6_System_Byte___HashAlgorithmName_0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!.SignData(default(System.Byte[])!, default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_185_SignData_6_System_Byte___HashAlgorithmName_1()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!.SignData(System.Array.Empty<byte>(), default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_186_SignData_6_System_Byte___HashAlgorithmName_2()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SignatureGenerator)!.SignData(new byte[2] { default(byte)!, default(byte)! }, default(System.Security.Cryptography.HashAlgorithmName)!);
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_187_EnumerateDnsNames_1__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SubjectAlternativeNameExtension)!.EnumerateDnsNames();
            return (object)(result) != null ? 0L : 1L;
        }

        public long Subject_188_EnumerateIPAddresses_2__0()
        {
            var result = default(global::System.Security.Cryptography.X509Certificates.X509SubjectAlternativeNameExtension)!.EnumerateIPAddresses();
            return (object)(result) != null ? 0L : 1L;
        }
    }
}
