"""Hotupdate stage — ATG patch pass + entry.exe --hotupdate --patch-data.

Flow:
  1. Run ATG --patch-mode to generate patch C# code with transformed return values
  2. Build patch DLL via dotnet build
  3. Run PatchDataExtractor (subject-only mode) to produce patch.patchdata
  4. Run entry.exe --hotupdate --patch-data patch.patchdata
  5. Parse per-method baseline/patched/revert JSON, verify semantic change
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from verification.orchestration.context import ChunkContext, StageResult

# Ensure testing/ is on sys.path so _pipeline.tool_helpers can be imported
_TESTING = str(Path(__file__).resolve().parents[3])
if _TESTING not in sys.path:
    sys.path.insert(0, _TESTING)

from _pipeline.tool_helpers import tool_dll, ensure_tool_built, detect_tfm

_REPO_ROOT = Path(__file__).resolve().parents[4]


# -- BOUNDARY_OVERRIDE: https://github.com/chaos-il2cpp/chaos-il2cpp/issues/PHASE5-HOSTARRAYS --
# Reason: patch-host-arrays.cpp is regenerated here (Python write_text) after the
#         pipeline emits the patch DLL, because the exact type/method name list is
#         only known post-hoc. TPG's BuildHostArrays() covers the ATG-present case;
#         this post-hoc path exists for the batch/hotupdate flow. Preferred fix: push
#         the name list back into TPG. Keep until DONE.
# Expires: 2099-12-31


def _build_patch_dll(patch_output: Path, patch_dll: Path, target_dll: Path | None = None) -> bool:
    """Combine ATG --patch-mode generated .cs files and build into a DLL."""
    # Exclude obj/ build artifacts, CombinedPatchSubjects.cs (self-reference),
    # and AssemblyAttributes files generated by the build system.
    all_patch_files = sorted(
        p for p in patch_output.rglob("*.cs")
        if "obj" not in p.parts
        and p.name != "CombinedPatchSubjects.cs"
        and "AssemblyAttributes" not in p.name
        and "AssemblyInfo" not in p.name
        and "GlobalUsings" not in p.name
    )
    if not all_patch_files:
        print(f"  [hotupdate] No patch .cs files found in {patch_output}")
        return False

    combined_cs = patch_dll.parent / "CombinedPatchSubjects.cs"
    # Concatenate ATG output files as-is — all usings and code bodies are
    # generated correctly by ATG --patch-mode.
    parts = [pf.read_text(encoding="utf-8") for pf in all_patch_files]
    content = "\n\n".join(parts)
    combined_cs.write_text(content, encoding="utf-8")

    # Detect TFM from target DLL path (e.g. ".../9.0.0/...System.Private.CoreLib.dll" → net9.0)
    # Reuse build.py's exact TFM detection for consistency.
    tfm = detect_tfm(target_dll)
    sdk_csproj = (_REPO_ROOT / "src" / "reference" / "Chaos.TestFramework.Sdk"
                  / "Chaos.TestFramework.Sdk.csproj")
    ref_block = ""
    if target_dll is not None:
        # Determine if the target DLL is part of the shared framework.
        # If it lives under DOTNET_ROOT/shared/ (e.g.
        # /usr/share/dotnet/shared/Microsoft.NETCore.App/), the TFM already
        # provides an implicit reference.  Adding an explicit <Reference>
        # would cause CS0433 (type forwarded to both the real assembly and
        # a facade like System.Xml.ReaderWriter) or CS0518 (System.Private.
        # CoreLib predefined types).  Only add an explicit reference for
        # assemblies OUTSIDE the shared framework (NuGet packages, third-
        # party DLLs, etc.).
        dotnet_shared = os.path.join(
            os.environ.get("DOTNET_ROOT", "/usr/share/dotnet"), "shared")
        target_is_framework = (
            target_dll.stem == "System.Private.CoreLib" or
            (dotnet_shared in str(target_dll))
        )
        if not target_is_framework:
            # Reference the target DLL so patch code can resolve types
            # (e.g. SseItem<>, IPAddress, etc.) from the source assembly.
            ref_block = (
                f"    <Reference Include=\"{target_dll.stem}\">\n"
                f"      <HintPath>{target_dll}</HintPath>\n"
                "    </Reference>\n"
        )
    csproj = patch_dll.parent / "PatchSubjects.csproj"
    csproj.write_text(
        "<Project Sdk=\"Microsoft.NET.Sdk\">\n"
        "  <PropertyGroup>\n"
        "    <OutputType>Library</OutputType>\n"
        f"    <TargetFramework>{tfm}</TargetFramework>\n"
        "    <ImplicitUsings>enable</ImplicitUsings>\n"
        "    <Nullable>enable</Nullable>\n"
        "    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n"
        "    <NoWarn>$(NoWarn);SYSLIB0011;CS0433;SYSLIB5006;SYSLIB5007;SYSLIB5008;CA2252</NoWarn>\n"
        "    <WarningsNotAsErrors>$(WarningsNotAsErrors);CS0433;SYSLIB5006;SYSLIB5007;SYSLIB5008</WarningsNotAsErrors>\n"
        "    <EnablePreviewFeatures>true</EnablePreviewFeatures>\n"
        "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>\n"
        "  </PropertyGroup>\n"
        "  <ItemGroup>\n"
        f"    <Compile Include=\"{combined_cs.name}\" />\n"
        f"    <ProjectReference Include=\"{sdk_csproj}\" />\n"
        f"{ref_block}"
        "  </ItemGroup>\n"
        "</Project>\n"
    )

    result = subprocess.run(
        ["dotnet", "build", str(csproj),
         f"-p:OutDir={patch_dll.parent}",
         "--nologo"],
        capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=120,
    )
    if result.returncode != 0:
        for line in (result.stderr.splitlines() + result.stdout.splitlines())[-10:]:
            print(f"      {line}")
        return False

    return patch_dll.exists()


def _regenerate_host_arrays(ctx, metadata: dict) -> bool:
    """Regenerate patch-host-arrays.cpp with correct AOT name mappings.

    Returns True on success, False on any failure (caller must propagate).
    """
    hu_indices = metadata.get("hotupdateMethodIndices", [])
    methods = metadata.get("methods", [])
    if not hu_indices or not methods:
        print(f"  [hotupdate] No hotupdate subjects in metadata, skipping host arrays")
        return False

    # Build assembly name from the first method's subjectId
    first_sid = methods[0].get("methodSubjectId", "")
    assembly = first_sid.split("/")[0] if "/" in first_sid else ""
    if not assembly:
        print(f"  [hotupdate] Cannot determine assembly name from subjectId")
        return False

    import re
    sanitized_asm = assembly.replace(".", "_")
    host_ns = f"AutoGenerated.{sanitized_asm}"

    # Read AOT generated code to get correct type/method names
    aot_gen_path = ctx.chunk_dir / "native" / "subjects" / "native-aot.generated.cpp"
    if not aot_gen_path.exists():
        aot_gen_path = ctx.chunk_dir / "native" / "codegen" / "generated" / "native-aot.generated.cpp"
    if not aot_gen_path.exists():
        print(f"  [hotupdate] Cannot read AOT generated code at either location")
        return False

    aot_code = aot_gen_path.read_text(encoding="utf-8", errors="replace")

    # Parse slot map
    slot_match = re.search(r'kSubjectSlotMap\[\d+\]\s*=\s*\{([^}]+)\}', aot_code, re.DOTALL)
    if not slot_match:
        print(f"  [hotupdate] Could not parse kSubjectSlotMap")
        return False
    slot_map = [int(x.strip()) for x in slot_match.group(1).split(",") if x.strip().isdigit()]

    # Parse hotpatch types: {type_name, namespace, first_idx, count}
    type_entries = re.findall(
        r'\{\s*"([^"]+)",\s*"([^"]+)",\s*(\d+)u,\s*(\d+)u\s*\}',
        aot_code)
    # Parse hotpatch methods: {method_name, token, flags}
    method_entries = re.findall(
        r'\{\s*"([^"]+)",\s*0x[0-9A-Fa-f]+u,\s*(\d+)u\s*\}',
        aot_code)

    if not type_entries or not method_entries:
        print(f"  [hotupdate] Could not parse AOT entries ({len(type_entries)} types, {len(method_entries)} methods)")
        return False

    # Build method_name -> AOT_method_index mapping from method_entries
    # method_entries[i] = (name, flags) at AOT method index i
    method_name_to_idx = {}
    for i, (mn, _) in enumerate(method_entries):
        # Some methods may have duplicate names across types; keep first occurrence
        if mn not in method_name_to_idx:
            method_name_to_idx[mn] = i

    # Build type index -> (type_name, first_idx, count)
    type_info = []
    for tn, ns, first, count_str in type_entries:
        if ns != host_ns:
            continue
        type_info.append((tn, int(first), int(count_str)))

    if not type_info:
        print(f"  [hotupdate] No type entries found for namespace {host_ns}")
        return False

    # For each hotupdate subject, find type name by method name
    idx_to_method = {m["index"]: m for m in methods}
    type_names = []
    method_names = []

    for idx in hu_indices:
        m = idx_to_method.get(idx)
        if m is None:
            continue
        method_name = m.get("generatedMethodId", "")
        if not method_name:
            continue

        # Find AOT method index for this method name
        aot_idx = method_name_to_idx.get(method_name)
        if aot_idx is None:
            continue

        # Find type entry covering this AOT method index
        found_type = None
        for tn, first_idx, cnt in type_info:
            if first_idx <= aot_idx < first_idx + cnt:
                found_type = tn
                break

        if found_type is None:
            continue

        type_names.append(found_type)
        method_names.append(method_name)

    if not type_names:
        print(f"  [hotupdate] No host array entries generated")
        return False

    host_arrays_path = ctx.chunk_dir / "native" / "patch-host-arrays.cpp"
    lines = [
        "// patch-host-arrays.cpp — Auto-generated (hotupdate pipeline)",
        f'extern const char* const kPatchDataHostNamespace = "{host_ns}";',
        "extern const char* const kPatchDataHostTypeNames[] = {",
    ]
    for tn in type_names:
        lines.append(f'    "{tn}",')
    lines.extend(["};", "extern const char* const kPatchDataHostMethodNames[] = {"])
    for mn in method_names:
        lines.append(f'    "{mn}",')
    lines.extend(["};", f"extern const int kPatchDataCount = {len(type_names)};"])
    # BOUNDARY_OVERRIDE: patch-host-arrays.cpp (post-hoc name list; see header note).
    host_arrays_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  [hotupdate] Regenerated {host_arrays_path.name} ({len(type_names)} entries)")
    return True


def _incremental_rebuild(ctx) -> bool:
    """Incremental cmake rebuild of entry.exe with patch-host-arrays.cpp linked.

    Deletes the stale patch-host-arrays.obj first, patches CMakeLists.txt so
    patch-host-arrays.cpp is compiled AND linked FIRST, reconfigures, and rebuilds.
    Returns True on success, False on failure.

    Distinct-linking note: BOTH runtime-patchdata.cpp (sentinel kPatchDataHostCount=0,
    null arrays) and patch-host-arrays.cpp (real entries) define the same symbols.
    Verified MSVC /FORCE:MULTIPLE keeps the FIRST-compiled duplicate (LNK4006), so the
    patch file must link before the sentinel.  runtime-patchdata.cpp still supplies
    kPatchData/kPatchDataSize (no duplicate), so it stays in the build — just later.

    Platform note: MSVC /FORCE:MULTIPLE is required for the distinct-linking approach.
    On non-MSVC toolchains, cross-TU duplicate symbols are a hard error (multiple definition).
    Non-Windows platforms will return False.
    """
    build_dir = ctx.chunk_dir / "native" / "build"
    native_dir = ctx.chunk_dir / "native"
    src_file = native_dir / "patch-host-arrays.cpp"
    if not build_dir.exists() or not src_file.exists():
        print(f"  [hotupdate] Cannot rebuild: build dir or source not found")
        return False

    import subprocess, shutil, glob as _glob

    # Platform check: MSVC /FORCE:MULTIPLE is required for the distinct-linking
    # approach. On non-MSVC toolchains, cross-TU duplicate symbols are a hard error.
    if sys.platform != "win32":
        print(f"  [hotupdate] Non-MSVC platform: incremental rebuild not supported "
              f"(MSVC /FORCE:MULTIPLE required for duplicate symbol resolution)")
        return False

    # Delete stale .obj to force MSBuild recompilation
    obj_pattern = str(build_dir / "chaos_entry.dir" / "RelWithDebInfo" / "patch-host-arra*")
    stale_objs = _glob.glob(obj_pattern)
    for o in stale_objs:
        os.remove(o)
        print(f"  [hotupdate] Removed stale .obj: {os.path.basename(o)}")

    # Touch source to ensure timestamp changes
    os.utime(str(src_file), None)

    cmake = shutil.which("cmake") or r"C:\Program Files\CMake\bin\cmake.exe"
    # ── Reorder CMakeLists so patch-host-arrays.cpp is compiled + linked FIRST ──
    # The generated CMakeLists.txt list(REMOVE_ITEM CHAOS_NATIVE_STUBS ...) excludes
    # patch-host-arrays.cpp entirely (so it is never compiled → entry uses the
    # runtime-patchdata sentinel → 0 patches); even when added, MSVC /FORCE:MULTIPLE
    # would keep the sentinel if it links first.  Fix both by un-excluding the file and
    # placing it ahead of runtime-patchdata.cpp.
    cmake_path = native_dir / "CMakeLists.txt"
    # BOUNDARY_OVERRIDE: https://github.com/chaos-il2cpp/chaos-il2cpp/issues/PHASE5-HOSTARRAYS
    # Reason: Hotupdate pipeline patches CMakeLists.txt at runtime to reorder source
    #         files for correct link order. This is a fragile text surgery workaround
    #         — the CMake template is generated by TPG and any structural change to it
    #         will silently break the insert logic. Preferred fix: move the reordering
    #         into the TPG template generator.
    # Expires: 2099-12-31
    try:
        cmake_text = cmake_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        cmake_text = None
    _patched_cmake = False
    _anchor_found = True

    def _restore_cmake():
        if cmake_text and _patched_cmake and cmake_path.exists():
            cmake_path.write_text(cmake_text, encoding="utf-8")

    # Wrap the rebuild in try/finally to ensure CMakeLists.txt is always restored
    # even if the process is interrupted mid-rebuild (#17).
    try:
        if not cmake_text:
            # Could not read CMakeLists.txt — cannot un-exclude + reorder the patch
            # file, so the sentinel (0 patches) build would silently pass (#1).
            print(f"  [hotupdate] ERROR: Cannot read {cmake_path.name} — cannot wire "
                  f"patch-host-arrays.cpp link; aborting to avoid false-positive pass.")
            return False
        if cmake_text:
            src_lines = cmake_text.splitlines(keepends=True)
            # (1) drop the REMOVE_ITEM entry that excludes patch-host-arrays.cpp
            kept = [ln for ln in src_lines
                    if not ln.strip().startswith('"${CMAKE_CURRENT_SOURCE_DIR}/patch-host-arrays.cpp"')]
            # (2) ensure patch-host-arrays.cpp is the FIRST CHAOS_ENTRY_SOURCES source,
            #     right after runtime-entry.cpp and before runtime-patchdata.cpp.
            out_lines = []
            inserted_host = False
            for ln in kept:
                stripped = ln.strip()
                if not inserted_host and stripped.startswith('"runtime-entry.cpp"'):
                    indent = ln[:len(ln) - len(ln.lstrip())]
                    out_lines.append(ln)
                    out_lines.append(f'{indent}    "patch-host-arrays.cpp"\n')
                    inserted_host = True
                else:
                    out_lines.append(ln)
            # If runtime-entry.cpp isn't the anchor, prepend at set(CHAOS_ENTRY_SOURCES too.
            if not inserted_host:
                out_lines = []
                for ln in kept:
                    if not inserted_host and ln.strip().startswith("set(CHAOS_ENTRY_SOURCES"):
                        indent = ln[:len(ln) - len(ln.lstrip())]
                        out_lines.append(ln)
                        out_lines.append(f'{indent}    "patch-host-arrays.cpp"\n')
                        inserted_host = True
                    else:
                        out_lines.append(ln)
            if not inserted_host:
                _anchor_found = False
                print(f"  [hotupdate] WARNING: Could not find anchor in CMakeLists.txt "
                      f"(neither 'runtime-entry.cpp' nor 'set(CHAOS_ENTRY_SOURCES' found). "
                      f"CMake template may have changed — patch-host-arrays.cpp will NOT be linked.")
            out_text = "".join(out_lines)
            if out_text != cmake_text and inserted_host:
                cmake_path.write_text(out_text, encoding="utf-8")
                _patched_cmake = True
                print(f"  [hotupdate] Patched CMakeLists.txt: patch-host-arrays.cpp linked before runtime-patchdata.cpp")
            else:
                _patched_cmake = False

        # Fail fast if anchor wasn't found — sentinel build would pass silently (#1)
        if not _anchor_found:
            print(f"  [hotupdate] Cannot guarantee patch linking; aborting rebuild to avoid false-positive pass")
            return False

        # Re-configure so the (now un-excluded) file is part of the target.
        reconf = subprocess.run(
            [cmake, "-S", str(native_dir), "-B", str(build_dir)],
            capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=120)
        if reconf.returncode != 0:
            for line in (reconf.stderr.splitlines() + reconf.stdout.splitlines())[-5:]:
                print(f"      {line}")
            print(f"  [hotupdate] cmake configure FAILED (rc={reconf.returncode})")
            return False

        cmd = [cmake, "--build", str(build_dir), "--config", "RelWithDebInfo", "--target", "chaos_entry"]
        print(f"  [hotupdate] Incremental rebuild...")
        result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=300)
        if result.returncode != 0:
            for line in (result.stderr.splitlines() + result.stdout.splitlines())[-5:]:
                print(f"      {line}")
            print(f"  [hotupdate] Rebuild FAILED (rc={result.returncode})")
            return False

        src = build_dir / "RelWithDebInfo" / "chaos_entry.exe"
        dst = ctx.chunk_dir / "native" / "entry.exe"
        if src.exists():
            # Verify patch-host-arrays.cpp was actually linked (not sentinel) (#1)
            if not _patched_cmake:
                print(f"  [hotupdate] WARNING: CMakeLists.txt patch was not applied — "
                      f"entry.exe may contain sentinel (0 patches). "
                      f"Verifying patch-host-arra*.obj exists...")
                fresh_objs = _glob.glob(str(build_dir / "chaos_entry.dir" / "RelWithDebInfo" / "patch-host-arra*"))
                if not fresh_objs:
                    print(f"  [hotupdate] ERROR: No patch-host-arra*.obj found after rebuild — "
                          f"patch was NOT linked. Returning failure to avoid false-positive pass.")
                    return False
                print(f"  [hotupdate] patch-host-arra*.obj found, patch linked.")
            shutil.copy2(src, dst)
            print(f"  [hotupdate] Rebuilt entry.exe: {dst.name} ({src.stat().st_size} bytes)")
            return True
        print(f"  [hotupdate] Rebuild completed but entry.exe not found at {src}")
        return False
    finally:
        _restore_cmake()


def run_hotupdate_chunk(ctx: ChunkContext, stages: dict[str, StageResult]) -> StageResult:
    """HotUpdate stage: generate patch data, run entry.exe (+ entry-jit.exe), verify semantic change."""
    start = time.perf_counter()

    # Collect available binaries
    technologies: list[tuple[Path, str]] = []
    aot_exe = ctx.entry_exe_path
    if aot_exe.exists():
        technologies.append((aot_exe, "aot"))
    else:
        return StageResult(
            stage="hotupdate", status="skipped",
            summary=f"entry.exe not found, skipping hotupdate",
            duration_ms=int((time.perf_counter() - start) * 1000),
        )
    jit_exe = ctx.entry_jit_exe_path
    has_jit = jit_exe.exists()
    if has_jit:
        technologies.append((jit_exe, "jit"))
    else:
        print(f"  [hotupdate] entry-jit.exe not found, skipping chaos-jit hotupdate")

    metadata_path = ctx.subjects_metadata_path
    if not metadata_path.exists():
        return StageResult(
            stage="hotupdate", status="skipped",
            summary="subjects.metadata.json not found, skipping hotupdate",
            duration_ms=int((time.perf_counter() - start) * 1000),
        )

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    hotupdate_indices = metadata.get("hotupdateMethodIndices", [])
    if not hotupdate_indices:
        print(f"  [hotupdate] No hotupdate subjects in metadata, skipping")
        return StageResult(
            stage="hotupdate", status="skipped_no_subjects",
            summary="no hotupdate subjects",
            duration_ms=int((time.perf_counter() - start) * 1000),
        )

    # ── Step 1: Try to generate patch data (ATG --patch-mode + build) ──
    _patch_generation_attempted = False
    _patch_skipped_no_methods = False
    # Full patch data generation pipeline: ATG --patch-mode → csc → PatchDataExtractor.
    # PatchDataExtractor reads the patch DLL's PE metadata and produces a self-contained
    # .patchdata binary (format "PADT" magic) that the runtime PatchLoader can apply.
    # The flow: ATG generates CombinedPatchSubjects.cs → dotnet build → PatchSubjects.dll
    # → TPG extract-patch-data → patch.patchdata → ApplyPatchFromMemoryEx at runtime.
    patch_data_path = None
    print(f"  [hotupdate] Attempting ATG --patch-mode to generate patch DLL...")

    # Find target DLL (same logic as build.py, with Linux fallback)
    target_dll: Path | None = None
    dll_candidates: list[Path] = [
        ctx.foundation_dir / f"{ctx.assembly}.dll",
    ]
    # Use project-internal reference DLLs first (portable, no system dependency)
    for ref_dir in sorted((_REPO_ROOT / "src" / "dll" / "dotnet-foundation").iterdir(), reverse=True):
        candidate = ref_dir / "runtime" / f"{ctx.assembly}.dll"
        if candidate.exists():
            dll_candidates.insert(0, candidate)
    # Fallback: search system-wide dotnet paths (checked after project ref)
    import sys as _sys
    for base in (
        Path(os.environ.get("DOTNET_ROOT", "")),
        Path("/usr/share/dotnet/shared"),
        Path("C:/Program Files/dotnet/shared") if _sys.platform == "win32" else Path(""),
    ):
        if base.exists():
            for runtime_dir in sorted(base.rglob(f"**/{ctx.assembly}.dll")):
                dll_candidates.append(runtime_dir)
    for c in dll_candidates:
        if c.exists():
            target_dll = c
            print(f"  [hotupdate] Target DLL: {c}")
            break

    if target_dll is None:
        print(f"  [hotupdate] Target DLL not found, skipping ATG --patch-mode")
    elif ensure_tool_built("Chaos.IL2CPP.Tools.AutoTestGenerator"):
        _patch_generation_attempted = True
        auto_dll = tool_dll("Chaos.IL2CPP.Tools.AutoTestGenerator")
        patch_output = ctx.foundation_dir / "chunks" / ctx.slug / "managed" / ".autogen.patch"

        cmd = [
            "dotnet", "exec", str(auto_dll),
            "--dll", str(target_dll),
            "--all-types",
            "--output", str(patch_output),
            "--chunk-slug", ctx.slug,
            "--patch-mode",
        ]

        chunk_partition = json.loads(ctx.namespace_partition_path.read_text(encoding="utf-8"))
        chunk_def = next((c for c in chunk_partition.get("chunks", []) if c["slug"] == ctx.slug), None)
        if chunk_def and chunk_def.get("namespaces"):
            cmd.extend(["--namespace-filter", ",".join(chunk_def["namespaces"])])

        atg_result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=1200)
        if atg_result.returncode == 0:
            # Check if ATG produced any .cs files (non-empty patch generation)
            patch_cs_files = sorted(
                p for p in patch_output.rglob("*.cs")
                if "obj" not in p.parts and p.name != "CombinedPatchSubjects.cs"
                and "AssemblyAttributes" not in p.name
                and "AssemblyInfo" not in p.name
                and "GlobalUsings" not in p.name
            ) if patch_output.exists() else []
            if not patch_cs_files:
                print(f"  [hotupdate] ATG --patch-mode produced 0 .cs files (no methods to patch)")
                _patch_skipped_no_methods = True
            else:
                # Try to build the generated patch DLL
                patch_dll = ctx.chunk_dir / "managed" / "subjects" / "patch" / "PatchSubjects.dll"
                patch_dll.parent.mkdir(parents=True, exist_ok=True)
                if _build_patch_dll(patch_output, patch_dll, target_dll):
                    print(f"  [hotupdate] Patch DLL built: {patch_dll}")
                    # Extract patch data via TPG (IL2CPP codegen layer)
                    if ensure_tool_built("Chaos.IL2CPP.Tools.TestProjectGenerator"):
                        tpg_dll = tool_dll("Chaos.IL2CPP.Tools.TestProjectGenerator")
                        patch_data_path = ctx.chunk_dir / "native" / "patch.patchdata"
                        patch_data_path.parent.mkdir(parents=True, exist_ok=True)
                        extract_cmd = [
                            "dotnet", "exec", str(tpg_dll),
                            "extract-patch-data",
                            "--dll", str(patch_dll),
                            "--output", str(patch_data_path),
                        ]
                        # FP-8: Pass subject indices to align sentinel values with baseline.
                        hu_indices = metadata.get("hotupdateMethodIndices")
                        if hu_indices:
                            extract_cmd.extend(["--subject-indices", ",".join(str(i) for i in hu_indices)])
                            extract_cmd.extend(["--subject-only"])
                        extract_result = subprocess.run(
                            extract_cmd, capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=120)
                        if extract_result.returncode == 0:
                            patch_data_size = patch_data_path.stat().st_size
                            print(f"  [hotupdate] Patch data: {patch_data_path} ({patch_data_size} bytes)")
                            if patch_data_size == 0:
                                print(f"  [hotupdate] ERROR: patch data is empty")
                                return StageResult(
                                    stage="hotupdate", status="error",
                                    summary="patch data is empty",
                                    duration_ms=int((time.perf_counter() - start) * 1000))
                        else:
                            print(f"  [hotupdate] TPG extract-patch-data failed, falling back to no-patch mode")
                            for line in (extract_result.stderr.splitlines() + extract_result.stdout.splitlines())[-5:]:
                                print(f"      {line}")
                            patch_data_path = None
                    else:
                        print(f"  [hotupdate] TPG build failed, falling back to no-patch mode")
                        patch_data_path = None
                else:
                    print(f"  [hotupdate] Patch DLL build failed, falling back to no-patch mode")
                    # Show ATG output diagnostics
                    if patch_output.exists():
                        import glob as _glob
                        cs_files = sorted(p for p in patch_output.rglob("*.cs") if p.suffix == ".cs" and "obj" not in p.parts)
                        total_lines = sum(len(p.read_text(encoding="utf-8", errors="replace").splitlines()) for p in cs_files)
                        print(f"  [hotupdate]   ATG generated {len(cs_files)} .cs files ({total_lines} lines)")
                        for pf in cs_files[:5]:
                            print(f"  [hotupdate]   ATG output: {pf.relative_to(patch_output)}")
        else:
            print(f"  [hotupdate] ATG --patch-mode failed, falling back to no-patch mode")
            for line in (atg_result.stderr.splitlines() + atg_result.stdout.splitlines())[-10:]:
                    print(f"      {line}")
    else:
        print(f"  [hotupdate] ATG build failed, falling back to no-patch mode")

    # ── Step 1.5: Regenerate patch-host-arrays.cpp + incremental rebuild ──
    # The patch-host-arrays.cpp maps patch DLL method indices to AOT registry
    # names. It must be regenerated after patch data extraction because the TPG
    # generates it at project time (before ATG --patch-mode runs) with sentinel
    # null values. Without this mapping, ApplyPatchFromMemoryEx cannot match
    # patch methods to AOT dispatch entries (0 patches applied).
    if patch_data_path and patch_data_path.exists() and patch_data_path.stat().st_size > 0:
        # P0-A/P1-A (false+-fix): if host-array regeneration fails (name-map miss,
        # empty mapping, stale parse), ApplyPatchFromMemoryEx will match 0 dispatch
        # entries and the native run would "pass" while applying nothing. Propagate
        # the failure as an error instead of silently running on stale arrays.
        if not _regenerate_host_arrays(ctx, metadata):
            return StageResult(
                stage="hotupdate", status="error",
                summary="patch-host-arrays.cpp regeneration failed — cannot guarantee patch "
                        "will be applied (would risk a false-positive no-op pass); check "
                        "native-aot.generated.cpp parse / name mapping",
                duration_ms=int((time.perf_counter() - start) * 1000))
        if not _incremental_rebuild(ctx):
            return StageResult(
                stage="hotupdate", status="error",
                summary="incremental rebuild failed after host-array regen — stale executable "
                        "cannot apply patch (false-positive risk); not marking passed",
                duration_ms=int((time.perf_counter() - start) * 1000))

    # ── Step 2: Run entry.exe --hotupdate [--patch-data ...] [--benchmark-iterations N] ──
    # NOTE: We do NOT do a cmake rebuild here.  The cmake build infrastructure
    # is managed by the build stage (TPG generate-dll) which regenerates
    # CMakeLists.txt from Scriban templates with correct CHAOS_SDK_DIR paths.
    # Incremental cmake rebuilds in the hotupdate stage fail because:
    #   1. CMakeLists.txt may have been patched for Linux cross-builds
    #   2. cmake auto-regeneration loses the CHAOS_SDK_DIR path
    #   3. The patch-host-arrays.cpp data is optional (Subject_N → AOT registry
    #      mapping), not critical for patch data correctness.
    # The patch data (method return values) is loaded at runtime via --patch-data.
    hotupdate_args = [str(ctx.entry_exe_path), "--hotupdate"]
    if patch_data_path:
        hotupdate_args.extend(["--patch-data", str(patch_data_path)])
        print(f"  [hotupdate] Running with --patch-data {patch_data_path.name}...")
    else:
        print(f"  [hotupdate] Running without --patch-data (no semantic change expected)...")

    # When patch data is available, run benchmark before/after for performance comparison.
    # Scale iterations by chunk size: 5 for small (<500 methods), 2 for medium, 0 disabled
    # for large (keeps the run bounded; the semantic assertion coverage is invariant of it).
    #
    # The DispatchDirectVoid+benchmark+patch-data crash (interpreter tier-promotion + GC
    # re-entrancy in the timed loop) was fixed in Dispatch.scriban (commit f5c4a2dc2) via:
    #   (1) 1000-call warmup to terminal tier outside the timer,
    #   (2) budgeted no-GC region (chaos_gc_try_start_no_gc_region) instead of a TLS-only
    #       counter, failing-safe if the budget is insufficient,
    #   (3) post-timer chaos_gc_end_no_gc_region to release the deferred GC outside window.
    #
    # The fix was authored-but-not-yet validated in a full rebuild of a hotupdate family.
    # Benchmarking is therefore ENABLED here (small/medium chunks) but overridable to 0 via
    # CHAOS_HOTUPDATE_BENCHMARK_ITERS — so the first nightly/release full rebuild can confirm
    # the fix holds, and if it does not, flip the env var off in CI profile config rather than
    # editing code.  (The semantic assertion path — baseline/patched/revert — is unaffected by
    # benchmark_iterations, so a benchmark crash cannot false-pass/false-fail correctness.)
    method_count = len(hotupdate_indices)
    benchmark_iterations = 0
    if method_count < 500:
        benchmark_iterations = 5
    elif method_count < 5000:
        benchmark_iterations = 2
    # Allow an operator to force-disable/force a specific value from CI without a code change.
    _env_override = os.environ.get("CHAOS_HOTUPDATE_BENCHMARK_ITERS")
    if _env_override is not None:
        try:
            benchmark_iterations = int(_env_override)
        except (TypeError, ValueError):
            benchmark_iterations = 0

    # Scale timeout by chunk size: 3s per method for 3 passes (baseline/patched/revert)
    hotupdate_timeout = max(120, 60 + method_count * 3)
    print(f"  [hotupdate] {method_count} subjects, timeout={hotupdate_timeout}s, benchmark_iters={benchmark_iterations}")

    if benchmark_iterations > 0:
        hotupdate_args.extend(["--benchmark-iterations", str(benchmark_iterations)])
        print(f"  [hotupdate] With before/after benchmark ({benchmark_iterations} iter)...")

    try:
        r = subprocess.run(
            hotupdate_args,
            capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=hotupdate_timeout,
        )
    except subprocess.TimeoutExpired:
        return StageResult(
            stage="hotupdate", status="error",
            summary=f"hotupdate timed out after {hotupdate_timeout}s",
            duration_ms=int((time.perf_counter() - start) * 1000),
        )

    stdout = r.stdout or ""
    stderr = r.stderr or ""

    # ── Step 4b: Parse JSON output with structural integrity check ──
    hotupdate_data: dict[str, Any] = {}
    json_truncated = False
    try:
        json_start = stdout.find("{")
        json_end = stdout.rfind("}") + 1
        if json_start >= 0 and json_end > json_start:
            payload = stdout[json_start:json_end]
            hotupdate_data = json.loads(payload)
    except (json.JSONDecodeError, KeyError):
        json_truncated = True

    # B1: Structural integrity check — verify baselineFact count matches totalMethods.
    # If they don't match, the JSON was truncated and partial data is unreliable.
    if hotupdate_data:
        total = hotupdate_data.get("totalMethods", 0)
        baseline_fact = hotupdate_data.get("baselineFact", [])
        if total > 0 and len(baseline_fact) != total:
            json_truncated = True
            print(f"  [hotupdate] WARNING: JSON truncated — expected {total} baseline entries, got {len(baseline_fact)}")

    passed = hotupdate_data.get("passedMethods", 0)
    failed = hotupdate_data.get("failedMethods", 0)
    assert_failed = hotupdate_data.get("patchedAssertFailed", 0)
    all_semantic = hotupdate_data.get("allSemantic", False)
    all_revert = hotupdate_data.get("allRevert", False)
    semantic_changed = hotupdate_data.get("semanticChangedCount", 0)
    reverted_fact = hotupdate_data.get("revertedFact", [])
    baseline_benchmark = hotupdate_data.get("baselineBenchmark", [])
    patched_benchmark = hotupdate_data.get("patchedBenchmark", [])

    # Compute per-method revert pass count
    revert_passed = sum(1 for r in reverted_fact if r.get("passed"))

    ctx.results_dir.mkdir(parents=True, exist_ok=True)
    result_path = ctx.results_dir / "hotupdate.json"
    result_data = {
        "exitCode": getattr(r, 'returncode', r.get('exitCode', 0)) if isinstance(r, dict) else r.returncode,
        "passed": passed,
        "failed": failed,
        "assertFailed": assert_failed,
        "allSemantic": all_semantic,
        "allRevert": all_revert,
        "revertPassed": revert_passed,
        "semanticChangedCount": semantic_changed,
        "patchDataUsed": patch_data_path is not None,
        "patchFailed": patch_data_path is None and _patch_generation_attempted and not _patch_skipped_no_methods,
        "patchSkippedNoMethods": _patch_skipped_no_methods,
        "truncated": json_truncated,
        "crash": hotupdate_data.get("_crash", False),
        "hasBaselineBenchmark": len(baseline_benchmark) > 0,
        "hasPatchedBenchmark": len(patched_benchmark) > 0,
        "details": hotupdate_data,
        "stderr": stderr[:500] if stderr else "",
    }

    # Determine status:
    # - Unified pass criterion (applies to both with and without patch data):
    #   methods must execute without crashing (passed>0 && assert_failed==0) and
    #   revert must work cleanly (allRevert=true).
    # - With IL rewriting, allSemantic (semantic_changed>0) is REQUIRED as a hard gate:
    #   it proves the patch data was actually applied AND the replacement (sentinel)
    #   IL executed (patched != baseline). Without it, a "no-op patch" (0 dispatch
    #   entries activated because of a name-map miss, empty host arrays, or a stale
    #   executable) still runs the original AOT body, does not crash, and "reverts"
    #   trivially — reporting passed while NO replacement code ever ran (false+).
    # - assert_failed > 0 means the patch introduced a crash in a previously-passing
    #   method — this is a genuine regression and should fail.
    # - Native non-zero exit (even with well-formed JSON) is treated as unreliable:
    #   the process may have crashed after flushing stdout.
    errors: list[str] = []
    exit_code = (r.returncode if isinstance(r, subprocess.CompletedProcess)
                 else (r.get('exitCode', 0) if isinstance(r, dict) else 0))
    native_crash = exit_code != 0
    active_patch_count = hotupdate_data.get("activePatchCount", 0)

    if json_truncated:
        status = "error"
        if not errors:
            errors.append("hotupdate JSON truncated — results unreliable")
    elif not hotupdate_data:
        status = "error"
        if not errors:
            errors.append("hotupdate returned no data")
    elif result_data.get("patchFailed"):
        # Genuine patch generation failure (ATG/build crashed, not just 0 methods)
        status = "error"
        if not errors:
            errors.append("patch data generation failed earlier")
    elif result_data.get("patchSkippedNoMethods"):
        # ATG produced 0 patchable methods — tests ran clean, nothing to patch.
        # Semantic gate N/A (no patch to apply); require clean run + clean revert.
        status = "passed" if (assert_failed == 0 and all_revert and not native_crash) else "failed"
        if status != "passed" and not errors:
            errors.append("patch skipped; clean-run/revert/exit-code requirement unmet")
        print(f"  [hotupdate] No methods to patch — {passed} passed, revert={all_revert}")
    # P2-A: cross-check activePatchCount against semantic_changed.
    # If semantic_changed > 0 but activePatchCount == 0, the semantic change
    # came from a non-patch source (e.g. void method RAX garbage) — this is an
    # error, not a genuine patch application.
    elif patch_data_path and semantic_changed > 0 and active_patch_count == 0:
        status = "error"
        if not errors:
            errors.append(
                f"semantic_changed={semantic_changed} but activePatchCount=0 — "
                f"semantic change detected without any patch dispatch entries active; "
                f"likely a false-positive from void-method RAX noise")
    elif patch_data_path:
        # P0-A (false+-fix): pass REQUIRES semantic_changed > 0 — i.e. at least one
        # patched subject actually produced a different value than its baseline
        # (the sentinel body executed, not the original AOT body).  A no-op patch
        # (0 dispatch entries activated) yields semantic_changed == 0 and must fail,
        # not pass.  Combined with a clean run (no assert crash) + clean revert +
        # clean native exit code.
        semantic_ok = semantic_changed > 0
        status = "passed" if (assert_failed == 0 and all_revert and semantic_ok and not native_crash) else "failed"
        if status != "passed":
            if not semantic_ok:
                errors.append(
                    f"semantic_changed == {semantic_changed} — patch appeared to apply 0 "
                    f"replacements (no patched value differed from baseline); possible "
                    f"no-op patch / name-map miss / stale executable")
            elif assert_failed != 0:
                errors.append(f"patch introduced {assert_failed} assertion crash(es)")
            elif not all_revert:
                errors.append("revert did not cleanly restore baseline")
            elif native_crash:
                errors.append(f"native runner exited non-zero ({exit_code}) with complete JSON — unreliable")
    else:
        status = "skipped"
        print(f"  [hotupdate] Skipped — no patch data was provided")
        if not errors:
            errors.append("no patch data — nothing meaningful was tested")

    # Mark truncated JSON
    if json_truncated:
        result_data["_truncated"] = True

    # Embed the determined status in result_data so aggregate.py can report it
    result_data["status"] = status
    result_path.write_text(json.dumps(result_data, indent=2), encoding="utf-8")

    duration_ms = int((time.perf_counter() - start) * 1000)
    benchmark_note = f", bench={len(baseline_benchmark)}" if baseline_benchmark else ""
    print(f"  [hotupdate] {status}: {passed} passed, "
          f"assert_failed={assert_failed}, semantic_changed={semantic_changed}, revert={revert_passed}/{len(reverted_fact) or '?'}"
          f"{benchmark_note} ({duration_ms}ms)")

    # Build a richer summary: include stderr tail and exit code on error/crash
    error_detail = ""
    if status in ("error", "failed") and stderr:
        stderr_lines = [l for l in stderr.splitlines() if l.strip()
                       and "DEBUG" not in l and "INFO" not in l and "Gc" not in l]
        if stderr_lines:
            error_detail = " | " + "; ".join(stderr_lines[-3:])
    elif status == "error" and not hotupdate_data and r is not None:
        error_detail = f" | exit_code={r.returncode}"

    return StageResult(
        stage="hotupdate", status=status,
        summary=f"{status}: {passed} passed, assert_failed={assert_failed}, semantic_changed={semantic_changed}{error_detail}",
        details=result_data,
        duration_ms=duration_ms,
    )
