<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\managed\Chaos.IL2CPP.HotUpdate\Chaos.IL2CPP.HotUpdate.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="package\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
