
public class Program
{
    static int Main()
    {
        int failures = 0;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method0(); failures += SerializerOptionsPatchEntry._exitCode << 0;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method1(); failures += SerializerOptionsPatchEntry._exitCode << 1;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method2(); failures += SerializerOptionsPatchEntry._exitCode << 2;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method3(); failures += SerializerOptionsPatchEntry._exitCode << 3;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method4(); failures += SerializerOptionsPatchEntry._exitCode << 4;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method5(); failures += SerializerOptionsPatchEntry._exitCode << 5;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method6(); failures += SerializerOptionsPatchEntry._exitCode << 6;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method7(); failures += SerializerOptionsPatchEntry._exitCode << 7;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method8(); failures += SerializerOptionsPatchEntry._exitCode << 8;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method9(); failures += SerializerOptionsPatchEntry._exitCode << 9;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method10(); failures += SerializerOptionsPatchEntry._exitCode << 10;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method11(); failures += SerializerOptionsPatchEntry._exitCode << 11;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method12(); failures += SerializerOptionsPatchEntry._exitCode << 12;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method13(); failures += SerializerOptionsPatchEntry._exitCode << 13;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method14(); failures += SerializerOptionsPatchEntry._exitCode << 14;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method15(); failures += SerializerOptionsPatchEntry._exitCode << 15;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method16(); failures += SerializerOptionsPatchEntry._exitCode << 16;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method17(); failures += SerializerOptionsPatchEntry._exitCode << 17;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method18(); failures += SerializerOptionsPatchEntry._exitCode << 18;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method19(); failures += SerializerOptionsPatchEntry._exitCode << 19;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method20(); failures += SerializerOptionsPatchEntry._exitCode << 20;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method21(); failures += SerializerOptionsPatchEntry._exitCode << 21;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method22(); failures += SerializerOptionsPatchEntry._exitCode << 22;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method23(); failures += SerializerOptionsPatchEntry._exitCode << 23;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method24(); failures += SerializerOptionsPatchEntry._exitCode << 24;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method25(); failures += SerializerOptionsPatchEntry._exitCode << 25;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method26(); failures += SerializerOptionsPatchEntry._exitCode << 26;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method27(); failures += SerializerOptionsPatchEntry._exitCode << 27;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method28(); failures += SerializerOptionsPatchEntry._exitCode << 28;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method29(); failures += SerializerOptionsPatchEntry._exitCode << 29;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method30(); failures += SerializerOptionsPatchEntry._exitCode << 30;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method31(); failures += SerializerOptionsPatchEntry._exitCode << 31;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method32(); failures += SerializerOptionsPatchEntry._exitCode << 32;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method33(); failures += SerializerOptionsPatchEntry._exitCode << 33;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method34(); failures += SerializerOptionsPatchEntry._exitCode << 34;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method35(); failures += SerializerOptionsPatchEntry._exitCode << 35;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method36(); failures += SerializerOptionsPatchEntry._exitCode << 36;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method37(); failures += SerializerOptionsPatchEntry._exitCode << 37;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method38(); failures += SerializerOptionsPatchEntry._exitCode << 38;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method39(); failures += SerializerOptionsPatchEntry._exitCode << 39;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method40(); failures += SerializerOptionsPatchEntry._exitCode << 40;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method41(); failures += SerializerOptionsPatchEntry._exitCode << 41;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method42(); failures += SerializerOptionsPatchEntry._exitCode << 42;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method43(); failures += SerializerOptionsPatchEntry._exitCode << 43;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method44(); failures += SerializerOptionsPatchEntry._exitCode << 44;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method45(); failures += SerializerOptionsPatchEntry._exitCode << 45;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method46(); failures += SerializerOptionsPatchEntry._exitCode << 46;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method47(); failures += SerializerOptionsPatchEntry._exitCode << 47;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method48(); failures += SerializerOptionsPatchEntry._exitCode << 48;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method49(); failures += SerializerOptionsPatchEntry._exitCode << 49;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method50(); failures += SerializerOptionsPatchEntry._exitCode << 50;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method51(); failures += SerializerOptionsPatchEntry._exitCode << 51;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method52(); failures += SerializerOptionsPatchEntry._exitCode << 52;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method53(); failures += SerializerOptionsPatchEntry._exitCode << 53;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method54(); failures += SerializerOptionsPatchEntry._exitCode << 54;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method55(); failures += SerializerOptionsPatchEntry._exitCode << 55;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method56(); failures += SerializerOptionsPatchEntry._exitCode << 56;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method57(); failures += SerializerOptionsPatchEntry._exitCode << 57;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method58(); failures += SerializerOptionsPatchEntry._exitCode << 58;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method59(); failures += SerializerOptionsPatchEntry._exitCode << 59;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method60(); failures += SerializerOptionsPatchEntry._exitCode << 60;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method61(); failures += SerializerOptionsPatchEntry._exitCode << 61;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method62(); failures += SerializerOptionsPatchEntry._exitCode << 62;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method63(); failures += SerializerOptionsPatchEntry._exitCode << 63;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method64(); failures += SerializerOptionsPatchEntry._exitCode << 64;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method65(); failures += SerializerOptionsPatchEntry._exitCode << 65;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method66(); failures += SerializerOptionsPatchEntry._exitCode << 66;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method67(); failures += SerializerOptionsPatchEntry._exitCode << 67;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method68(); failures += SerializerOptionsPatchEntry._exitCode << 68;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method69(); failures += SerializerOptionsPatchEntry._exitCode << 69;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method70(); failures += SerializerOptionsPatchEntry._exitCode << 70;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method71(); failures += SerializerOptionsPatchEntry._exitCode << 71;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method72(); failures += SerializerOptionsPatchEntry._exitCode << 72;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method73(); failures += SerializerOptionsPatchEntry._exitCode << 73;
        SerializerOptionsPatchEntry._exitCode = 0; SerializerOptionsPatchEntry.Method74(); failures += SerializerOptionsPatchEntry._exitCode << 74;
        return failures;
    }
}
