// Auto-generated by Chaos.IL2CPP.AutoTestGenerator
using System;
using System.Buffers;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Data;
using System.Diagnostics;
using System.Formats.Asn1;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Numerics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Xml.Xsl;
using Microsoft.Win32.SafeHandles;
using Chaos.TestFramework;
using System;

namespace AutoGenerated.System_Private_CoreLib
{
    public unsafe partial class System_DelegateTests
    {

        [Fact]
        [HotUpdate]
        public long CreateDelegate_0_System_Type_object_string_bool_bool_0()
        {
            var result_0_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!, default(bool), default(bool));
            return (object)(result_0_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_0_System_Type_object_string_bool_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!, default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_0_System_Type_object_string_bool_bool_1()
        {
            var result_0_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "", default(bool), default(bool));
            return (object)(result_0_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_0_System_Type_object_string_bool_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "", default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_0_System_Type_object_string_bool_bool_2()
        {
            var result_0_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "", default(bool), default(bool));
            return (object)(result_0_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_0_System_Type_object_string_bool_bool_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "", default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_1_System_Type_System_Type_string_bool_bool_0()
        {
            var result_1_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!, default(bool), default(bool));
            return (object)(result_1_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_1_System_Type_System_Type_string_bool_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!, default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_1_System_Type_System_Type_string_bool_bool_1()
        {
            var result_1_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "", default(bool), default(bool));
            return (object)(result_1_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_1_System_Type_System_Type_string_bool_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "", default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_1_System_Type_System_Type_string_bool_bool_2()
        {
            var result_1_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "", default(bool), default(bool));
            return (object)(result_1_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_1_System_Type_System_Type_string_bool_bool_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "", default(bool), default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_2_System_Type_MethodInfo_bool_0()
        {
            var result_2_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!, default(bool));
            return (object)(result_2_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_2_System_Type_MethodInfo_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_2_System_Type_MethodInfo_bool_1()
        {
            var result_2_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!, false);
            return (object)(result_2_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_2_System_Type_MethodInfo_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!, false);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_2_System_Type_MethodInfo_bool_2()
        {
            var result_2_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!, default(bool));
            return (object)(result_2_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_2_System_Type_MethodInfo_bool_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_3_System_Type_object_MethodInfo_bool_0()
        {
            var result_3_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(System.Reflection.MethodInfo)!, default(bool));
            return (object)(result_3_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_3_System_Type_object_MethodInfo_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(System.Reflection.MethodInfo)!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_3_System_Type_object_MethodInfo_bool_1()
        {
            var result_3_1 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!, default(bool));
            return (object)(result_3_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_3_System_Type_object_MethodInfo_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long Clone_4__0()
        {
            var result_4_0 = SubjectInstanceFactory.Create<System.Delegate>().Clone();
            return (object)(result_4_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Clone_4__0()
        {
            _ = SubjectInstanceFactory.Create<System.Delegate>().Clone();
        }

        [Fact]
        [HotUpdate]
        public long Combine_5_System_Delegate_System_Delegate_0()
        {
            var result_5_0 = global::System.Delegate.Combine(default(System.Delegate)!, default(System.Delegate)!);
            return (object)(result_5_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Combine_5_System_Delegate_System_Delegate_0()
        {
            _ = global::System.Delegate.Combine(default(System.Delegate)!, default(System.Delegate)!);
        }

        [Fact]
        [HotUpdate]
        public long Combine_6_System_Delegate_0()
        {
            var result_6_0 = global::System.Delegate.Combine(default(System.Delegate[])!);
            return (object)(result_6_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Combine_6_System_Delegate_0()
        {
            _ = global::System.Delegate.Combine(default(System.Delegate[])!);
        }

        [Fact]
        [HotUpdate]
        public long Combine_6_System_Delegate_1()
        {
            var result_6_1 = global::System.Delegate.Combine(System.Array.Empty<System.Delegate>());
            return (object)(result_6_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Combine_6_System_Delegate_1()
        {
            _ = global::System.Delegate.Combine(System.Array.Empty<System.Delegate>());
        }

        [Fact]
        [HotUpdate]
        public long Combine_6_System_Delegate_2()
        {
            var result_6_2 = global::System.Delegate.Combine(new System.Delegate[2] { default(System.Delegate)!, default(System.Delegate)! });
            return (object)(result_6_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Combine_6_System_Delegate_2()
        {
            _ = global::System.Delegate.Combine(new System.Delegate[2] { default(System.Delegate)!, default(System.Delegate)! });
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_7_System_Type_object_MethodInfo_0()
        {
            var result_7_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(System.Reflection.MethodInfo)!);
            return (object)(result_7_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_7_System_Type_object_MethodInfo_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(System.Reflection.MethodInfo)!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_7_System_Type_object_MethodInfo_1()
        {
            var result_7_1 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!);
            return (object)(result_7_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_7_System_Type_object_MethodInfo_1()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_8_System_Type_MethodInfo_0()
        {
            var result_8_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!);
            return (object)(result_8_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_8_System_Type_MethodInfo_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Reflection.MethodInfo)!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_8_System_Type_MethodInfo_1()
        {
            var result_8_1 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!);
            return (object)(result_8_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_8_System_Type_MethodInfo_1()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample).GetMethod("SampleMethod")!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_9_System_Type_object_string_0()
        {
            var result_9_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!);
            return (object)(result_9_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_9_System_Type_object_string_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_9_System_Type_object_string_1()
        {
            var result_9_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "");
            return (object)(result_9_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_9_System_Type_object_string_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "");
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_9_System_Type_object_string_2()
        {
            var result_9_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "");
            return (object)(result_9_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_9_System_Type_object_string_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "");
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_10_System_Type_object_string_bool_0()
        {
            var result_10_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!, default(bool));
            return (object)(result_10_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_10_System_Type_object_string_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, default(string)!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_10_System_Type_object_string_bool_1()
        {
            var result_10_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "", default(bool));
            return (object)(result_10_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_10_System_Type_object_string_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(object)!, "", default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_10_System_Type_object_string_bool_2()
        {
            var result_10_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "", default(bool));
            return (object)(result_10_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_10_System_Type_object_string_bool_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), default(object)!, "", default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_11_System_Type_System_Type_string_0()
        {
            var result_11_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!);
            return (object)(result_11_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_11_System_Type_System_Type_string_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!);
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_11_System_Type_System_Type_string_1()
        {
            var result_11_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "");
            return (object)(result_11_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_11_System_Type_System_Type_string_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "");
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_11_System_Type_System_Type_string_2()
        {
            var result_11_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "");
            return (object)(result_11_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_11_System_Type_System_Type_string_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "");
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_12_System_Type_System_Type_string_bool_0()
        {
            var result_12_0 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!, default(bool));
            return (object)(result_12_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_12_System_Type_System_Type_string_bool_0()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, default(string)!, default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_12_System_Type_System_Type_string_bool_1()
        {
            var result_12_1 = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "", default(bool));
            return (object)(result_12_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_12_System_Type_System_Type_string_bool_1()
        {
            _ = global::System.Delegate.CreateDelegate(default(System.Type)!, default(System.Type)!, "", default(bool));
        }

        [Fact]
        [HotUpdate]
        public long CreateDelegate_12_System_Type_System_Type_string_bool_2()
        {
            var result_12_2 = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "", default(bool));
            return (object)(result_12_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_CreateDelegate_12_System_Type_System_Type_string_bool_2()
        {
            _ = global::System.Delegate.CreateDelegate(typeof(ReflectionSubjectSample), typeof(ReflectionSubjectSample), "", default(bool));
        }

        [Fact]
        [HotUpdate]
        public long GetInvocationList_13__0()
        {
            var result_13_0 = SubjectInstanceFactory.Create<System.Delegate>().GetInvocationList();
            return (object)(result_13_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_GetInvocationList_13__0()
        {
            _ = SubjectInstanceFactory.Create<System.Delegate>().GetInvocationList();
        }

        [Fact]
        [HotUpdate]
        public long DynamicInvoke_14_System_Object_0()
        {
            var result_14_0 = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(default(System.Object[])!);
            return (object)(result_14_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_DynamicInvoke_14_System_Object_0()
        {
            _ = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(default(System.Object[])!);
        }

        [Fact]
        [HotUpdate]
        public long DynamicInvoke_14_System_Object_1()
        {
            var result_14_1 = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(System.Array.Empty<object>());
            return (object)(result_14_1) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_DynamicInvoke_14_System_Object_1()
        {
            _ = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(System.Array.Empty<object>());
        }

        [Fact]
        [HotUpdate]
        public long DynamicInvoke_14_System_Object_2()
        {
            var result_14_2 = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(new object[2] { default(object)!, default(object)! });
            return (object)(result_14_2) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_DynamicInvoke_14_System_Object_2()
        {
            _ = SubjectInstanceFactory.Create<System.Delegate>().DynamicInvoke(new object[2] { default(object)!, default(object)! });
        }

        [Fact]
        [HotUpdate]
        public long Remove_15_System_Delegate_System_Delegate_0()
        {
            var result_15_0 = global::System.Delegate.Remove(default(System.Delegate)!, default(System.Delegate)!);
            return (object)(result_15_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_Remove_15_System_Delegate_System_Delegate_0()
        {
            _ = global::System.Delegate.Remove(default(System.Delegate)!, default(System.Delegate)!);
        }

        [Fact]
        [HotUpdate]
        public long RemoveAll_16_System_Delegate_System_Delegate_0()
        {
            var result_16_0 = global::System.Delegate.RemoveAll(default(System.Delegate)!, default(System.Delegate)!);
            return (object)(result_16_0) != null ? 1L : 0L;
        }

        [Benchmark]
        public static void Benchmark_RemoveAll_16_System_Delegate_System_Delegate_0()
        {
            _ = global::System.Delegate.RemoveAll(default(System.Delegate)!, default(System.Delegate)!);
        }
    }
}
